import {NextRequest,NextResponse} from 'next/server';import {createHash} from 'node:crypto';
import {electoralStaff} from '@/lib/electoral/auth';import {canonicalJson} from '@/lib/science/integrity';import {validInput,type LegislativeRun} from '@/lib/legislative/types';import {collectPage,officialIdentity} from '@/lib/legislative/collector';
export const dynamic='force-dynamic';export const maxDuration=60;const uuid=(v:unknown)=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v);const fail=(error:string,status=400)=>NextResponse.json({error},{status});
export async function GET(r:NextRequest){const {db,allowed}=await electoralStaff();if(!allowed)return fail('Acesso administrativo necessário.',403);const id=r.nextUrl.searchParams.get('candidate_id');if(!id){const {data,error}=await db.from('candidates').select('id,name,state_uf').order('name').limit(1000);return error?fail('Não foi possível consultar candidatos.',503):NextResponse.json({candidates:data},{headers:{'Cache-Control':'no-store'}});}if(!uuid(id))return fail('Candidato inválido.');const provider=r.nextUrl.searchParams.get('provider'),category=r.nextUrl.searchParams.get('category');const offset=Number(r.nextUrl.searchParams.get('offset')??0);if(!Number.isSafeInteger(offset)||offset<0||offset>100000)return fail('Página inválida.');let q=db.from('ibfc_legislative_records').select('id,provider,category,external_id,external_key,title,summary,occurred_on,source_url,source_hash,vote_value,fetched_at,run_id',{count:'exact'}).eq('candidate_id',id);if(provider)q=q.eq('provider',provider);if(category)q=q.eq('category',category);const [records,runs]=await Promise.all([q.order('occurred_on',{ascending:false,nullsFirst:false}).order('id').range(offset,offset+49),db.from('ibfc_legislative_runs').select('*').eq('candidate_id',id).order('created_at',{ascending:false}).limit(30)]);if(records.error||runs.error)return fail('Observatório indisponível. Execute a migração 20261025.',503);return NextResponse.json({rows:records.data,total:records.count,runs:runs.data,offset},{headers:{'Cache-Control':'no-store'}});}
export async function POST(r:NextRequest){const {db,allowed}=await electoralStaff();if(!allowed)return fail('Acesso administrativo necessário.',403);if(r.headers.get('origin')!==r.nextUrl.origin)return fail('Origem inválida.',403);let b;try{b=await r.json();}catch{return fail('Pedido inválido.');}if(!b||typeof b!=='object'||Array.isArray(b))return fail('Pedido inválido.');
 if(b.action==='verify'||b.action==='start'){const invalid=validInput(b);if(invalid)return fail(invalid);if(!uuid(b.candidate_id))return fail('Selecione um candidato.');const c=await db.from('candidates').select('id').eq('id',b.candidate_id).maybeSingle();if(c.error||!c.data)return fail('Candidato não encontrado.');try{const identity=await officialIdentity(b.provider,String(b.external_id));if(b.action==='verify')return NextResponse.json({identity});if(b.confirmed!==true)return fail('Confirme que o perfil oficial corresponde ao candidato.');const {data,error}=await db.rpc('ibfc_legislative_run_save',{p_data:{...b,external_id:String(b.external_id),official_name:identity.name}});return error?fail('Não foi possível iniciar a coleta. Confira a migração 20261025.',503):NextResponse.json({run:data});}catch(e){return fail(e instanceof Error?e.message:'Fonte oficial indisponível.',502);}}
 if(b.action!=='step'||!uuid(b.id))return fail('Ação inválida.');const result=await db.from('ibfc_legislative_runs').select('*').eq('id',b.id).single();if(result.error)return fail('Coleta indisponível.',404);const run=result.data as LegislativeRun;if(['completed','partial'].includes(run.status))return fail('Coleta encerrada.',409);
 try{const batch=await collectPage(run),records=batch.records.map(x=>({...x,source_hash:createHash('sha256').update(canonicalJson(x.payload)).digest('hex')}));const {data,error}=await db.rpc('ibfc_legislative_run_save',{p_data:{action:'commit',id:run.id,version:run.version,records,has_more:batch.hasMore,source:batch.source}});if(error)return fail(error.message.includes('outra sessão')?'Outra sessão avançou esta coleta. Atualize o histórico.':'Lote não salvo. Confira migração e integridade dos registros.',409);return NextResponse.json({run:data});}catch(e){const message=e instanceof Error?e.message:'Falha ao consultar fonte oficial.';const {error}=await db.rpc('ibfc_legislative_run_save',{p_data:{action:'fail',id:run.id,version:run.version,error:message}});return fail(error?'Falha de coleta e de registro do erro. Atualize o histórico.':message,502);}
}
