'use client';
import Link from 'next/link';import {useEffect,useState} from 'react';
import {ACTIVITY_STATUS,type CommunityActivity} from '@/lib/community/activities';
import {brazilDate} from '@/lib/community/demands';
import './community.css';import './activities.css';
type Organization={id:string;name:string};
export function ActivityWorkspace(){
 const [organizations,setOrganizations]=useState<Organization[]>([]),[rows,setRows]=useState<CommunityActivity[]>([]),[total,setTotal]=useState(0),[truncated,setTruncated]=useState(false),[selected,setSelected]=useState<CommunityActivity|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[filter,setFilter]=useState('');
 async function load(){const r=await fetch('/api/admin/community/activities',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);setRows(d.rows);setTotal(d.total);setTruncated(d.truncated);}
 useEffect(()=>{let disposed=false;Promise.all([fetch('/api/admin/community').then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);if(!disposed)setOrganizations(d.organizations);}),load()]).catch(e=>{if(!disposed)setError(e.message);}).finally(()=>{if(!disposed)setLoading(false);});return()=>{disposed=true;};},[]);
 async function send(body:Record<string,unknown>,form:HTMLFormElement,attendance=false){setSaving(true);setError('');setMessage('');try{const r=await fetch(attendance?'/api/admin/community':'/api/admin/community/activities',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error);form.reset();await load();setSelected(null);setMessage(attendance?'Presença vinculada à atividade.':'Atividade salva.');}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar.');}finally{setSaving(false);}}
 function submit(e:React.FormEvent<HTMLFormElement>,action:string){e.preventDefault();const form=e.currentTarget,b=Object.fromEntries(new FormData(form));if(action==='participation'&&selected)void send({...b,action,organization_id:selected.organization_id,activity_id:selected.id,activity:selected.title,authorized:b.authorized==='on'},form,true);else void send({...b,action,...(action==='status'&&selected?{id:selected.id,version:selected.version}:{})},form);}
 const visible=rows.filter(a=>!filter||a.status===filter),today=brazilDate();
 return <main className="community-workspace"><header><small>IBFC · Programação comunitária</small><h1>Atividades comunitárias</h1><p>Planeje ações e registre presença realizada com autorização. Capacidade é uma estimativa de planejamento; presenças registradas não equivalem a pessoas únicas.</p><Link href="/admin/comunidade">← Organizações e participação</Link></header>{error&&<p className="community-error" role="alert">{error}</p>}{message&&<p className="community-success" role="status">{message}</p>}
 <div className="community-forms"><section><h2>Nova atividade</h2><form onSubmit={e=>submit(e,'create')}><label>Organização<select aria-label="Organização da atividade" name="organization_id" required defaultValue=""><option value="" disabled>Selecione</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Título da atividade<input name="title" minLength={3} maxLength={160} required/></label><label>Objetivo comunitário<textarea name="objective" minLength={5} maxLength={1000} required/></label><div className="activity-row"><label>Data inicial<input type="date" name="start_on" required/></label><label>Data final<input type="date" name="end_on" required/></label></div><label>Local público de realização<input name="venue" minLength={3} maxLength={300} required/></label><label>Responsável pela atividade<input name="responsible" maxLength={160}/></label><label>Capacidade planejada (opcional)<input type="number" name="capacity" min={1} max={100000} step={1}/></label><button disabled={saving||!organizations.length}>{saving?'Salvando…':'Cadastrar atividade'}</button></form></section>
 <section><h2>Atividade selecionada</h2>{!selected?<p>Selecione uma atividade na tabela para atualizar sua situação ou registrar presença.</p>:<><h3>{selected.title}</h3><p>{selected.organization_name} · {selected.municipality}/{selected.uf}</p><p>{selected.objective}</p><p>{selected.start_on} a {selected.end_on} · {selected.venue}</p><p>Capacidade planejada: {selected.capacity??'Não informada'} · Registros de presença: {selected.attendance_total} · Autorização vigente: {selected.authorized_records}</p><form key={selected.id+':status'} onSubmit={e=>submit(e,'status')}><label>Situação da atividade<select aria-label="Situação da atividade" name="status" defaultValue={selected.status}>{Object.entries(ACTIVITY_STATUS).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>Justificativa da alteração<textarea name="note" required minLength={5} maxLength={1000}/></label><button disabled={saving}>Atualizar situação</button></form>{selected.status_note&&<p>Última justificativa: {selected.status_note}</p>}
 <p><Link href={`/admin/comunidade/inscricoes?atividade=${selected.id}`}>Gerenciar inscrições e fila de espera</Link></p><h3>Registrar presença realizada</h3>{selected.status==='cancelada'||selected.start_on>today?<p>Presença indisponível: atividade cancelada ou ainda não iniciada.</p>:<form key={selected.id+':presence'} onSubmit={e=>submit(e,'participation')}><label>Nome do participante<input name="name" required minLength={2} maxLength={160}/></label><label>Data da presença<input type="date" name="participated_on" min={selected.start_on} max={selected.end_on<today?selected.end_on:today} defaultValue={selected.start_on} required/></label><label>Referência da autorização<textarea name="consent_evidence" minLength={5} maxLength={500} required placeholder="Referência do termo autorizado, sem documentos pessoais."/></label><label className="community-check"><input type="checkbox" name="authorized" required/>Confirmo a autorização voluntária para registrar a presença.</label><button disabled={saving}>Registrar presença</button></form>}<p>Retirada da autorização e exclusão ficam em Organizações e participação. Registros antigos sem vínculo continuam preservados.</p></>}</section></div>
 <section><h2>Programação e registros</h2><label>Filtrar atividades<select aria-label="Filtrar atividades" value={filter} onChange={e=>{setFilter(e.target.value);setSelected(null);}}><option value="">Todas</option>{Object.entries(ACTIVITY_STATUS).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label>{loading?<p role="status">Carregando atividades…</p>:<><p>{visible.length} atividades exibidas · {total} cadastradas na base.</p>{truncated&&<p role="alert" className="community-error">Lista parcial: até 500 atividades, ordenadas da data inicial mais recente para a mais antiga. O filtro opera sobre esta lista.</p>}<div className="community-table"><table><thead><tr><th>Atividade</th><th>Organização / região</th><th>Datas</th><th>Situação</th><th>Registros de presença</th></tr></thead><tbody>{visible.map(a=><tr key={a.id}><td><button disabled={saving} onClick={()=>{setSelected(a);setMessage('');}}>{a.title}</button></td><td>{a.organization_name}<br/>{a.municipality}/{a.uf}</td><td>{a.start_on}<br/>{a.end_on}</td><td>{ACTIVITY_STATUS[a.status]}</td><td>{a.attendance_total} · {a.authorized_records} com autorização vigente</td></tr>)}</tbody></table></div>{!visible.length&&<p>Nenhuma atividade neste recorte.</p>}</> }</section></main>;
}
