'use client';
import {useEffect,useState} from 'react';
import {UFS} from '@/lib/science/territory';
import './community.css';
type Organization={id:string;name:string;uf:string;municipality:string;territory:string;purpose:string};
type Participation={id:string;organization_id:string;name:string;activity:string;participated_on:string;withdrawn_at:string|null};
export function CommunityWorkspace(){
 const [organizations,setOrganizations]=useState<Organization[]>([]),[participation,setParticipation]=useState<Participation[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[limit,setLimit]=useState(500);
 async function load(){const r=await fetch('/api/admin/community',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);setOrganizations(d.organizations);setParticipation(d.participation);setLimit(d.limit);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function save(body:Record<string,unknown>,form?:HTMLFormElement){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/admin/community',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error);await load();form?.reset();setMessage(body.action==='delete'?'Registro excluído.':'Alteração salva.');}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar.');}finally{setBusy(false);}}
 function submit(e:React.FormEvent<HTMLFormElement>,action:string){e.preventDefault();const f=e.currentTarget,v=Object.fromEntries(new FormData(f));void save({...v,action,authorized:v.authorized==='on'},f);}
 return <main className="community-workspace"><header><small>IBFC · Gestão comunitária</small><h1>Comunidade e participação</h1><p>Organizações e atividades voluntárias realizadas. Estes registros não representam votos, apoio eleitoral confirmado ou preferência partidária.</p></header>
 {error&&<p role="alert" className="community-error">{error}</p>}{message&&<p role="status" className="community-success">{message}</p>}
 <div className="community-forms"><section><h2>Cadastrar organização</h2><form onSubmit={e=>submit(e,'organization')}><label>Nome<input name="name" required minLength={2} maxLength={160}/></label><div className="community-row"><label>UF<select name="uf" defaultValue="DF">{UFS.map(uf=><option key={uf}>{uf}</option>)}</select></label><label>Município<input name="municipality" required minLength={2} maxLength={160}/></label></div><label>RA / bairro (opcional)<input name="territory" maxLength={160}/></label><label>Finalidade comunitária<textarea name="purpose" maxLength={500}/></label><button disabled={busy}>{busy?'Salvando…':'Cadastrar organização'}</button></form></section>
 <section><h2>Registrar participação realizada</h2><form onSubmit={e=>submit(e,'participation')}><label>Organização<select name="organization_id" required defaultValue=""><option value="" disabled>Selecione uma organização</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.name} · {o.municipality}/{o.uf}</option>)}</select></label><label>Nome do participante<input name="name" required minLength={2} maxLength={160}/></label><label>Atividade<input name="activity" required minLength={2} maxLength={160}/></label><label>Data da participação<input type="date" name="participated_on" required max={new Date().toISOString().slice(0,10)}/></label><label>Referência da autorização<textarea name="consent_evidence" required minLength={5} maxLength={500} placeholder="Ex.: termo autorizado no cadastro, protocolo e data. Não inclua documentos pessoais."/></label><label className="community-check"><input type="checkbox" name="authorized" required/>Confirmo que o participante autorizou este registro voluntariamente.</label><button disabled={busy||!organizations.length}>{busy?'Salvando…':'Registrar participação'}</button></form></section></div>
 <section><h2>Organizações cadastradas</h2>{!organizations.length?<p>Nenhuma organização cadastrada.</p>:<ul className="community-organizations">{organizations.map(o=><li key={o.id}><strong>{o.name}</strong><span>{o.municipality}/{o.uf}{o.territory?` · ${o.territory}`:''}</span><p>{o.purpose}</p></li>)}</ul>}</section>
 <section><h2>Registros recentes de participação</h2><p>Acesso restrito a administradores e editores. Retirar autorização mantém o registro marcado; excluir remove o registro pessoal.</p><div className="community-table"><table><thead><tr><th>Participante</th><th>Organização</th><th>Atividade / data</th><th>Situação</th><th>Ações</th></tr></thead><tbody>{participation.map(p=><tr key={p.id}><td>{p.name}</td><td>{organizations.find(o=>o.id===p.organization_id)?.name??'Organização fora da página'}</td><td>{p.activity}<br/>{p.participated_on}</td><td>{p.withdrawn_at?'Autorização retirada':'Autorizado'}</td><td>{!p.withdrawn_at&&<button disabled={busy} onClick={()=>{if(window.confirm('Registrar a retirada da autorização?'))void save({action:'withdraw',id:p.id});}}>Retirar autorização</button>}<button className="community-delete" disabled={busy} onClick={()=>{if(window.confirm('Excluir definitivamente este registro pessoal?'))void save({action:'delete',id:p.id});}}>Excluir</button></td></tr>)}</tbody></table></div>{!participation.length&&<p>Nenhuma participação registrada.</p>}{(participation.length>=limit||organizations.length>=limit)&&<p role="status">Exibindo até {limit} registros por lista. A lista não representa o total da base.</p>}</section></main>;
}
