'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {UFS} from '@/lib/science/territory';
import {communityLayer,hasCoordinates,type CommunityMapData} from '@/lib/community/map';
import {CommunityLeafletMap} from './CommunityLeafletMap';
import './community.css';
import './community-map.css';
export function CommunityMapWorkspace(){
 const [data,setData]=useState<CommunityMapData|null>(null),[uf,setUf]=useState('DF'),[municipality,setMunicipality]=useState(''),[territory,setTerritory]=useState(''),[organizations,setOrganizations]=useState(true),[demands,setDemands]=useState(false),[selectedId,setSelectedId]=useState(''),[latitude,setLatitude]=useState(''),[longitude,setLongitude]=useState(''),[note,setNote]=useState(''),[confirmed,setConfirmed]=useState(false),[picking,setPicking]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[reload,setReload]=useState(0);
 useEffect(()=>{const abort=new AbortController();setLoading(true);setError('');setData(null);fetch(`/api/admin/community/map?${new URLSearchParams({uf})}`,{signal:abort.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);}).catch(e=>{if(!abort.signal.aborted)setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[uf,reload]);
 const municipalities=useMemo(()=>[...new Set(data?.rows.map(p=>p.municipality)??[])].sort(),[data]);
 const territories=useMemo(()=>[...new Set((data?.rows??[]).filter(p=>!municipality||p.municipality===municipality).map(p=>p.territory).filter(Boolean))].sort(),[data,municipality]);
 const filtered=useMemo(()=>(data?.rows??[]).filter(p=>(!municipality||p.municipality===municipality)&&(!territory||p.territory===territory)),[data,municipality,territory]);
 const visible=useMemo(()=>communityLayer(filtered,organizations,demands),[filtered,organizations,demands]),selected=data?.rows.find(p=>p.id===selectedId);
 useEffect(()=>{setLatitude(selected?.latitude?.toString()??'');setLongitude(selected?.longitude?.toString()??'');setNote(selected?.location_note??'');setConfirmed(false);setPicking(false);},[selected]);
 function choose(id:string){setSelectedId(id);setMessage('');}
 function location(lat:number,lng:number){setLatitude(lat.toFixed(6));setLongitude(lng.toFixed(6));setPicking(false);setConfirmed(false);}
 async function save(clear=false){if(!selected)return;if(clear&&!window.confirm('Remover as coordenadas deste ponto? A organização e as demandas serão mantidas.'))return;setSaving(true);setError('');setMessage('');try{const r=await fetch('/api/admin/community/map',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected.id,latitude:clear?null:latitude.trim()===''?null:Number(latitude),longitude:clear?null:longitude.trim()===''?null:Number(longitude),note,confirmed})}),d=await r.json();if(!r.ok)throw new Error(d.error);setReload(n=>n+1);setMessage(clear?'Coordenadas removidas.':'Ponto público de atendimento salvo.');}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar.');}finally{setSaving(false);}}
 const missing=visible.filter(p=>!hasCoordinates(p)).length;
 return <main className="community-workspace community-map-workspace"><header><small>IBFC · Gestão territorial de serviços</small><h1>Mapa comunitário</h1><p>Visualize organizações e demandas de atendimento. Os números nos círculos são demandas abertas; não representam pessoas ou votos.</p><div className="community-map-links"><Link href="/admin/comunidade">Organizações e participação</Link><Link href="/admin/comunidade/demandas">Demandas e atendimento</Link></div></header>
 {error&&<p className="community-error" role="alert">{error}</p>}{message&&<p className="community-success" role="status">{message}</p>}
 <section><h2>Região e camadas</h2><div className="community-map-filters"><label>UF<select aria-label="UF do mapa comunitário" value={uf} onChange={e=>{setUf(e.target.value);setMunicipality('');setTerritory('');setSelectedId('');}}><option value="">Todas as UFs cadastradas</option>{UFS.map(v=><option key={v}>{v}</option>)}</select></label><label>Município<select aria-label="Município do mapa comunitário" value={municipality} onChange={e=>{setMunicipality(e.target.value);setTerritory('');setSelectedId('');}}><option value="">Todos</option>{municipalities.map(v=><option key={v}>{v}</option>)}</select></label><label>RA / bairro<select aria-label="RA ou bairro do mapa comunitário" value={territory} onChange={e=>{setTerritory(e.target.value);setSelectedId('');}}><option value="">Todos</option>{territories.map(v=><option key={v}>{v}</option>)}</select></label></div><div className="community-map-layers"><label className="community-check"><input type="checkbox" checked={organizations} onChange={e=>setOrganizations(e.target.checked)}/><i className="community-dot green"/>Organizações</label><label className="community-check"><input type="checkbox" checked={demands} onChange={e=>setDemands(e.target.checked)}/><i className="community-dot amber"/>Demandas abertas — número no círculo</label><button disabled={loading||saving} onClick={()=>{setSelectedId('');setReload(n=>n+1);}}>Atualizar mapa</button></div></section>
 {loading&&<p role="status">Consultando organizações e demandas…</p>}{data&&<><p>{filtered.length} organizações no recorte carregado · {visible.length-missing} pontos da camada com coordenadas · {missing} sem coordenadas na tabela.</p>{data.truncated&&<p role="alert" className="community-error">Cobertura parcial: limite de 1.000 organizações por consulta, de {data.total} cadastradas nesta UF. Restrinja a UF; não interprete esta tela como toda a base.</p>}{data.unlinked_demands>0&&<p>{data.unlinked_demands} demandas em toda a base sem organização vinculada não têm ponto neste mapa.</p>}
 <div className="community-map-layout"><section className="community-map-panel"><CommunityLeafletMap places={visible} demands={demands} picking={picking} onSelect={choose} onLocation={location}/>{!organizations&&!demands&&<p>Nenhuma camada selecionada. Ative uma das opções acima.</p>}{picking&&<p role="status">Clique no mapa de ruas para escolher o ponto público da organização. O local só será salvo após sua confirmação.</p>}</section><section className="community-map-detail"><h2>{selected?.name??'Selecione uma organização'}</h2>{selected?<><p>{selected.municipality}/{selected.uf}{selected.territory?` · ${selected.territory}`:''}</p><p>{selected.purpose}</p><dl><dt>Demandas registradas</dt><dd>{selected.demands_total}</dd><dt>Demandas abertas</dt><dd>{selected.demands_open}</dd><dt>Com prazo vencido</dt><dd>{selected.demands_overdue}</dd></dl><h3>Ponto público de atendimento</h3><form onSubmit={e=>{e.preventDefault();void save();}}><label>Latitude<input type="number" step="any" min="-90" max="90" required value={latitude} onChange={e=>{setLatitude(e.target.value);setConfirmed(false);}}/></label><label>Longitude<input type="number" step="any" min="-180" max="180" required value={longitude} onChange={e=>{setLongitude(e.target.value);setConfirmed(false);}}/></label><button type="button" disabled={saving} onClick={()=>setPicking(v=>!v)}>{picking?'Cancelar escolha no mapa':'Escolher ponto no mapa'}</button><label>Referência do local<textarea required minLength={5} maxLength={300} value={note} onChange={e=>setNote(e.target.value)} placeholder="Ex.: sede pública da organização, conferida no mapa."/></label><label className="community-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} required/>Confirmo que é um ponto público de atendimento, não um endereço residencial de participante.</label><button disabled={saving}>{saving?'Salvando…':'Salvar localização'}</button>{hasCoordinates(selected)&&<button className="community-map-clear" type="button" disabled={saving} onClick={()=>void save(true)}>Remover coordenadas</button>}</form><p className="community-map-caption">Local informado pela equipe; não houve geocodificação automática nem validação externa.</p></>:<p>Clique em um ponto ou escolha uma organização na tabela. Registros sem coordenadas podem receber localização aqui.</p>}</section></div>
 <section><h2>Organizações no recorte</h2><p>A tabela mantém os registros sem coordenadas e permite posicioná-los. As opções de camadas controlam somente os pontos do mapa.</p><div className="community-table"><table><thead><tr><th>Organização</th><th>Município / RA</th><th>Demandas abertas</th><th>Prazo vencido</th><th>Localização</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><button disabled={saving} onClick={()=>choose(p.id)}>{p.name}</button></td><td>{p.municipality}/{p.uf}<br/>{p.territory}</td><td>{p.demands_open}</td><td>{p.demands_overdue}</td><td>{hasCoordinates(p)?'Ponto informado pela equipe':'Sem coordenadas'}</td></tr>)}</tbody></table></div>{!filtered.length&&<p>Nenhuma organização neste recorte. Cadastre em Organizações e participação.</p>}</section></>}
 </main>;
}
