'use client';
import Link from 'next/link';import {useEffect,useRef,useState} from 'react';
import {UFS} from '@/lib/science/territory';
import {DEMAND_CATEGORY,DEMAND_STATUS} from '@/lib/community/demands';
import {EMPTY_REPORT_FILTERS,communityReportCsv,validateReportFilters,type ReportFilters,type CommunityReport} from '@/lib/community/reports';
import './community.css';import './community-reports.css';
export function CommunityReports(){
 const [filters,setFilters]=useState<ReportFilters>({...EMPTY_REPORT_FILTERS}),[report,setReport]=useState<CommunityReport|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');const request=useRef<AbortController|null>(null);
 useEffect(()=>()=>request.current?.abort(),[]);
 const change=(k:keyof ReportFilters,v:string)=>setFilters(f=>({...f,[k]:v}));
 async function generate(){const problem=validateReportFilters(filters);if(problem){setError(problem);setReport(null);return;}request.current?.abort();const controller=new AbortController();request.current=controller;setLoading(true);setError('');setReport(null);try{const r=await fetch('/api/admin/community/reports?'+new URLSearchParams(filters),{signal:controller.signal,cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);setReport(d);}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Falha ao gerar.');}finally{if(!controller.signal.aborted)setLoading(false);}}
 function download(){if(!report)return;const url=URL.createObjectURL(new Blob([communityReportCsv(report)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='IBFC_relatorio_atendimento.csv';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const applied=report?Object.entries(report.filters).filter(([,v])=>v).map(([k,v])=>`${({uf:'UF',municipality:'Município',territory:'RA/bairro',status:'Situação',category:'Tema',from:'Desde',to:'Até'} as Record<string,string>)[k]}: ${k==='status'?DEMAND_STATUS[v as keyof typeof DEMAND_STATUS]:k==='category'?DEMAND_CATEGORY[v as keyof typeof DEMAND_CATEGORY]:v}`).join(' · '):'';
 return <main className="community-workspace community-reports"><header><small>IBFC · Monitoramento de serviços</small><h1>Relatórios de atendimento</h1><p>Resultados dos registros comunitários: andamento, temas e prazos. Não constituem avaliação eleitoral nem comprovação externa de entrega de serviços.</p><Link className="community-report-controls" href="/admin/comunidade/demandas">← Demandas e atendimento</Link></header>
 <section className="community-report-controls"><h2>Recorte do relatório</h2><form onSubmit={e=>{e.preventDefault();void generate();}}><div className="community-report-filters"><label>UF<select aria-label="UF do relatório" value={filters.uf} onChange={e=>change('uf',e.target.value)}><option value="">Todas</option>{UFS.map(v=><option key={v}>{v}</option>)}</select></label><label>Município (nome exato)<input value={filters.municipality} maxLength={160} onChange={e=>change('municipality',e.target.value)}/></label><label>RA / bairro (nome exato)<input value={filters.territory} maxLength={160} onChange={e=>change('territory',e.target.value)}/></label><label>Situação<select aria-label="Situação do relatório" value={filters.status} onChange={e=>change('status',e.target.value)}><option value="">Todas</option>{Object.entries(DEMAND_STATUS).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>Tema<select aria-label="Tema do relatório" value={filters.category} onChange={e=>change('category',e.target.value)}><option value="">Todos</option>{Object.entries(DEMAND_CATEGORY).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>Registradas desde<input type="date" value={filters.from} onChange={e=>change('from',e.target.value)}/></label><label>Registradas até<input type="date" value={filters.to} onChange={e=>change('to',e.target.value)}/></label></div><button disabled={loading}>{loading?'Gerando…':'Gerar relatório'}</button></form><p>Período pela data de criação, no horário de Brasília. Demanda sem organização não entra em filtros de UF, município ou bairro.</p></section>
 {error&&<p role="alert" className="community-error">{error}</p>}{loading&&<p role="status">Calculando o relatório…</p>}
 {report&&<div className="community-report-result"><section><h2>Resultado do recorte</h2><p>{applied||'Todos os registros, sem filtro.'}</p><p>Gerado em {new Date(report.generated_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})} · horário de Brasília.</p><div className="community-report-controls community-report-actions"><button onClick={download}>Baixar planilha CSV</button><button onClick={()=>window.print()}>Imprimir / salvar PDF</button></div><div className="community-report-metrics">{[['Total',report.summary.total],['Em aberto',report.summary.open],['Resolvidas',report.summary.resolved],['Canceladas',report.summary.cancelled],['Prazo vencido',report.summary.overdue],['Sem organização',report.summary.without_organization]].map(([label,n])=><div key={label}><small>{label}</small><strong>{n}</strong></div>)}</div><p>Indicadores e agrupamentos calculados sobre todo o filtro. Prazo vencido exclui resolvidas e canceladas; ausência de prazo não significa atraso.</p></section>
 <div className="community-report-groups"><section><h2>Por tema</h2><div className="community-table"><table><thead><tr><th>Tema</th><th>Total</th><th>Resolvidas</th><th>Vencidas</th></tr></thead><tbody>{report.categories.map(r=><tr key={r.category}><td>{DEMAND_CATEGORY[r.category]}</td><td>{r.total}</td><td>{r.resolved}</td><td>{r.overdue}</td></tr>)}</tbody></table></div></section><section><h2>Por município</h2>{report.regions_truncated&&<p role="alert">Agrupamento limitado aos 500 municípios com mais registros. Restrinja a UF.</p>}<div className="community-table"><table><thead><tr><th>Município / UF</th><th>Total</th><th>Resolvidas</th><th>Vencidas</th></tr></thead><tbody>{report.regions.map(r=><tr key={`${r.uf}:${r.municipality}`}><td>{r.municipality?`${r.municipality}/${r.uf}`:'Sem organização'}</td><td>{r.total}</td><td>{r.resolved}</td><td>{r.overdue}</td></tr>)}</tbody></table></div></section></div>
 <section><h2>Demandas detalhadas</h2><p>{report.rows.length} linhas exibidas/exportadas de {report.total} no filtro.</p>{report.truncated&&<p role="alert" className="community-error">Lista parcial: apenas as 1.000 demandas mais recentes. A planilha e a impressão detalhada seguem esse limite. Restrinja os filtros para exportar um recorte completo.</p>}<div className="community-table"><table><thead><tr><th>Demanda</th><th>Organização</th><th>Situação</th><th>Responsável interno</th><th>Prazo</th></tr></thead><tbody>{report.rows.map(r=><tr key={r.id}><td>{r.title}</td><td>{r.organization_name??'Sem organização'}</td><td>{DEMAND_STATUS[r.status]}</td><td>{r.responsible||'Não atribuído'}</td><td>{r.due_on??'Sem prazo'}{r.overdue?' · Vencido':''}</td></tr>)}</tbody></table></div>{!report.total&&<p>Nenhuma demanda neste filtro.</p>}</section></div>}
 </main>;
}
