'use client';
import Link from 'next/link';
import {useCallback,useEffect,useRef,useState} from 'react';
import {DEMAND_CATEGORY,DEMAND_PRIORITY,DEMAND_STATUS,isOverdue,type Demand,type DemandEvent} from '@/lib/community/demands';
import './community.css';
import './demands.css';
type Organization={id:string;name:string};
type List={rows:Demand[];total:number;pageSize:number;summary:{total:number;open:number;resolved:number;overdue:number;first_response_hours:number|null;resolution_hours:number|null}};
const date=(v:string|null)=>v?v.split('-').reverse().join('/'):'Sem prazo';
const time=(v:string)=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Sao_Paulo'}).format(new Date(v));
export function DemandWorkspace(){
 const [data,setData]=useState<List|null>(null),[organizations,setOrganizations]=useState<Organization[]>([]),[status,setStatus]=useState(''),[category,setCategory]=useState(''),[page,setPage]=useState(0),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[selected,setSelected]=useState<Demand|null>(null),[events,setEvents]=useState<DemandEvent[]>([]),[historyLoading,setHistoryLoading]=useState(false),[historyError,setHistoryError]=useState(''),[reload,setReload]=useState(0);
 const detailRef=useRef<HTMLElement>(null);
 useEffect(()=>{const abort=new AbortController();fetch('/api/admin/community',{signal:abort.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setOrganizations(d.organizations);}).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[]);
 useEffect(()=>{const abort=new AbortController();setLoading(true);setError('');fetch(`/api/admin/community/demands?${new URLSearchParams({status,category,page:String(page)})}`,{signal:abort.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);}).catch(e=>{if(!abort.signal.aborted){setError(e.message);setData(null);}}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[status,category,page,reload]);
 useEffect(()=>{if(!selected){setEvents([]);return;}const abort=new AbortController();setEvents([]);setHistoryError('');setHistoryLoading(true);fetch(`/api/admin/community/demands?id=${selected.id}`,{signal:abort.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setEvents(d.events);}).catch(e=>{if(!abort.signal.aborted)setHistoryError(e.message);}).finally(()=>{if(!abort.signal.aborted)setHistoryLoading(false);});return()=>abort.abort();},[selected]);
 const refresh=useCallback(()=>{setSelected(null);setReload(n=>n+1);},[]);
 async function save(body:Record<string,unknown>,form:HTMLFormElement){setSaving(true);setError('');setMessage('');try{const r=await fetch('/api/admin/community/demands',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error);form.reset();refresh();setMessage(body.action==='create'?'Demanda registrada.':'Atendimento registrado no histórico.');}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar.');}finally{setSaving(false);}}
 function submit(e:React.FormEvent<HTMLFormElement>,action:'create'|'update'){e.preventDefault();const f=e.currentTarget,b=Object.fromEntries(new FormData(f));void save({...b,action,...(action==='update'&&selected?{id:selected.id,version:selected.version}:{})},f);}
 function choose(d:Demand){setSelected(d);setTimeout(()=>detailRef.current?.scrollIntoView({behavior:'smooth',block:'start'}),0);}
 return <main className="community-workspace demand-workspace"><header><small>IBFC · Comunicação e monitoramento</small><h1>Demandas e atendimento</h1><p>Organize solicitações comunitárias, responsáveis, prazos e respostas. O registro interno não envia mensagens nem comprova resposta de uma autoridade.</p><Link href="/admin/comunidade">← Organizações e participação</Link></header>
 {error&&<p role="alert" className="community-error">{error}</p>}{message&&<p role="status" className="community-success">{message}</p>}
 {data&&<><p className="demand-caption">Indicadores de toda a base, independentemente dos filtros. Tempos médios usam os registros internos de atendimento; não comprovam tempo de resposta de uma autoridade.</p><div className="demand-metrics">{[['Total',data.summary.total],['Em aberto',data.summary.open],['Resolvidas',data.summary.resolved],['Prazo vencido',data.summary.overdue],['Primeiro atendimento (média)',data.summary.first_response_hours==null?'—':`${data.summary.first_response_hours} h`],['Conclusão (média)',data.summary.resolution_hours==null?'—':`${data.summary.resolution_hours} h`]].map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div></>}
 <div className="community-forms"><section><h2>Nova demanda</h2><form onSubmit={e=>submit(e,'create')}><label>Título<input name="title" minLength={3} maxLength={160} required/></label><label>Descrição da necessidade<textarea name="description" minLength={5} maxLength={2000} required placeholder="Descreva o problema comunitário sem dados pessoais ou prontuários."/></label><label>Organização (opcional)<select aria-label="Organização (opcional)" name="organization_id" defaultValue=""><option value="">Sem organização vinculada</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><div className="demand-row"><label>Categoria<select aria-label="Categoria" name="category">{Object.entries(DEMAND_CATEGORY).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>Prioridade<select aria-label="Prioridade" name="priority">{Object.entries(DEMAND_PRIORITY).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label></div><label>Responsável interno<input name="responsible" maxLength={160}/></label><label>Prazo previsto<input name="due_on" type="date"/></label><button disabled={saving}>{saving?'Salvando…':'Cadastrar demanda'}</button></form></section>
 <section ref={detailRef}><h2>Atendimento e histórico</h2>{!selected?<p>Selecione uma demanda na lista para registrar andamento ou conclusão.</p>:<><h3>{selected.title}</h3><p className="demand-description">{selected.description}</p><p>{DEMAND_CATEGORY[selected.category]} · {DEMAND_PRIORITY[selected.priority]} · Criada em {time(selected.created_at)}</p><form key={`${selected.id}:${selected.version}`} onSubmit={e=>submit(e,'update')}><label>Situação<select aria-label="Situação" name="status" defaultValue={selected.status}>{Object.entries(DEMAND_STATUS).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>Responsável pelo acompanhamento<input name="responsible" maxLength={160} defaultValue={selected.responsible}/></label><label>Prazo de retorno<input name="due_on" type="date" defaultValue={selected.due_on??''}/></label><label>Registro do atendimento / justificativa<textarea name="note" minLength={5} maxLength={2000} required placeholder="Registre o andamento. Para concluir ou cancelar, explique o resultado."/></label><button disabled={saving}>{saving?'Salvando…':'Salvar atendimento'}</button></form><h3>Histórico</h3>{historyLoading&&<p role="status">Carregando histórico…</p>}{historyError&&<p role="alert">{historyError}</p>}<ol className="demand-history">{events.map(e=><li key={e.id}><strong>{DEMAND_STATUS[e.new_status]}</strong><small>{time(e.created_at)}</small><p>{e.note}</p></li>)}</ol></>}</section></div>
 <section><h2>Fila de demandas</h2><div className="demand-filters"><label>Filtrar situação<select aria-label="Filtrar situação" value={status} onChange={e=>{setStatus(e.target.value);setPage(0);setSelected(null);}}><option value="">Todas as situações</option>{Object.entries(DEMAND_STATUS).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>Filtrar categoria<select aria-label="Filtrar categoria" value={category} onChange={e=>{setCategory(e.target.value);setPage(0);setSelected(null);}}><option value="">Todas as categorias</option>{Object.entries(DEMAND_CATEGORY).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><button type="button" disabled={loading||saving} onClick={refresh}>Atualizar lista</button></div>{loading?<p role="status">Consultando demandas…</p>:data&&<><p>{data.total} demandas neste filtro · página {page+1} de {Math.max(1,Math.ceil(data.total/data.pageSize))}</p><div className="community-table"><table><thead><tr><th>Demanda</th><th>Categoria / prioridade</th><th>Situação</th><th>Responsável</th><th>Prazo</th></tr></thead><tbody>{data.rows.map(d=><tr key={d.id}><td><button onClick={()=>choose(d)} disabled={saving}>{d.title}</button></td><td>{DEMAND_CATEGORY[d.category]}<br/>{DEMAND_PRIORITY[d.priority]}</td><td>{DEMAND_STATUS[d.status]}</td><td>{d.responsible||'Não atribuído'}</td><td>{date(d.due_on)}{isOverdue(d)&&<span className="demand-overdue">Vencido</span>}</td></tr>)}</tbody></table></div>{!data.rows.length&&<p>Nenhuma demanda neste filtro.</p>}<div className="demand-pages"><button disabled={page===0||saving} onClick={()=>{setPage(p=>p-1);setSelected(null);}}>Anterior</button><button disabled={(page+1)*data.pageSize>=data.total||saving} onClick={()=>{setPage(p=>p+1);setSelected(null);}}>Próxima</button></div></>}</section></main>;
}
