'use client';
import Link from 'next/link';import {useEffect,useState} from 'react';
import {ACTIVITY_STATUS,type CommunityActivity} from '@/lib/community/activities';
import {brazilDate} from '@/lib/community/demands';
import {ENROLLMENT_STATUS,type EnrollmentData} from '@/lib/community/enrollments';
import './community.css';import './enrollments.css';
export function EnrollmentWorkspace({initialActivity=''}:{initialActivity?:string}){
 const [activities,setActivities]=useState<CommunityActivity[]>([]),[activityId,setActivityId]=useState(initialActivity),[data,setData]=useState<EnrollmentData|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[reload,setReload]=useState(0),[activityLimit,setActivityLimit]=useState(false);
 useEffect(()=>{const abort=new AbortController();fetch('/api/admin/community/activities',{signal:abort.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setActivities(d.rows);setActivityLimit(d.truncated);if(initialActivity&&!d.rows.some((a:CommunityActivity)=>a.id===initialActivity)){setActivityId('');setMessage('Atividade fora da lista disponível. Selecione uma atividade.');}}).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[initialActivity]);
 useEffect(()=>{setData(null);if(!activityId)return;const abort=new AbortController();setLoading(true);setError('');fetch('/api/admin/community/enrollments?'+new URLSearchParams({activity_id:activityId}),{signal:abort.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);}).catch(e=>{if(!abort.signal.aborted)setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[activityId,reload]);
 const selected=activities.find(a=>a.id===activityId),closed=!selected||selected.status==='cancelada'||selected.status==='concluida'||selected.end_on<brazilDate();
 async function save(body:Record<string,unknown>,form?:HTMLFormElement){setSaving(true);setError('');setMessage('');try{const r=await fetch('/api/admin/community/enrollments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,activity_id:activityId})}),d=await r.json();if(!r.ok)throw new Error(d.error);form?.reset();setMessage(body.action==='register'?(d.status==='confirmada'?'Inscrição confirmada.':'Inscrição na fila de espera.'):body.action==='delete'?'Inscrição e dados pessoais excluídos.':'Inscrição cancelada e autorização retirada.');if(d.promoted_id)setMessage(m=>m+' A primeira pessoa da fila foi confirmada; nenhum aviso foi enviado.');setReload(n=>n+1);}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar.');}finally{setSaving(false);}}
 return <main className="community-workspace"><header><small>IBFC · Atendimento comunitário</small><h1>Inscrições e fila de espera</h1><p>Gestão administrativa das inscrições autorizadas. Confirmação de vaga não significa presença realizada; nenhuma mensagem é enviada por este módulo.</p><Link href="/admin/comunidade/atividades">← Atividades comunitárias</Link></header>{error&&<p role="alert" className="community-error">{error}</p>}{message&&<p role="status" className="community-success">{message}</p>}
 <section><h2>Selecionar atividade</h2><label>Atividade para inscrição<select aria-label="Atividade para inscrição" value={activityId} disabled={saving} onChange={e=>{setActivityId(e.target.value);setMessage('');}}><option value="">Selecione</option>{activities.map(a=><option key={a.id} value={a.id}>{a.title} · {a.organization_name} · {a.start_on}</option>)}</select></label>{activityLimit&&<p>Lista de até 500 atividades; atividades mais antigas podem ficar fora da seleção.</p>}{selected&&<><p>{selected.start_on} a {selected.end_on} · {selected.venue} · {ACTIVITY_STATUS[selected.status]}</p><p>Vagas: {selected.capacity??'Sem limite definido'}{data?` · ${data.confirmed} confirmadas · ${data.waiting} em espera`:''}</p>{closed&&<p>Inscrições encerradas. Cancelamento e exclusão dos registros continuam disponíveis.</p>}</>}</section>
 {selected&&<section><h2>Nova inscrição autorizada</h2><form onSubmit={e=>{e.preventDefault();const f=e.currentTarget,b=Object.fromEntries(new FormData(f));void save({...b,action:'register',authorized:b.authorized==='on'},f);}}><div className="enrollment-row"><label>Nome do inscrito<input name="name" required minLength={2} maxLength={160}/></label><label>E-mail do inscrito<input name="email" type="email" required maxLength={254}/></label></div><label>Referência da autorização<textarea name="consent_evidence" required minLength={5} maxLength={500} placeholder="Referência do termo autorizado; não inclua documentos pessoais."/></label><label className="community-check"><input name="authorized" type="checkbox" required/>Confirmo que a pessoa autorizou o cadastro para esta atividade.</label><button disabled={saving||loading||closed}>{saving?'Salvando…':'Cadastrar inscrição'}</button></form><p>O mesmo e-mail não pode ter duas inscrições ativas nesta atividade. E-mail compartilhado por pessoas diferentes exige revisão da equipe; não é comprovação de identidade.</p></section>}
 {loading&&<p role="status">Consultando inscrições…</p>}{data&&<section><h2>Inscrições cadastradas</h2><div className="enrollment-metrics">{[['Confirmadas',data.confirmed],['Fila de espera',data.waiting],['Canceladas',data.cancelled]].map(([name,n])=><div key={name}><small>{name}</small><strong>{n}</strong></div>)}</div><p>{data.rows.length} registros exibidos de {data.total}. A ordem da fila segue o cadastro; ao liberar uma vaga a primeira pessoa é promovida automaticamente.</p>{data.truncated&&<p role="alert" className="community-error">Lista parcial: até 500 inscrições em ordem de cadastro. As contagens e promoções usam toda a base da atividade.</p>}<button disabled={saving||loading} onClick={()=>setReload(n=>n+1)}>Atualizar inscrições</button><div className="community-table"><table><thead><tr><th>Nome / e-mail</th><th>Situação</th><th>Posição na fila</th><th>Ações</th></tr></thead><tbody>{data.rows.map(e=><tr key={e.id}><td>{e.name}<br/>{e.email}</td><td>{ENROLLMENT_STATUS[e.status]}</td><td>{e.queue_position??'—'}</td><td>{e.status!=='cancelada'&&<button disabled={saving||loading} onClick={()=>{if(window.confirm('Cancelar inscrição e retirar autorização? Uma vaga liberada poderá confirmar a primeira pessoa da fila.'))void save({action:'cancel',id:e.id});}}>Cancelar inscrição</button>}<button className="enrollment-delete" disabled={saving||loading} onClick={()=>{if(window.confirm('Excluir os dados pessoais desta inscrição? Uma vaga liberada poderá confirmar a primeira pessoa da fila.'))void save({action:'delete',id:e.id});}}>Excluir dados</button></td></tr>)}</tbody></table></div>{!data.rows.length&&<p>Nenhuma inscrição nesta atividade.</p>}</section>}
 </main>;
}
