import {NextRequest,NextResponse} from 'next/server';
import {electoralStaff} from '@/lib/electoral/auth';
import {DEMAND_STATUS,DEMAND_CATEGORY,validateDemand} from '@/lib/community/demands';
export const dynamic='force-dynamic';
const reply=(body:unknown,status=200)=>NextResponse.json(body,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(r:NextRequest){const {db,allowed}=await electoralStaff();if(!allowed)return reply({error:'Acesso administrativo necessário.'},403);
 const id=r.nextUrl.searchParams.get('id');if(id){if(!/^[0-9a-f-]{36}$/i.test(id))return reply({error:'Identificador inválido.'},400);const {data,error}=await db.from('ibfc_community_demand_events').select('id,old_status,new_status,note,created_at').eq('demand_id',id).order('created_at');return error?reply({error:'Não foi possível consultar o histórico.'},503):reply({events:data});}
 const status=r.nextUrl.searchParams.get('status')??'',category=r.nextUrl.searchParams.get('category')??'',page=Number(r.nextUrl.searchParams.get('page')??'0');if(!Number.isSafeInteger(page)||page<0||page>100000||(status&&!Object.hasOwn(DEMAND_STATUS,status))||(category&&!Object.hasOwn(DEMAND_CATEGORY,category)))return reply({error:'Filtros inválidos.'},400);
 let q=db.from('ibfc_community_demands').select('id,organization_id,title,description,category,priority,responsible,due_on,status,resolution,version,created_at,updated_at',{count:'exact'}).order('created_at',{ascending:false}).order('id').range(page*50,page*50+49);if(status)q=q.eq('status',status);if(category)q=q.eq('category',category);
 const [list,summary]=await Promise.all([q,db.rpc('ibfc_community_demand_summary')]);if(list.error||summary.error)return reply({error:'Instale a migração 20261020_ibfc_community_demands.sql para habilitar demandas.'},503);return reply({rows:list.data,total:list.count,summary:summary.data,page,pageSize:50});}
export async function POST(r:NextRequest){const {db,allowed}=await electoralStaff();if(!allowed)return reply({error:'Acesso administrativo necessário.'},403);if(r.headers.get('origin')!==r.nextUrl.origin)return reply({error:'Origem inválida.'},403);let b;try{b=await r.json();}catch{return reply({error:'Pedido inválido.'},400);}if(!b||typeof b!=='object'||Array.isArray(b))return reply({error:'Pedido inválido.'},400);const problem=validateDemand(b);if(problem)return reply({error:problem},400);const {data,error}=await db.rpc('ibfc_community_demand_save',{p_data:b});if(error)return reply({error:error.message.includes('outra pessoa')?'Registro alterado por outra pessoa. Atualize a lista antes de salvar novamente.':'Não foi possível salvar. Confira a migração, organização e permissões.'},error.message.includes('outra pessoa')?409:400);return reply({ok:true,id:data});}
