import type {LegislativeRecord,LegislativeRun,Provider} from './types';
type Obj=Record<string,any>;
const obj=(x:unknown):Obj=>{if(!x||typeof x!=='object'||Array.isArray(x))throw Error('Formato oficial incompatível.');return x as Obj;};
const array=(x:unknown):Obj[]=>{if(!Array.isArray(x))throw Error('Lista oficial incompatível.');return x.map(obj);};
const singleton=(x:unknown):Obj[]=>x==null?[]:Array.isArray(x)?x.map(obj):[obj(x)];
const text=(x:unknown,max=2000)=>x==null?null:String(x).slice(0,max);
const day=(x:unknown)=>typeof x==='string'&&/^\d{4}-\d{2}-\d{2}/.test(x)?x.slice(0,10):null;
const inRange=(d:string|null,r:LegislativeRun)=>d!==null&&d>=r.start_on&&d<=r.end_on;
const base={camara:'https://dadosabertos.camara.leg.br/api/v2',senado:'https://legis.senado.leg.br/dadosabertos'};
export async function readOfficial(url:string,request:typeof fetch=fetch){const u=new URL(url);if(u.protocol!=='https:'||!['dadosabertos.camara.leg.br','legis.senado.leg.br'].includes(u.hostname))throw Error('Fonte não autorizada.');const response=await request(url,{headers:{Accept:'application/json'},cache:'no-store',redirect:'error',signal:AbortSignal.timeout(10000)});if(!response.ok)throw Error(`Fonte oficial respondeu HTTP ${response.status}.`);const length=Number(response.headers.get('content-length'));if(length>8000000)throw Error('Resposta excede 8 MB. Reduza o intervalo.');if(!response.body)throw Error('Resposta sem conteúdo.');const reader=response.body.getReader();const chunks:Uint8Array[]=[];let bytes=0;for(;;){const {done,value}=await reader.read();if(done)break;bytes+=value.length;if(bytes>8000000){await reader.cancel();throw Error('Resposta excede 8 MB. Reduza o intervalo.');}chunks.push(value);}const all=new Uint8Array(bytes);let offset=0;for(const c of chunks){all.set(c,offset);offset+=c.length;}return JSON.parse(new TextDecoder().decode(all));}
export async function officialIdentity(provider:Provider,id:string,request:typeof fetch=fetch){const url=provider==='camara'?`${base.camara}/deputados/${id}`:`${base.senado}/senador/${id}.json`,p=await readOfficial(url,request);const raw=provider==='camara'?obj(obj(p).dados):obj(obj(obj(obj(p).DetalheParlamentar).Parlamentar).IdentificacaoParlamentar);const found=provider==='camara'?raw.id:raw.CodigoParlamentar;if(String(found)!==id)throw Error('Identificador retornado não corresponde ao solicitado.');return {name:text(provider==='camara'?raw.ultimoStatus?.nome??raw.nomeCivil:raw.NomeParlamentar,250)??'Nome não informado',url};}
export async function collectPage(r:LegislativeRun,request:typeof fetch=fetch):Promise<{records:LegislativeRecord[];hasMore:boolean;source:string}>{
 const id=r.external_id;let source:string;
 const make=(key:string,title:unknown,summary:unknown,date:unknown,payload:Obj,vote:unknown=null):LegislativeRecord=>({external_key:key,title:text(title,500)??'Registro oficial',summary:text(summary),occurred_on:day(date),source_url:source,payload,vote_value:text(vote,100)});
 if(r.provider==='camara'){
  const path=r.category==='committees'?`/deputados/${id}/orgaos`:r.category==='propositions'?'/proposicoes':r.category==='votes'?'/votacoes':`/deputados/${id}/eventos`;
  const q=new URLSearchParams({pagina:String(r.page),itens:r.category==='committees'?'20':r.category==='propositions'?'5':'3',ordem:'ASC'});
  if(r.category!=='committees'){q.set('dataInicio',r.start_on);q.set('dataFim',r.end_on);}if(r.category==='propositions'){q.delete('dataInicio');q.delete('dataFim');q.set('dataApresentacaoInicio',r.start_on);q.set('dataApresentacaoFim',r.end_on);q.set('idDeputadoAutor',id);q.set('ordenarPor','id');}else if(r.category==='votes')q.set('ordenarPor','dataHoraRegistro');else if(r.category==='events')q.set('ordenarPor','dataHoraInicio');
  source=base.camara+path+'?'+q;const p=obj(await readOfficial(source,request)),items=array(p.dados);
  if(!Array.isArray(p.links))throw Error('Metadados de paginação ausentes; não é possível confirmar a cobertura.');
  const hasMore=p.links.some((x:Obj)=>x.rel==='next');
  const records=await Promise.all(items.map(async x=>{
   const recordId=r.category==='committees'?x.idOrgao??x.id:x.id;if(recordId==null)throw Error('Registro oficial sem identificador.');
   if(r.category==='committees')return make(`${id}:org:${recordId}:${x.dataInicio??''}`,x.nomeOrgao??x.nome??x.siglaOrgao??x.sigla,x.titulo??x.nomePapel,x.dataInicio,x);
   if(r.category==='propositions'){const u=`${base.camara}/proposicoes/${x.id}`,detail=obj(obj(await readOfficial(u,request)).dados);return {...make(`${id}:prop:${x.id}`,`${x.siglaTipo} ${x.numero}/${x.ano}`,detail.ementa,detail.dataApresentacao,{...detail,collection_author_id:id}),source_url:u};}
   if(r.category==='votes'){const u=`${base.camara}/votacoes/${encodeURIComponent(x.id)}/votos`,votes=array(obj(await readOfficial(u,request)).dados);const found=votes.find(v=>String(v.deputado_?.id??v.deputado?.id??v.idDeputado)===id);return {...make(`${id}:vote:${x.id}`,x.descricao,found?`Voto publicado: ${found.tipoVoto}`:'Sem voto nominal publicado para este parlamentar nesta consulta.',x.data,{ballot:x,member_vote:found??null},found?.tipoVoto),source_url:u};}
   const u=`${base.camara}/eventos/${x.id}/deputados`,people=array(obj(await readOfficial(u,request)).dados),found=people.find(v=>String(v.id)===id),ended=x.dataHoraFim&&Date.parse(x.dataHoraFim)<Date.now();return {...make(`${id}:event:${x.id}`,x.descricao??x.descricaoTipo,found?(ended?'Consta na relação de participantes do evento encerrado.':'Participação prevista/publicada; não comprova presença realizada.'):'Não consta na relação consultada; não classificado como ausência.',x.dataHoraInicio,{event:x,member:found??null}),source_url:u};
  }));return {records,hasMore,source};
 }
 if(r.category==='votes'||r.category==='propositions'){
  const start=new Date(r.start_on+'T12:00:00Z');start.setUTCDate(start.getUTCDate()+(r.page-1)*7);const from=start.toISOString().slice(0,10);if(from>r.end_on)throw Error('Lote fora do intervalo.');start.setUTCDate(start.getUTCDate()+6);const to=start.toISOString().slice(0,10)<r.end_on?start.toISOString().slice(0,10):r.end_on;
  source=r.category==='votes'?`${base.senado}/votacao?`+new URLSearchParams({codigoParlamentar:id,dataInicio:from,dataFim:to}):`${base.senado}/processo?`+new URLSearchParams({codigoParlamentarAutor:id,dataInicioApresentacao:from,dataFimApresentacao:to});const items=array(await readOfficial(source,request));
  if(r.category==='propositions'){const records=items.map(x=>{if(x.id==null||!inRange(day(x.dataApresentacao),r))throw Error('Processo sem identificador ou fora do intervalo.');return make(`${id}:prop:${x.id}`,x.identificacao,`${x.ementa??''} · Situação: ${x.situacaoAtual??'não informada'}`,x.dataApresentacao,x);});return {records,hasMore:to<r.end_on,source};}
  const records=items.filter(x=>{if(!['S','N'].includes(String(x.votacaoSecreta).toUpperCase()))throw Error('Sigilo da votação não informado.');return String(x.votacaoSecreta).toUpperCase()==='N';}).flatMap(x=>{if(x.codigoSessaoVotacao==null)throw Error('Votação sem identificador de sessão de votação.');if(!inRange(day(x.dataSessao),r))throw Error('Fonte retornou votação fora do período solicitado.');const found=array(x.votos??[]).find(v=>String(v.codigoParlamentar)===id);if(!found)return [];return [make(`${id}:vote:${x.codigoSessaoVotacao}:${x.sequencialVotacao??''}`,x.identificacao??x.descricaoVotacao,`${x.descricaoVotacao??''} · Voto publicado: ${found.siglaVotoParlamentar??'não informado'}`,x.dataSessao,{ballot:Object.fromEntries(Object.entries(x).filter(([key])=>key!=='votos')),member_vote:found},found.siglaVotoParlamentar)];});return {records,hasMore:to<r.end_on,source};
 }
 source=`${base.senado}/senador/${id}/${r.category==='committees'?'comissoes':'autorias'}.json`;const p=obj(await readOfficial(source,request));
 const root=obj(p[r.category==='committees'?'MembroComissaoParlamentar':'MateriasAutoriaParlamentar']);
 if(root.Metadados?.Descontinuacao?.DataDesativacaoCompleta)throw Error('Fonte indica desativação. Revisar o serviço substituto; esta coleta não será marcada como concluída.');
 const par=obj(root.Parlamentar);if(String(par.Codigo)!==id)throw Error('Fonte retornou outro parlamentar.');
 const items=r.category==='committees'?singleton(par.MembroComissoes?.Comissao):singleton(par.Autorias?.Autoria);
 const records=items.flatMap(x=>{if(r.category==='committees'){const c=obj(x.IdentificacaoComissao);if(c.CodigoComissao==null)throw Error('Comissão sem identificador.');return [make(`${id}:org:${c.CodigoComissao}:${x.DataInicio??''}`,`${c.SiglaComissao??''} · ${c.NomeComissao??''}`,`${x.DescricaoParticipacao??''} · término: ${x.DataFim??'não informado'}`,x.DataInicio,x)];}const m=obj(x.Materia);if(m.Codigo==null)throw Error('Matéria sem identificador.');if(!inRange(day(m.Data),r))return [];return [make(`${id}:prop:${m.Codigo}`,m.DescricaoIdentificacao??`${m.Sigla} ${m.Numero}/${m.Ano}`,m.Ementa,m.Data,x)];});
 if(records.length>2000)throw Error('Mais de 2.000 registros no lote. Reduza o intervalo ou revise o conector.');return {records,hasMore:false,source};
}
