const test=require('node:test'),assert=require('node:assert/strict');
const {reconcileBu,reconciliationCsv}=require('../lib/science/bu-reconciliation.ts');
const context={scope:'municipality',filters:{},selection:'Exemplo'};
const bu=(section,votes=10,base=100)=>({uf:'DF',municipality:97012,zone:1,local:1001,section,votes,nominal_legenda:base,metadata:{urna:123,agregadas:'2'}});
function report(){return {denominator_basis:'bu_nominal_legenda',granularity:'section',rows:[{key:'DF:97012:1',name:'Zona 1',new_votes:20,new_valid:200,new_sections:2}],total_rows:1,truncated:false,totals:{new_votes:20,new_valid:200,new_sections:2},bu:{rows:[bu(1),bu(2)],total_rows:2,truncated:false},sources:[],analysis_id:'p1',result_sha256:'a'.repeat(64),generated_at:'2026-10-08'};}
test('complete aggregation reconciles exact zeros and nominal denominator without modifying report',()=>{const r=report();r.rows[0].new_votes=r.totals.new_votes=0;r.bu.rows.forEach(b=>b.votes=0);const original=JSON.stringify(r),q=reconcileBu(r,context);assert.equal(q.counts.equal,1);assert.equal(q.totals.comparable,true);assert.equal(q.totals.delta_votes,0);assert.equal(JSON.stringify(r),original);});
test('difference uses BU minus analysis and checks votes and denominator independently',()=>{const r=report();r.bu.rows[0].votes=12;r.bu.rows[1].nominal_legenda=101;const q=reconcileBu(r,context);assert.equal(q.lines[0].status,'different');assert.equal(q.lines[0].delta_votes,2);assert.equal(q.lines[0].delta_valid,1);assert.equal(q.totals.delta_votes,2);});
test('partial BU suppresses delta until section counts match; no fake zero',()=>{const r=report();r.bu.rows.pop();r.bu.truncated=true;const q=reconcileBu(r,context);assert.equal(q.lines[0].status,'partial');assert.equal(q.lines[0].bu_votes,10);assert.equal(q.lines[0].delta_votes,null);assert.equal(q.totals.comparable,false);assert.equal(q.totals.bu_votes,null);});
test('global truncated flag blocks total but fully represented loaded group remains comparable',()=>{const r=report();r.bu.truncated=true;r.bu.total_rows=6000;const q=reconcileBu(r,context);assert.equal(q.counts.equal,1);assert.equal(q.totals.comparable,false);});
test('duplicate section identity including contradictory local blocks both groups; shared physical urna is allowed',()=>{const r=report();r.bu.rows[1]={...r.bu.rows[0],local:1002};const q=reconcileBu(r,context);assert.equal(q.lines[0].status,'duplicate');assert.equal(q.totals.comparable,false);assert.equal(reconcileBu(report(),context).counts.equal,1);});
test('duplicate aggregate keys, invalid count and integer overflow do not produce comparison',()=>{const r=report();r.rows.push({...r.rows[0]});assert.equal(reconcileBu(r,context).counts.duplicate,2);const s=report();s.bu.rows[0].votes=-1;assert.equal(reconcileBu(s,context).counts.invalid,1);s.bu.rows.forEach(b=>{b.votes=Number.MAX_SAFE_INTEGER;b.nominal_legenda=Number.MAX_SAFE_INTEGER;});assert.equal(reconcileBu(s,context).counts.invalid,1);});
test('missing results and unmatched BU keys are separate from zero',()=>{const r=report();r.rows[0].new_votes=null;r.bu.rows.push({...bu(3),zone:2});const q=reconcileBu(r,context);assert.equal(q.counts.missing_result,1);assert.equal(q.counts.outside,1);assert.equal(q.totals.comparable,false);});
test('common-only and non-BU denominators never receive numerical differences',()=>{const r=report();assert.equal(reconcileBu(r,{...context,filters:{common_only:true}}).counts.incompatible,1);r.denominator_basis=undefined;const q=reconcileBu(r,context);assert.equal(q.lines[0].delta_votes,null);assert.equal(q.totals.comparable,false);});
test('all supported scopes group by SQL keys, not by physical urna or coordinates',()=>{for(const [scope,key,split] of [['country','DF',false],['state','DF:97012',false],['municipality','DF:97012:1',false],['zone','DF:97012:1:1001',false],['location','DF:97012:1:1001:1',true],['section','DF:97012:1:1001:1',true]]){const r=report();r.rows[0].key=key;if(split){r.rows[0].new_sections=1;r.rows[0].new_votes=10;r.rows[0].new_valid=100;r.rows.push({...r.rows[0],key:'DF:97012:1:1001:2'});r.total_rows=2;}assert.equal(reconcileBu(r,{...context,scope}).totals.comparable,true,scope);}});
test('metadata count mismatch and invalid territorial keys block totals',()=>{const r=report();r.bu.rows[0].section=0;const q=reconcileBu(r,context);assert.equal(q.coverage.invalid_bu_keys,1);assert.equal(q.totals.comparable,false);const s=report();s.bu.total_rows=3;assert.equal(reconcileBu(s,context).totals.comparable,false);});
test('CSV preserves protocols, all statuses and formula protection; unavailable differences remain blank',()=>{const r=report();r.rows[0].name='=HYPERLINK("x")';r.bu.rows.pop();const s=reconciliationCsv(reconcileBu(r,context));assert.match(s,/p1/);assert.match(s,/ibfc-bu-reconciliation-1.0/);assert.match(s,/'=HYPERLINK/);assert.match(s,/Cobertura incompleta/);assert.match(s,/;"";""\r?\n/);});

test('absence of BU is reported explicitly even on zone-only base',()=>{const r=report();delete r.bu;r.granularity='zone';delete r.denominator_basis;const q=reconcileBu(r,context);assert.equal(q.counts.missing_bu,1);assert.equal(q.totals.delta_votes,null);});
