const test=require('node:test'),assert=require('node:assert/strict');const {cldfRequest,queryCldf}=require('../lib/legislative/cldf.ts');
const json=data=>new Response(JSON.stringify(data),{headers:{'Content-Type':'application/json'}});
test('only documented fixed official endpoints and fields reach the source',()=>{assert.equal(cldfRequest({action:'catalogue'}).url,'https://ple.cl.df.gov.br/pleservico/api/public/autor/listar');const r=cldfRequest({action:'search',author:' Nome ',year:'2026',page:2,url:'https://evil.example'});assert.equal(r.method,'POST');assert.deepEqual(r.body,{ementa:true,autoria:'Nome',ano:'2026'});assert.match(r.url,/page=2&size=20/);assert.equal(cldfRequest({action:'tramitation',project_id:'123'}).url,'https://ple.cl.df.gov.br/pleservico/api/public/proposicao/123/tramitacoes');});
test('invalid ranges, date, id, page and unbounded search refused before network',()=>{for(const q of [{action:'search'},{action:'search',year:'2026',page:-1},{action:'search',year:'2026',page:1.2},{action:'search',year:'2026',start_on:'2026-02-30',end_on:'2026-03-01'},{action:'search',year:'2026',start_on:'2026-01-01'},{action:'search',start_on:'2025-01-01',end_on:'2026-01-02'},{action:'project',project_id:'../foo'},{action:'evil',project_id:'123'}])assert.throws(()=>cldfRequest(q));});
test('success retains original JSON and marks schema and candidate identity unvalidated',async()=>{let sent;const raw={content:[{id:123,ementa:'Teste'}],totalPages:3};const r=await queryCldf({action:'search',year:'2026'},async(url,init)=>{sent={url,init};return json(raw);});assert.deepEqual(r.raw,raw);assert.equal(r.schema_validated,false);assert.equal(r.candidate_binding_validated,false);assert.equal(sent.init.redirect,'error');assert.equal(sent.init.method,'POST');assert.equal(JSON.parse(sent.init.body).ano,'2026');assert.ok(r.bytes>0);});
test('upstream errors, HTML, bad JSON and oversize are failures rather than empty success',async()=>{await assert.rejects(()=>queryCldf({action:'catalogue'},async()=>new Response('',{status:502})),e=>e.upstreamStatus===502);await assert.rejects(()=>queryCldf({action:'catalogue'},async()=>new Response('<html/>',{headers:{'Content-Type':'text/html'}})),/JSON/);await assert.rejects(()=>queryCldf({action:'catalogue'},async()=>new Response('{',{headers:{'Content-Type':'application/json'}})),/inválido/);await assert.rejects(()=>queryCldf({action:'catalogue'},async()=>new Response('{}',{headers:{'Content-Type':'application/json','content-length':'4000001'}})),/4 MB/);await assert.rejects(()=>queryCldf({action:'catalogue'},async()=>{throw Error('private details')}),e=>!e.message.includes('private'));});
test('admin endpoint enforces authentication, origin and request validation before official query',async()=>{
 const fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),cldf=require('../lib/legislative/cldf.ts');
 const code=ts.transpileModule(fs.readFileSync(require.resolve('../app/api/admin/science/cldf/route.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
 let allowed=false,calls=0;const endpoint={};vm.runInNewContext(code,{exports:endpoint,Date,require:id=>id==='next/server'?require('next/server'):id==='node:crypto'?require(id):id.includes('electoral/auth')?{electoralStaff:async()=>({allowed})}:id.includes('legislative/cldf')?{...cldf,queryCldf:async()=>{calls++;return {raw:{authors:[]}}}}:{canonicalJson:JSON.stringify}});
 const request=(origin,body)=>({headers:new Headers({origin}),nextUrl:new URL('https://portal.example/api'),text:async()=>JSON.stringify(body)});
 assert.equal((await endpoint.POST(request('https://portal.example',{action:'catalogue'}))).status,403);allowed=true;
 assert.equal((await endpoint.POST(request('https://evil.example',{action:'catalogue'}))).status,403);
 assert.equal((await endpoint.POST(request('https://portal.example',{action:'search'}))).status,400);assert.equal(calls,0);
 const r=await endpoint.POST(request('https://portal.example',{action:'catalogue'}));assert.equal(r.status,200);assert.equal(r.headers.get('Cache-Control'),'private, no-store');assert.match((await r.json()).source_hash,/^[a-f0-9]{64}$/);assert.equal(calls,1);
});
