const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript'),vm=require('node:vm');
const uuid='00000000-0000-0000-0000-000000000001';
const body={request_id:uuid,candidate_id:uuid,title:'Proposta pública',description:'Descrição',source_url:'https://example.org',status:'registered',review_note:'Registro com fonte pública.',deadline:'',evidence_url:''};
function endpoint(){let allowed=false,calls=[];const mod={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(require.resolve('../app/api/admin/science/commitments/route.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports:mod,URL,Date,Number,require:id=>id==='next/server'?require(id):{electoralStaff:async()=>({allowed,db:{rpc:async(name,args)=>{calls.push({name,args});return {data:{id:uuid},error:null}}}})}});return {mod,calls,allow:()=>allowed=true};}
const request=(b=body,origin='https://portal.example',q='')=>({nextUrl:new URL('https://portal.example/api?'+q),headers:new Headers({origin}),text:async()=>JSON.stringify(b)});
test('auth and same origin required before save',async()=>{const e=endpoint();assert.equal((await e.mod.POST(request())).status,403);e.allow();assert.equal((await e.mod.POST(request(body,'https://evil.example'))).status,403);assert.equal(e.calls.length,0);});
test('reject invalid UUID, unsafe URLs, impossible date, missing evidence, short justification and oversize body',async()=>{const e=endpoint();e.allow();for(const b of [{...body,candidate_id:'bad'},{...body,source_url:'javascript:alert(1)'},{...body,source_url:'https://user:pass@example.org'},{...body,deadline:'2026-02-30'},{...body,status:'fulfilled'},{...body,review_note:'curta'},null])assert.equal((await e.mod.POST(request(b))).status,400);assert.equal((await e.mod.POST(request({...body,description:'x'.repeat(16000)}))).status,413);assert.equal(e.calls.length,0);});
test('valid save uses server RPC, no caller selected actor',async()=>{const e=endpoint();e.allow();const r=await e.mod.POST(request({...body,actor_id:'attacker'}));assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'private, no-store');assert.equal(e.calls[0].name,'ibfc_commitment_save');assert.equal(Object.hasOwn(e.calls[0].args,'actor_id'),false);});
test('GET rejects invalid pagination and filters before querying',async()=>{const e=endpoint();assert.equal((await e.mod.GET(request())).status,403);e.allow();for(const q of ['id=bad','candidate_id=bad','offset=-1','offset=0.5','status=wrong'])assert.equal((await e.mod.GET(request(body,undefined,q))).status,400);});
