const test=require('node:test'),assert=require('node:assert/strict');
const {pairMapData,geographicPositions,historicalGeographicCoverage}=require('../lib/science/comparison-maps.ts');
const row=(key,votes,valid=100,lat=-15.7,lon=-47.9)=>({key,name:key,new_votes:votes,new_valid:valid,latitude:lat,longitude:lon,sections:[],address:null});
const col=(name,rows)=>({target:{name},report:{rows,granularity:'zone'}});
test('shared square-root area scale, confirmed zero distinct from unavailable',()=>{const c=[col('A',[row('1',100),row('2',0),row('3',null)]),col('B',[row('1',25)])];const d=pairMapData(c,0,1,'votes');assert.equal(d.max,100);assert.equal(d.maps[0][0].marker_radius,30);assert.equal(d.maps[1][0].marker_radius,18);assert.equal(d.maps[0][1].marker_radius,6);assert.equal(d.maps[0][2].marker_color,'#64748b');assert.equal(d.maps[0][1].sections[0].new_votes,0);assert.equal(d.maps[0][2].sections[0].new_votes,null);});
test('percentages use their own valid denominators and missing or zero denominator does not become zero',()=>{const d=pairMapData([col('A',[row('1',20,100)]),col('B',[row('1',20,200),row('2',20,0)])],0,1,'share');assert.equal(d.max,20);assert.equal(d.maps[1][1].marker_color,'#64748b');assert.ok(d.maps[1][0].marker_caption.includes('10%'));});
test('coordinate union excludes invalid points, preserves real source positions and removes only exact duplicate coordinates',()=>{const c=[col('A',[row('1',1),row('2',1,100,null,null),row('3',1,100,91,0)]),col('B',[row('1',2,100,-16,-48),row('4',2)])];assert.deepEqual(geographicPositions(c),[[-15.7,-47.9],[-16,-48]]);const d=pairMapData(c,0,1,'votes');assert.equal(d.maps[1][0].latitude,-16);assert.equal(d.maps[0][1].latitude,null);assert.equal(d.maps[0].length,3);});
test('pair selection rejects equal, out of bounds and noninteger indexes',()=>{const c=[col('A',[]),col('B',[])];for(const pair of [[0,0],[-1,1],[0,2],[0.5,1]])assert.throws(()=>pairMapData(c,...pair,'votes'));});

test('historical rendering hides future or undated geography, permits older references and leaves original archived reports untouched',()=>{const a=col('A',[{...row('1',10),coordinate_year:2026},{...row('2',0),coordinate_year:null},{...row('3',5,100,-15.8,-48),coordinate_year:2020},{...row('4',4,100,-15.9,-48.1),coordinate_year:2022}]);a.target.year=2022;const b=col('B',[{...row('1',20),coordinate_year:2026}]);b.target.year=2026;const d=pairMapData([a,b],0,1,'votes',true);assert.equal(d.maps[0][0].latitude,null);assert.equal(d.maps[0][1].latitude,null);assert.equal(d.maps[0][2].latitude,-15.8);assert.equal(d.positions.length,3);assert.equal(a.report.rows[0].latitude,-15.7);assert.equal(a.report.rows[0].coordinate_year,2026);assert.deepEqual(historicalGeographicCoverage(a),{rows:4,valid_coordinates:4,missing_coordinates:0,excluded_future:1,excluded_unknown_year:1,reference_prior_year:1,plotted_rows:2});});
