const test=require('node:test'),assert=require('node:assert/strict');
const {readOfficial,officialIdentity,collectPage}=require('../lib/legislative/collector.ts');const {validInput}=require('../lib/legislative/types.ts');
const base={provider:'camara',external_id:'123',category:'committees',start_on:'2026-01-01',end_on:'2026-01-14',page:1};
const response=b=>new Response(JSON.stringify(b),{headers:{'Content-Type':'application/json'}});
test('strict dates, interval, institution and category',()=>{assert.equal(validInput(base),null);assert.ok(validInput({...base,start_on:'2026-02-30'}));assert.ok(validInput({...base,provider:'senado',category:'events'}));assert.ok(validInput({...base,end_on:'2027-02-01'}));});
test('fixed official hosts, HTTP errors and oversized responses',async()=>{await assert.rejects(()=>readOfficial('https://evil.example/test'),/autorizada/);await assert.rejects(()=>readOfficial('https://legis.senado.leg.br/dadosabertos/test',async()=>new Response('',{status:404})),/404/);await assert.rejects(()=>readOfficial('https://legis.senado.leg.br/dadosabertos/test',async()=>new Response('',{headers:{'content-length':'9000000'}})),/8 MB/);});
test('official identity refuses mismatched IDs',async()=>{const p=async()=>response({dados:{id:123,ultimoStatus:{nome:'Parlamentar teste'}}});assert.equal((await officialIdentity('camara','123',p)).name,'Parlamentar teste');await assert.rejects(()=>officialIdentity('camara','124',p),/corresponde/);});
test('Camara committees preserve continuation and explicit source',async()=>{const r=await collectPage(base,async()=>response({dados:[{id:8,nome:'Comissão teste',dataInicio:'2025-02-01'}],links:[{rel:'next',href:'https://evil.example'}]}));assert.equal(r.hasMore,true);assert.equal(r.records.length,1);assert.ok(r.source.includes('pagina=1'));await assert.rejects(()=>collectPage(base,async()=>response({dados:[]})),/paginação/);});
test('Camara page fails atomically when a vote detail fails',async()=>{await assert.rejects(()=>collectPage({...base,category:'votes'},async url=>url.includes('/votos')?new Response('',{status:503}):response({dados:[{id:'99-1',data:'2026-01-02'}],links:[]})),/503/);});
test('Camara missing nominal vote never becomes absence',async()=>{const r=await collectPage({...base,category:'votes'},async url=>url.includes('/votos')?response({dados:[{deputado_:{id:999},tipoVoto:'Sim'}]}):response({dados:[{id:'99-1',data:'2026-01-02'}],links:[]}));assert.equal(r.records[0].vote_value,null);assert.match(r.records[0].summary,/Sem voto nominal/);});
test('current Senate endpoint uses date windows and stable ballot identity; secret votes excluded',async()=>{let source;const ballot={codigoSessaoVotacao:33,sequencialVotacao:4,votacaoSecreta:'N',dataSessao:'2026-01-02',identificacao:'PL teste',votos:[{codigoParlamentar:123,siglaVotoParlamentar:'Sim'}]};const r=await collectPage({...base,provider:'senado',category:'votes'},async url=>{source=url;return response([ballot,{...ballot,codigoSessaoVotacao:34,votacaoSecreta:'S'}]);});assert.ok(source.includes('/votacao?'));assert.ok(source.includes('dataFim=2026-01-07'));assert.equal(r.hasMore,true);assert.equal(r.records.length,1);assert.equal(r.records[0].external_key,'123:vote:33:4');assert.equal(r.records[0].vote_value,'Sim');assert.equal(r.records[0].payload.ballot.votos,undefined);});
test('Senate modern propositions use parliamentary author and presentation dates',async()=>{let source;const r=await collectPage({...base,provider:'senado',category:'propositions',page:2},async url=>{source=url;return response([{id:42,dataApresentacao:'2026-01-10',identificacao:'PL 1/2026',ementa:'Teste',situacaoAtual:'Em análise'}]);});assert.ok(source.includes('codigoParlamentarAutor=123'));assert.ok(source.includes('dataInicioApresentacao=2026-01-08'));assert.equal(r.hasMore,false);assert.equal(r.records[0].external_key,'123:prop:42');});
test('Senate empty weekly response is valid; wrong shape and retired source are failures',async()=>{assert.equal((await collectPage({...base,provider:'senado',category:'votes'},async()=>response([]))).records.length,0);await assert.rejects(()=>collectPage({...base,provider:'senado',category:'votes'},async()=>response({VotacaoParlamentar:{}})),/Lista/);await assert.rejects(()=>collectPage({...base,provider:'senado'},async()=>response({MembroComissaoParlamentar:{Metadados:{Descontinuacao:{DataDesativacaoCompleta:'2026-01-01'}},Parlamentar:{}}})),/desativação/);});

test('legacy Senate client cannot report success for retired HTTP 200 service',async()=>{const {obterVotacoesSenador}=require('../lib/integrations/senado/client.ts');const previous=global.fetch;global.fetch=async()=>response({VotacaoParlamentar:{Metadados:{Descontinuacao:{DataDesativacaoCompleta:'2020-01-01'}},Parlamentar:{Codigo:'123'}}});try{await assert.rejects(()=>obterVotacoesSenador('123'),/desativado/);}finally{global.fetch=previous;}});
