const test=require('node:test'),assert=require('node:assert/strict');
const {assertComparableTargets,comparisonLines,comparisonTotals,comparisonCsv}=require('../lib/science/multi-comparison.ts');
const target=n=>({uf:'DF',year:2026,election:6257,turn:1,office:1,kind:'candidate',number:String(n),name:'Candidato '+n});
const row=(key,votes,valid)=>({key,name:'Zona '+key,uf:'DF',municipality:1,zone:Number(key),local:null,section:0,new_votes:votes,new_valid:valid});
const column=(n,rows,extra={})=>({target:target(n),report:{rows,totals:{new_votes:100+n,new_valid:1000},sources:[{year:2026,filename:'TSE.csv',source_url:'https://example.test',finished_at:'2026-10-08'}],total_rows:rows.length,truncated:false,generated_at:'2026-10-08',analysis_id:'id-'+n,result_sha256:'hash-'+n,...extra}});
test('bounds, repeated selections and mixed recortes rejected',()=>{assert.throws(()=>assertComparableTargets([target(1)]));assert.throws(()=>assertComparableTargets(Array.from({length:11},(_,i)=>target(i))));assert.throws(()=>assertComparableTargets([target(1),target(1)]));for(const change of [{year:2022},{election:99},{office:5},{turn:2},{uf:'GO'},{kind:'party'},{kind:'group'}])assert.throws(()=>assertComparableTargets([target(1),{...target(2),...change}]));assert.doesNotThrow(()=>assertComparableTargets(Array.from({length:10},(_,i)=>target(i))));});
test('missing is preserved, confirmed zero comparable and mismatched denominators blocked',()=>{const a=column(1,[row('1',0,100),row('2',10,200),row('3',7,200)]),b=column(2,[row('1',30,100),row('2',20,250)]);const lines=comparisonLines([a,b]);assert.equal(lines[0].cells[0].votes,0);assert.equal(lines[0].cells[0].share,0);assert.equal(lines[0].comparable,true);assert.equal(lines[1].comparable,false);assert.equal(lines[2].cells[1].votes,null);assert.equal(lines[2].comparable,false);});
test('mixed denominator basis and duplicate row keys rejected or marked',()=>{assert.equal(comparisonLines([column(1,[row('1',1,100)]),column(2,[row('1',2,100)],{denominator_basis:'bu_nominal_legenda'})])[0].comparable,false);assert.throws(()=>comparisonLines([column(1,[row('1',1,100),row('1',2,100)]),column(2,[])]));});
test('totals retained independently of partial table; CSV preserves provenance and neutralizes formulas',()=>{const a=column(1,[{...row('1',1,100),name:'=FORMULA()'}],{truncated:true,total_rows:500}),b=column(2,[]);a.target.name='=BAD';const columns=[a,b];assert.equal(comparisonTotals(columns)[0].votes,101);const csv=comparisonCsv(columns,comparisonLines(columns),{year:2026});assert.ok(csv.startsWith('\ufeff'));assert.ok(csv.includes("'=FORMULA()"));assert.ok(csv.includes("'=BAD"));assert.ok(csv.includes('hash-1'));assert.ok(csv.includes('500'));assert.ok(csv.includes('"true"'));});
