const test=require('node:test'),assert=require('node:assert/strict');
const {comparisonPrintHtml,historicalPrintHtml}=require('../lib/science/print-report.ts');
const {historicalSnapshot,HISTORICAL_STATUS_LABELS}=require('../lib/science/historical-coverage.ts');
const {comparisonLines,comparisonTotals}=require('../lib/science/multi-comparison.ts');
const options={details:true,exportedAt:'08/10/2026',version:'teste'};
function column(name='A',votes=0){return {target:{name,year:2026,uf:'DF',election:1,office:1,turn:1,number:name,kind:'candidate'},report:{analysis_id:'protocolo-'+name,result_sha256:'a'.repeat(64),generated_at:'2026-10-08',granularity:'zone',sources:[{year:2026,filename:'tse.csv',source_url:'https://example.test/tse',finished_at:'2026-10-08'}],coverage:['Cobertura de teste'],total_rows:6000,truncated:true,rows:[{key:'DF:1',name:'Escola exemplo',uf:'DF',municipality:97012,zone:1,old_votes:10,new_votes:votes,old_valid:100,new_valid:100,old_sections:1,new_sections:1,common_sections:1,moved_sections:0}],totals:{old_votes:100,new_votes:votes===null?null:9000,new_valid:10000,old_valid:1000,old_sections:1,new_sections:1,common_sections:1,moved_sections:0}}};}
function html(cols,details=true){return comparisonPrintHtml(cols,comparisonLines(cols),comparisonTotals(cols),{scope:'state',uf:'DF'}, {...options,details});}
test('report preserves complete recorte totals, confirmed zero/missing and source provenance without summing partial rows',()=>{const s=html([column('A',0),column('B',null)]);assert.match(s,/9\.000/);assert.match(s,/0 votos/);assert.match(s,/Sem dados votos/);assert.match(s,/Carga limitada/);assert.match(s,/protocolo-A/);assert.match(s,/tse\.csv/);assert.match(s,/hashes referem-se aos relatórios originais/);assert.match(s,/Não comparáveis/);});
test('all loaded territorial rows included regardless of screen page; summary omits detailed table',()=>{const cols=[column(),column('B')];for(const c of cols)c.report.rows=Array.from({length:121},(_,i)=>({...c.report.rows[0],key:'DF:'+i,name:'Território '+i}));assert.match(html(cols),/Território 120/);assert.doesNotMatch(html(cols,false),/Território 120/);});
test('ten selections split into tables of at most three, preserving all column identities',()=>{const s=html(Array.from({length:10},(_,i)=>column('Candidato '+i,i)));assert.equal((s.match(/Detalhamento territorial · seleções/g)||[]).length,4);for(let i=0;i<10;i++)assert.match(s,new RegExp('Candidato '+i));});
test('untrusted names, sources and parameters cannot inject tags, scripts, links or external requests',()=>{const c=column('<script>alert(1)</script>');c.report.sources[0].source_url='javascript:alert(2)"><img src=x onerror=alert(3)>';const s=html([c,column('B')]);assert.doesNotMatch(s,/<script|<img|href=/);assert.match(s,/&lt;script&gt;/);assert.match(s,/default-src 'none'/);});
test('incomplete input fails rather than silently omitting selections',()=>{assert.throws(()=>comparisonPrintHtml([column()],[],[],{},options));assert.throws(()=>comparisonPrintHtml([column(),column('B')],[{cells:[]}],[{},{}],{},options));});
test('historical report reuses classifications and keeps zero baseline variation not calculable',()=>{const c=column();c.report.rows[0].old_votes=0;c.report.rows[0].new_votes=12;const old={...c.target,year:2022};const snapshot=historicalSnapshot(c.report,old,c.target,'state',{});const s=historicalPrintHtml(snapshot,c.report,HISTORICAL_STATUS_LABELS,options);assert.match(s,/Totais por zona nos dois anos/);assert.match(s,/Não calculável/);assert.match(s,/ibfc-historical-coverage-1.0/);assert.match(s,/Carga limitada/);assert.match(s,/0<\/td>/);});
