const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
const original=Module._resolveFilename;
Module._resolveFilename=function(id,parent,...rest){try{return original.call(this,id,parent,...rest);}catch(e){if(id.startsWith('.')&&parent?.filename.endsWith('.ts'))return original.call(this,id+'.ts',parent,...rest);throw e;}};
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,f);
const {workbookBytes,archiveSheets,archiveWorkbook}=require('../lib/science/report-workbook.ts');const {dossierHtml}=require('../lib/science/report-dossier.ts');
const fixture=(id='p1')=>({id,created_at:'2026-10-08',method_version:'original',result_sha256:'a'.repeat(64),integrity_verified:true,parameters:{new:{name:'<script>x</script>'}},result_snapshot:{generated_at:'2026-10-08',rows:[{key:'x',name:'=HYPERLINK("bad")',uf:'DF',zone:1,section:1,old_votes:null,new_votes:0,old_valid:null,new_valid:100}],total_rows:999,truncated:true,coverage:['Cobertura limitada'],sources:[{year:2026,filename:'tse.csv',source_url:'https://example.test',finished_at:'2026-10-08'}],totals:{old_votes:null,new_votes:9000,old_valid:null,new_valid:10000,old_sections:0,new_sections:1,common_sections:0,moved_sections:0}}});
function entries(bytes){const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),dec=new TextDecoder(),out={};let p=0;while(v.getUint32(p,true)===0x04034b50){const size=v.getUint32(p+18,true),n=v.getUint16(p+26,true),extra=v.getUint16(p+28,true),start=p+30+n+extra;out[dec.decode(bytes.slice(p+30,p+30+n))]=dec.decode(bytes.slice(start,start+size));p=start+size;}return out;}
test('workbook typed cells preserve confirmed zero, absent cells, formulas as text and all rows',()=>{const a=fixture(),before=JSON.stringify(a),sheets=archiveSheets([a]);assert.equal(sheets[1].rows[2][1],9000);const e=entries(archiveWorkbook([a]));assert.match(e['xl/worksheets/sheet2.xml'],/t="inlineStr"[^]*=HYPERLINK/);assert.doesNotMatch(e['xl/worksheets/sheet2.xml'],/<f>/);assert.match(e['xl/worksheets/sheet2.xml'],/<c r="H5"><v>0<\/v>/);assert.doesNotMatch(e['xl/worksheets/sheet2.xml'],/<c r="G5"/);assert.equal(JSON.stringify(a),before);});
test('workbook limits and XML escaping',()=>{assert.throws(()=>workbookBytes([{name:'bad/name',rows:[]} ]));assert.throws(()=>workbookBytes([{name:'a',rows:[]},{name:'A',rows:[]}]));assert.throws(()=>workbookBytes([{name:'a',rows:[['a'.repeat(32768)]]}]));assert.match(entries(workbookBytes([{name:'A & B',rows:[['<script>']]}]))['xl/workbook.xml'],/A &amp; B/);});
test('dossier retains separate totals and full details without mutation',()=>{const a=fixture(),b=fixture('p2');a.result_snapshot.rows=Array.from({length:121},(_,i)=>({...a.result_snapshot.rows[0],key:String(i),name:'Território '+i}));const before=JSON.stringify(a),h=dossierHtml([a,b],[],{details:true,version:'v',exportedAt:'now'});assert.match(h,/Território 120/);assert.match(h,/não são somados/);assert.match(h,/p1/);assert.match(h,/p2/);assert.doesNotMatch(h,/<script>/);assert.equal(JSON.stringify(a),before);assert.doesNotMatch(dossierHtml([a],[],{details:false,version:'v',exportedAt:'now'}),/Território 120/);});
test('dossier disallows duplicates, unverified records, foreign maps and active image URLs',()=>{const a=fixture();assert.throws(()=>dossierHtml([a,a],[],{}));assert.throws(()=>dossierHtml([{...a,integrity_verified:false}],[],{}));assert.throws(()=>dossierHtml([a],[{protocol:'other',dataUrl:'data:image/png;base64,iVBORw0KGgoAAA=',caption:'map'}],{}));assert.throws(()=>dossierHtml([a],[{protocol:'p1',dataUrl:'javascript:bad',caption:'map'}],{}));const h=dossierHtml([a],[{protocol:'p1',dataUrl:'data:image/png;base64,iVBORw0KGgoAAA=',caption:'<script>bad</script>'}],{details:false,version:'v',exportedAt:'now'});assert.match(h,/img-src data:/);assert.match(h,/&lt;script&gt;/);assert.doesNotMatch(h,/<script>/);});
test('xlsx ZIP structure independently verifies with Python standard library',()=>{const {execFileSync}=require('node:child_process'),os=require('node:os');const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ibfc-xlsx-')),f=path.join(dir,'check.xlsx');try{fs.writeFileSync(f,archiveWorkbook([fixture(),fixture('p2')]));execFileSync('python3',['-c',`import sys,zipfile,xml.etree.ElementTree as E\nwith zipfile.ZipFile(sys.argv[1]) as z:\n assert z.testzip() is None\n for p in z.namelist(): E.fromstring(z.read(p))\n assert len([p for p in z.namelist() if p.startswith('xl/worksheets/')])==3`,f]);}finally{fs.rmSync(dir,{recursive:true,force:true});}});
