const {test}=require('node:test'),assert=require('node:assert/strict');
const {temporalModels}=require('../lib/science/temporal-models.ts');
const years=[2014,2018,2022,2026];
const series=(values=[10,20,30,40],key='DF:1')=>years.map((year,i)=>({key,name:key,year,votes:values[i],valid:100}));
test('expanding chronology and persistence benchmark',()=>{const r=temporalModels(series(),years);assert.deepEqual(r.folds.map(f=>f.train_years),[[2014,2018],[2014,2018,2022]]);assert.equal(r.pooled.linear.mae,0);assert.equal(r.pooled.persistence.mae,10);assert.equal(r.projections[0].linear,50);assert.equal(r.projection_year,2030);});
test('a later observation cannot change an earlier held-out prediction',()=>{const a=temporalModels(series(),years),b=temporalModels(series([10,20,30,90]),years);assert.deepEqual(a.predictions.filter(p=>p.year===2022),b.predictions.filter(p=>p.year===2022));assert.deepEqual(a.predictions.at(-1).train_years,[2014,2018,2022]);assert.equal(a.predictions.at(-1).linear,b.predictions.at(-1).linear);});
test('missing years excluded, published zero votes retained',()=>{const missing=series([5,5,5,5],'DF:2').filter(p=>p.year!==2018),r=temporalModels([...series([0,0,0,0]),...missing],years);assert.equal(r.common_territories,1);assert.equal(r.excluded_territories,1);assert.deepEqual(r.excluded_keys,['DF:2']);assert.equal(r.projections[0].linear,0);assert.throws(()=>temporalModels(missing,years),/Nenhum território/);});
test('reject duplicates, invalid counts, insufficient and skipped years',()=>{assert.throws(()=>temporalModels([...series(),series()[0]],years),/duplicados/);assert.throws(()=>temporalModels(series([10,20,101,30]),years),/inválidos/);assert.throws(()=>temporalModels(series(),[2022,2026]),/consecutivas/);assert.throws(()=>temporalModels(series(),[2014,2022,2026]),/consecutivas/);const rows=series();rows[1].valid=null;assert.throws(()=>temporalModels(rows,years),/Nenhum território/);});
test('bounds are explicit, equal territory weighting and deterministic output',()=>{const rows=[...series([0,0,50,100],'A'),...series([10,10,10,10],'B')];const r=temporalModels(rows,years);assert.equal(r.projections.find(p=>p.key==='A').linear,100);assert.equal(r.projections.find(p=>p.key==='A').linear_clipped,true);assert.equal(r.folds[0].linear.mae,25);assert.deepEqual(temporalModels(rows.slice().reverse(),years),r);assert.equal(r.folds.length,2);assert.match(r.notice,/sem intervalo de confiança calibrado/);});
