const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript'),vm=require('node:vm');
const id='00000000-0000-0000-0000-000000000002',attempt='00000000-0000-0000-0000-000000000003';
function route(){let allowed=false,sourceCalls=0,writes=0,existing=null,failSource=false;const db={from(table){const chain={select(){return this},eq(){return this},async maybeSingle(){return {data:table==='ibfc_legislative_records'?{id,title:'Projeto teste',source_url:'https://dadosabertos.camara.leg.br/api/v2/proposicoes/123'}:existing,error:null}}};return chain},async rpc(){writes++;return {data:{id:attempt},error:null}}};
 const mod={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(require.resolve('../app/api/admin/science/tramitation/route.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports:mod,Date,require:name=>name==='next/server'?require('next/server'):name==='node:crypto'?require(name):name.includes('electoral/auth')?{electoralStaff:async()=>({allowed,db})}:name.includes('compare-tramitation')?{compareTramitation:()=>({})}:name.includes('legislative/tramitation')?{collectTramitation:async()=>{sourceCalls++;if(failSource)throw Error('HTTP 502');return {steps:[],raw:{dados:[],links:[]},source:'https://dadosabertos.camara.leg.br/api/v2/proposicoes/123/tramitacoes'}}}:{canonicalJson:JSON.stringify}});
 return {mod,setAllowed:v=>allowed=v,setExisting:v=>existing=v,setFail:v=>failSource=v,stats:()=>({sourceCalls,writes})};}
const request=(origin='https://portal.example',body={record_id:id,request_id:attempt})=>({headers:new Headers({origin}),nextUrl:new URL('https://portal.example/api?record_id='+id),json:async()=>body});
test('save refuses unauthorized user, cross origin and malformed request before source or database write',async()=>{const r=route();assert.equal((await r.mod.POST(request())).status,403);r.setAllowed(true);assert.equal((await r.mod.POST(request('https://evil.example'))).status,403);assert.equal((await r.mod.POST(request('https://portal.example',{record_id:id}))).status,400);assert.deepEqual(r.stats(),{sourceCalls:0,writes:0});});
test('lost acknowledgement retries stored version without new official call',async()=>{const r=route();r.setAllowed(true);r.setExisting({id:attempt,snapshot:{source_hash:'a'.repeat(64)}});const response=await r.mod.POST(request());assert.equal(response.status,200);assert.equal((await response.json()).archive.id,attempt);assert.deepEqual(r.stats(),{sourceCalls:0,writes:0});});
test('official failure does not save an empty or failed snapshot; read-only live query never writes',async()=>{const r=route();r.setAllowed(true);r.setFail(true);assert.equal((await r.mod.POST(request())).status,502);assert.deepEqual(r.stats(),{sourceCalls:1,writes:0});r.setFail(false);assert.equal((await r.mod.GET(request())).status,200);assert.deepEqual(r.stats(),{sourceCalls:2,writes:0});});
