import {NextRequest,NextResponse} from 'next/server';
import {electoralStaff} from '@/lib/electoral/auth';
import {RUN_FIELDS} from '@/lib/legislative/types';
export const dynamic='force-dynamic';export const maxDuration=30;
const uuid=(v:unknown)=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v);
const fail=(error:string,status=400)=>NextResponse.json({error},{status});
function config(){return {token:process.env.GITHUB_LEGISLATIVE_TOKEN||process.env.GITHUB_TSE_TOKEN,repository:process.env.GITHUB_LEGISLATIVE_REPOSITORY||process.env.GITHUB_TSE_REPOSITORY,ref:process.env.GITHUB_LEGISLATIVE_REF||process.env.GITHUB_TSE_REF||'main'};}
export async function GET(r:NextRequest){const {db,allowed}=await electoralStaff();if(!allowed)return fail('Acesso administrativo necessário.',403);const id=r.nextUrl.searchParams.get('candidate_id');if(!uuid(id))return fail('Candidato inválido.');const c=config();const [runs,schedules]=await Promise.all([db.from('ibfc_legislative_runs').select(RUN_FIELDS).eq('candidate_id',id).eq('execution_mode','background').order('created_at',{ascending:false}).limit(30),db.from('ibfc_legislative_schedules').select('*').eq('candidate_id',id).order('created_at',{ascending:false}).limit(100)]);if(runs.error||schedules.error)return fail('Automação indisponível. Execute a migração 20261027 após a 20261025.',503);return NextResponse.json({runs:runs.data,schedules:schedules.data,configured:Boolean(c.token&&c.repository),checked_at:new Date().toISOString()},{headers:{'Cache-Control':'no-store'}});}
export async function POST(r:NextRequest){const {db,allowed}=await electoralStaff();if(!allowed)return fail('Acesso administrativo necessário.',403);if(r.headers.get('origin')!==r.nextUrl.origin)return fail('Origem inválida.',403);let b;try{b=await r.json();}catch{return fail('Pedido inválido.');}if(!b||typeof b!=='object'||!uuid(b.id)||!['enqueue','pause','schedule','toggle_schedule'].includes(b.action))return fail('Ação inválida.');
 const c=config();if(b.action==='enqueue'&&(!c.token||!c.repository||!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(c.repository)))return fail('Configure GITHUB_TSE_TOKEN e GITHUB_TSE_REPOSITORY na Vercel, ou os equivalentes GITHUB_LEGISLATIVE_TOKEN/REPOSITORY.');
 const p:Record<string,unknown>={action:b.action,id:b.id};if(b.action==='schedule'){if(![1,7].includes(b.interval_days)||!Number.isInteger(b.lookback_days)||b.lookback_days<1||b.lookback_days>90||typeof b.enabled!=='boolean')return fail('Use frequência diária/semanal e janela de 1 a 90 dias.');Object.assign(p,{interval_days:b.interval_days,lookback_days:b.lookback_days,enabled:b.enabled});}if(b.action==='toggle_schedule'){if(typeof b.enabled!=='boolean')return fail('Agenda inválida.');p.enabled=b.enabled;}
 const {data,error}=await db.rpc('ibfc_legislative_background_control',{p_data:p});if(error)return fail(error.message,409);
 if(b.action!=='enqueue')return NextResponse.json({result:data});
 try{const response=await fetch(`https://api.github.com/repos/${c.repository}/actions/workflows/ibfc-legislative-sync.yml/dispatches`,{method:'POST',headers:{Authorization:`Bearer ${c.token}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'},body:JSON.stringify({ref:c.ref,inputs:{run_id:b.id}}),signal:AbortSignal.timeout(15000),cache:'no-store',redirect:'error'});if(!response.ok){await db.rpc('ibfc_legislative_background_control',{p_data:{action:'dispatch_failed',id:b.id}});return fail(`GitHub recusou o início (HTTP ${response.status}). Instale ibfc-legislative-sync.yml na branch configurada e confira o token Actions e o repositório.`,502);}return NextResponse.json({run:data,message:'Coleta na fila do GitHub Actions. Pode fechar o portal; acompanhe o histórico de segundo plano.'});}catch{return fail('Não foi possível confirmar a resposta do GitHub. A coleta permanece na fila; atualize o histórico antes de tentar novamente.',502);}
}
