'use client';
import {useMemo,useState} from 'react';
import type {ScienceReport} from '@/lib/science/types';
import {ADVANCED_METHOD,aggregateDescription,geographicValidation,aggregateScenario} from '@/lib/science/advanced-statistics';
import {number,percentage} from '@/lib/electoral/analysis';
export function AdvancedStatistics({report}:{report:ScienceReport}){
 const [swing,setSwing]=useState(0),[volume,setVolume]=useState(0),[sensitivity,setSensitivity]=useState(2);
 const description=useMemo(()=>aggregateDescription(report.rows),[report]);
 const validation=useMemo(()=>report.truncated?null:geographicValidation(report.rows),[report]);
 const scenario=aggregateScenario(report.totals.new_votes,report.totals.new_valid,swing,volume,sensitivity);
 function download(){const result={method:ADVANCED_METHOD,analysis_id:report.analysis_id,source_sha256:report.result_sha256,generated_at:new Date().toISOString(),sources:report.sources,coverage:report.coverage,total_rows:report.total_rows,truncated:report.truncated,description,validation,scenario:{hypotheses:{swing_pp:swing,valid_volume_change_pct:volume,sensitivity_pp:sensitivity},result:scenario},limitations:['Resultados públicos agregados; não identifica pessoas.','Validação espacial de resultados conhecidos, não validação temporal de previsão futura.','Faixa de sensibilidade definida pelo usuário, não intervalo de confiança.']};const url=URL.createObjectURL(new Blob([JSON.stringify(result,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='IBFC-metodo-estatistico.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="electoral-panel"><span className="electoral-eyebrow">MÉTODO {ADVANCED_METHOD}</span><h2>Validação geográfica e cenários agregados</h2><p>Indicadores calculados sobre {description.usableRows} territórios exibidos; {description.excludedRows} excluídos por valores ausentes ou incompatíveis.</p>{report.truncated&&<p role="alert" className="electoral-notice">Recorte parcial: os indicadores descritivos usam apenas as linhas exibidas. Validação bloqueada. Aprofunde o filtro para obter todas as linhas.</p>}
 <div className="science-kpis"><article><small>Participação ponderada</small><strong>{percentage(description.weightedShare)}</strong><span>Votos selecionados ÷ denominadores somados</span></article><article><small>Média dos territórios</small><strong>{percentage(description.meanTerritorialShare)}</strong><span>Cada território tem o mesmo peso</span></article><article><small>Territórios efetivos</small><strong>{description.effectiveTerritories?.toFixed(2)??'Não calculável'}</strong><span>1 ÷ HHI da distribuição dos votos</span></article></div><p>HHI: {description.hhi?.toFixed(4)??'não calculável'}. Concentração depende do recorte e do tamanho dos territórios; não compare índices calculados em níveis geográficos diferentes.</p>
 <h3>Teste em blocos geográficos</h3>{validation?.available?<><p>{validation.n} pares · {validation.groups} blocos por {validation.groupLevel.toLowerCase()} · {validation.folds} grupos de teste. Um bloco nunca aparece simultaneamente no treino e no teste.</p><div className="science-kpis"><article><small>Erro absoluto médio</small><strong>{validation.mae.toFixed(2)} pp</strong></article><article><small>RMSE da regressão</small><strong>{validation.rmse.toFixed(2)} pp</strong></article><article><small>RMSE da média de treino</small><strong>{validation.baselineRmse.toFixed(2)} pp</strong></article></div><p>RMSE ponderado pelo denominador: {validation.weightedRmse.toFixed(2)} pp. Melhoria sobre a média: {validation.skill===null?'não calculável':percentage(validation.skill*100)}. Valor negativo indica desempenho pior que a referência.</p><div className="science-table"><table><thead><tr><th>Grupo</th><th>Treino</th><th>Teste</th><th>RMSE (pp)</th></tr></thead><tbody>{validation.foldResults.map(f=><tr key={f.fold}><td>{f.fold}</td><td>{f.train}</td><td>{f.test}</td><td>{f.rmse.toFixed(2)}</td></tr>)}</tbody></table></div></>:<p>{validation?.reason??'Validação indisponível para uma tabela parcial.'}</p>}
 <p className="electoral-notice">A regressão estima associação entre duas eleições já observadas. Blocos reduzem mistura entre treino e teste, mas não eliminam dependência espacial. Previsão futura exige validação temporal e outras eleições. Não há estimativa de fidelidade individual.</p>
 <h3>Simulador de hipóteses</h3><div className="science-filters"><label>Variação da participação (pp)<input aria-label="Variação da participação (pp)" type="number" min={-20} max={20} step={0.5} value={swing} onChange={e=>setSwing(Number(e.target.value))}/></label><label>Variação dos votos válidos (%)<input aria-label="Variação dos votos válidos (%)" type="number" min={-50} max={50} step={1} value={volume} onChange={e=>setVolume(Number(e.target.value))}/></label><label>Sensibilidade escolhida (± pp)<input aria-label="Sensibilidade escolhida (± pp)" type="number" min={0} max={20} step={0.5} value={sensitivity} onChange={e=>setSensitivity(Number(e.target.value))}/></label></div>{scenario?<p>Hipótese central: <strong>{number(scenario.votes)} votos</strong> · {percentage(scenario.share)} de {number(scenario.volume)} votos válidos. Faixa de sensibilidade: {number(scenario.lowVotes)} a {number(scenario.highVotes)} votos.</p>:<p role="alert">Confira os limites das hipóteses e o denominador da base.</p>}<p>Esta faixa resulta das hipóteses digitadas; não é intervalo de confiança nem previsão probabilística. Votos válidos não equivalem necessariamente a pessoas, especialmente no Senado. O cenário usa os totais completos do filtro, inclusive quando a tabela é parcial.</p><button className="no-print" onClick={download}>Baixar método e resultados (JSON)</button></section>;
}
