'use client';
import {useState} from 'react';
import type {ScienceReport} from '@/lib/science/types';
import {number,csvCell} from '@/lib/electoral/analysis';
export function BuDetails({report}:{report:ScienceReport}){
 const [page,setPage]=useState(0),[query,setQuery]=useState('');
 const bu=report.bu;if(!bu?.total_rows)return null;
 const rows=bu.rows.filter(r=>`${r.uf} ${r.municipality} ${r.zone} ${r.local} ${r.section} ${r.metadata.urna}`.includes(query.trim()));
 const max=Math.max(0,Math.ceil(rows.length/25)-1),active=Math.min(page,max),shown=rows.slice(active*25,(active+1)*25);
 const pct=bu.totals.aptos?100*(bu.totals.abstencoes??0)/bu.totals.aptos:null;
 const download=()=>{const lines=[['UF','Município TSE','Zona','Local','Seção','Urna efetivada','Votos selecionados','Nominal + legenda do cargo','Aptos','Comparecimento','Abstenções','Brancos','Nulos','Legenda','Seções agregadas','Abertura','Encerramento','Emissão BU','Recebimento BU'],...rows.map(r=>[r.uf,r.municipality,r.zone,r.local,r.section,r.metadata.urna,r.votes,r.nominal_legenda,r.metadata.aptos,r.metadata.comparecimento,r.metadata.abstencoes,r.brancos,r.nulos,r.legenda,r.metadata.agregadas,r.metadata.abertura,r.metadata.encerramento,r.metadata.emissao,r.metadata.recebido])].map(r=>r.map(csvCell).join(';'));const url=URL.createObjectURL(new Blob(['\uFEFF'+lines.join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='IBFC-boletins-por-secao.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section className="electoral-panel"><h2>Seções e urnas · Boletins oficiais</h2><p>Eleitorado contado uma vez por seção, no cargo e turno selecionados. Seções agregadas permanecem juntas no boletim; número da seção e identificação da urna são campos diferentes.</p>
 <div className="science-kpis"><article><small>Eleitores aptos</small><strong>{number(bu.totals.aptos)}</strong></article><article><small>Comparecimento</small><strong>{number(bu.totals.comparecimento)}</strong></article><article><small>Abstenções</small><strong>{number(bu.totals.abstencoes)}</strong><span>{pct===null?'':`${pct.toFixed(2)}% dos aptos`}</span></article></div>
 <div className="science-actions"><label>Buscar zona, local, seção ou urna<input aria-label="Buscar urna" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}} placeholder="Código ou número"/></label><button onClick={download}>Baixar dados das seções</button></div>
 {bu.truncated&&<p className="electoral-notice">Exibidas até 5.000 de {number(bu.total_rows)} seções. Totais abrangem o recorte completo; selecione uma zona ou local para detalhar.</p>}
 <div className="science-table"><table><thead><tr><th>Zona / local / seção</th><th>Urna</th><th>Votos selecionados</th><th>Aptos</th><th>Compareceram</th><th>Abstenções</th><th>Brancos / nulos</th><th>Legenda</th><th>Horários e agregações</th></tr></thead><tbody>{shown.map(r=><tr key={`${r.uf}:${r.municipality}:${r.zone}:${r.section}`}><td>{r.uf} · zona {r.zone}<small>Local {r.local} · seção {r.section}</small></td><td>{r.metadata.urna}<small>{r.metadata.status}</small></td><td><strong>{number(r.votes)}</strong><small>{r.nominal_legenda?`${(100*r.votes/r.nominal_legenda).toFixed(2)}% do nominal + legenda`:"Sem denominador"}</small></td><td>{number(r.metadata.aptos)}</td><td>{number(r.metadata.comparecimento)}</td><td>{number(r.metadata.abstencoes)}</td><td>{number(r.brancos)} / {number(r.nulos)}</td><td>{number(r.legenda)}</td><td><small>Abertura: {r.metadata.abertura??'Sem informação'}<br/>Encerramento: {r.metadata.encerramento??'Sem informação'}{r.metadata.agregadas&&<><br/>Agregadas: {r.metadata.agregadas}</>}</small></td></tr>)}</tbody></table></div>
 <div className="science-actions"><button disabled={!active} onClick={()=>setPage(active-1)}>Anterior</button><span>Página {active+1} de {max+1} · {number(rows.length)} seções</span><button disabled={active>=max} onClick={()=>setPage(active+1)}>Próxima</button></div></section>;
}
