"use client";
import {useMemo,useState} from 'react';
import type {ScienceReport} from '@/lib/science/types';
import {reconcileBu,reconciliationCsv,RECONCILIATION_LABELS,type ReconciliationContext,type ReconciliationStatus} from '@/lib/science/bu-reconciliation';
import {number} from '@/lib/electoral/analysis';
export function BuReconciliation({report,context}:{report:ScienceReport;context:ReconciliationContext}){
 const result=useMemo(()=>reconcileBu(report,context),[report,context]);
 const [status,setStatus]=useState<ReconciliationStatus|'all'>('all'),[search,setSearch]=useState(''),[page,setPage]=useState(0);
 const normalize=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const rows=result.lines.filter(row=>(status==='all'||row.status===status)&&normalize(row.name+' '+row.key).includes(normalize(search.trim())));
 const lastPage=Math.max(0,Math.ceil(rows.length/50)-1),activePage=Math.min(page,lastPage);
 function download(kind:'csv'|'json'){const content=kind==='csv'?reconciliationCsv(result):JSON.stringify({...result,exported_at:new Date().toISOString()},null,2);const url=URL.createObjectURL(new Blob([content],{type:kind==='csv'?'text/csv;charset=utf-8':'application/json'})),a=document.createElement('a');a.href=url;a.download='IBFC-reconciliacao-BU.'+kind;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <details className="electoral-panel bu-reconciliation"><summary>Reconciliação de boletins · {context.selection}</summary><p>Conferência interna dos boletins carregados com os resultados da seleção atual/B. Não consulta uma segunda fonte independente. Em comparações históricas ou entre cargos, a seleção A não é reconciliada aqui.</p>
 <div className="science-kpis"><article><small>Coincidentes no conjunto comparável</small><strong>{result.counts.equal}</strong></article><article><small>Divergências numéricas</small><strong>{result.counts.different}</strong></article><article><small>Linhas sem comparação concluída</small><strong>{result.lines.length-result.counts.equal-result.counts.different}</strong></article></div>
 <p>Boletins carregados: {result.coverage.bu_sections_loaded} de {number(result.coverage.bu_sections_total)}. Linhas da análise: {result.coverage.analysis_rows_loaded} de {result.coverage.analysis_rows_total}.</p>
 <p className="electoral-notice">{result.limitations}</p>
 {result.notices.length>0&&<ul>{result.notices.map(n=><li key={n}>{n}</li>)}</ul>}
 <h3>Total do recorte · {result.totals.comparable?'comparável por cobertura e contagens declaradas':'não reconciliado'}</h3>
 <p>Votos da análise B: {number(result.totals.analysis_votes)} · votos dos BU do recorte completo: {number(result.totals.bu_votes)} · diferença BU − análise: {number(result.totals.delta_votes)}. Diferença do denominador: {number(result.totals.delta_valid)}.</p>
 <div className="science-filters no-print"><label>Resultado da reconciliação<select aria-label="Resultado da reconciliação" value={status} onChange={e=>{setStatus(e.target.value as typeof status);setPage(0);}}><option value="all">Todos</option>{Object.entries(RECONCILIATION_LABELS).map(([key,label])=><option key={key} value={key}>{label} ({result.counts[key as ReconciliationStatus]})</option>)}</select></label><label>Buscar território ou chave<input aria-label="Buscar território na reconciliação" value={search} maxLength={120} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label></div>
 <div className="science-actions no-print"><button onClick={()=>download('csv')}>Baixar reconciliação CSV</button><button onClick={()=>download('json')}>Baixar reconciliação JSON</button></div><p>Os arquivos incluem todo o diagnóstico retornado, sem restringir à busca ou página da tela. Valores BU carregados podem ser parciais; diferença ausente não significa zero.</p>
 <div className="science-table"><table><thead><tr><th>Território / chave</th><th>Resultado</th><th>Seções B / BU carregados</th><th>Votos análise B</th><th>Votos BU carregados</th><th>Diferença de votos</th><th>Diferença do denominador</th></tr></thead><tbody>{rows.slice(activePage*50,(activePage+1)*50).map((row,i)=><tr key={row.key+':'+i}><th>{row.name}<small>{row.key}</small></th><td>{RECONCILIATION_LABELS[row.status]}</td><td>{number(row.expected_sections)} / {row.loaded_sections}</td><td>{number(row.analysis_votes)}</td><td>{number(row.bu_votes)}</td><td>{row.delta_votes===null?'Não comparável':number(row.delta_votes)}</td><td>{row.delta_valid===null?'Não comparável':number(row.delta_valid)}</td></tr>)}</tbody></table></div>
 {!rows.length&&<p>Nenhuma linha neste filtro.</p>}<div className="science-actions no-print"><button disabled={activePage===0} onClick={()=>setPage(activePage-1)}>Reconciliação: anterior</button><span>{rows.length} linhas no filtro · página {activePage+1} de {lastPage+1}</span><button disabled={activePage>=lastPage} onClick={()=>setPage(activePage+1)}>Reconciliação: próxima</button></div>
 <p className="electoral-caption">Método: {result.method} · protocolo: {result.analysis_id??'não informado'}. Hash original: <span style={{overflowWrap:'anywhere'}}>{result.result_sha256??'não informado'}</span>. Diferenças servem para investigação da cobertura, filtros e origem; não são conclusões sobre a lisura eleitoral.</p></details>;
}
