"use client";
import {useMemo,useState} from 'react';
import type {ComparisonColumn} from '@/lib/science/multi-comparison';
import {pairMapData,geographicPositions,historicalGeographicCoverage,type ComparisonMetric} from '@/lib/science/comparison-maps';
import {LeafletElectionMap} from '@/components/electoral/LeafletElectionMap';
export function ComparisonMaps({columns,historical=false}:{columns:ComparisonColumn[];historical?:boolean}){
 const [left,setLeft]=useState(0),[right,setRight]=useState(1),[metric,setMetric]=useState<ComparisonMetric>('votes'),[fit,setFit]=useState(0),[selected,setSelected]=useState('');
 const data=useMemo(()=>pairMapData(columns,left,right,metric,historical),[columns,left,right,metric,historical]);
 const chosen=data.selected.map(c=>c.report.rows.find(r=>r.key===selected));
 return <section className="electoral-panel"><h2>Mapas lado a lado</h2><p>Mesmo recorte e escala de símbolos compartilhada. Cada mapa mantém as coordenadas de sua fonte. O enquadramento inicial e o botão de ajuste usam a união dos pontos; navegação manual é independente.</p>
 <div className="science-filters"><label>Mapa azul<select aria-label="Mapa azul" value={left} onChange={e=>{const n=Number(e.target.value);if(n===right)setRight(left);setLeft(n);setSelected('');}}>{columns.map((c,i)=><option value={i} key={i}>{c.target.name}</option>)}</select></label><label>Mapa vermelho<select aria-label="Mapa vermelho" value={right} onChange={e=>{const n=Number(e.target.value);if(n===left)setLeft(right);setRight(n);setSelected('');}}>{columns.map((c,i)=><option value={i} key={i}>{c.target.name}</option>)}</select></label><label>Tamanho dos símbolos<select aria-label="Tamanho dos símbolos" value={metric} onChange={e=>setMetric(e.target.value as ComparisonMetric)}><option value="votes">Votos absolutos</option><option value="share">Participação no denominador</option></select></label></div>
 <button onClick={()=>setFit(v=>v+1)}>Enquadrar os dois mapas</button>
 <p>Escala comum máxima: {data.max.toLocaleString('pt-BR',{maximumFractionDigits:2})}{metric==='share'?'%':' votos'}. Cinza: sem resultado calculável. Zero confirmado usa símbolo mínimo. Círculos não representam limites oficiais.</p>
 {metric==='share'&&<p>Compare percentuais somente com fontes, granularidades e denominadores compatíveis; confira a indicação na tabela da comparação.</p>}
 <div className="comparison-map-grid">{data.selected.map((c,i)=><article key={i}><h3>{c.target.name}</h3><p>{geographicPositions([{...c,report:{...c.report,rows:c.report.rows.filter(row=>!historical||(Number.isInteger(row.coordinate_year)&&row.coordinate_year!<=c.target.year))}}]).length} coordenadas distintas · {c.report.rows.length} registros retornados{c.report.truncated?' · carga limitada':''}. Pontos sobrepostos podem reunir várias linhas.</p>{historical&&<p className="electoral-notice">Cobertura cartográfica: {historicalGeographicCoverage(c).plotted_rows} linhas com coordenadas elegíveis; {historicalGeographicCoverage(c).missing_coordinates} sem coordenadas válidas; {historicalGeographicCoverage(c).excluded_future} referências posteriores a {c.target.year} ocultas; {historicalGeographicCoverage(c).excluded_unknown_year} sem ano cartográfico ocultas; {historicalGeographicCoverage(c).reference_prior_year} referências anteriores ao ano consultado. Resultados permanecem nos relatórios.</p>}<LeafletElectionMap places={data.maps[i]} onSelect={setSelected} fitPositions={data.positions} exportConfig={{title:c.target.name,subtitle:`${c.target.year} · ${c.target.uf} · cargo ${c.target.office} · turno ${c.target.turn}`,filename:`IBFC-${c.target.name}-${c.target.year}`,legend:[`${i===0?'Azul':'Vermelho'}: ${metric==='votes'?'votos absolutos':'participação no denominador'}; cinza: sem resultado calculável.`,`Escala comum máxima: ${data.max.toLocaleString('pt-BR')} ${metric==='share'?'%':'votos'}. Zero confirmado: símbolo mínimo.`],details:[`${c.report.rows.length} registros retornados${c.report.truncated?' (carga limitada)':''}. Círculos não são limites oficiais.`,historical?`Cartografia elegível: ${historicalGeographicCoverage(c).plotted_rows}; sem coordenadas: ${historicalGeographicCoverage(c).missing_coordinates}; referências futuras ocultas: ${historicalGeographicCoverage(c).excluded_future}; ano desconhecido oculto: ${historicalGeographicCoverage(c).excluded_unknown_year}.`:'Registros sem coordenadas permanecem no relatório.',`Protocolo: ${c.report.analysis_id??'não arquivado'} · dados gerados em ${c.report.generated_at}`,`SHA-256 do relatório original: ${c.report.result_sha256??'não informado'}`,...c.report.sources.slice(0,3).map(source=>`Fonte ${source.year}: ${source.filename} · ${source.source_url}`),...(c.report.sources.length>3?[`Mais ${c.report.sources.length-3} fontes no relatório completo.`]:[]),'Fonte: bases eleitorais importadas no IBFC. Consulte fontes e recorte completo no relatório CSV/JSON.']}} viewportKey={`${left}:${right}:${fit}`}/><small>Protocolo: {c.report.analysis_id} · gerado em {c.report.generated_at}</small></article>)}</div>
 {selected&&<div role="status"><h3>Território selecionado</h3>{chosen.map((row,i)=><p key={i}>{data.selected[i].target.name}: {row?`${row.name} · ${row.new_votes===null?'Sem dados':row.new_votes.toLocaleString('pt-BR')+' votos'}`:'Território ausente nesta seleção'}</p>)}</div>}
 <p>Registros sem coordenadas válidas continuam na tabela e nas exportações da comparação. A imagem do mapa não substitui a fonte oficial. Os dados pessoais de apoiadores não são usados aqui.</p></section>;
}
