"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import type {ScienceReport,Target} from '@/lib/science/types';
import type {ComparisonColumn} from '@/lib/science/multi-comparison';
import {historicalSnapshot,historicalCsv,HISTORICAL_STATUS_LABELS,assertHistoricalRecorte,type HistoricalStatus} from '@/lib/science/historical-coverage';
import {number,percentage} from '@/lib/electoral/analysis';
import {ReportExport} from '@/components/science/ReportExport';
import {historicalPrintHtml} from '@/lib/science/print-report';
import {SCIENCE_VERSION,SCIENCE_BUILD} from '@/lib/science/version';
import {ComparisonMaps} from '@/components/science/ComparisonMaps';
export type HistoricalContext={old:Target;new:Target;scope:string;filters:Record<string,number|boolean>};
export function HistoricalTerritory({report,context}:{report:ScienceReport;context:HistoricalContext}){
 const [status,setStatus]=useState<HistoricalStatus|'all'>('all'),[search,setSearch]=useState(''),[page,setPage]=useState(0);
 const [maps,setMaps]=useState<ComparisonColumn[]>([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState('');const active=useRef<AbortController|null>(null);
 const snapshot=useMemo(()=>historicalSnapshot(report,context.old,context.new,context.scope,context.filters),[report,context]);const c=snapshot.coverage;
 const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const rows=c.lines.filter(l=>(status==='all'||l.status===status)&&normalize(l.row.name+' '+l.row.uf+' '+l.row.municipality+' '+l.row.zone).includes(normalize(search)));
 useEffect(()=>setPage(0),[status,search]);
 useEffect(()=>{active.current?.abort();setMaps([]);setBusy(false);setError('');setProgress(0);return()=>active.current?.abort();},[report,context]);
 async function loadMaps(){const controller=new AbortController();active.current?.abort();active.current=controller;setBusy(true);setMaps([]);setProgress(0);setError('');
  try{assertHistoricalRecorte(context.old,context.new);const columns:ComparisonColumn[]=[];
   for(const target of [context.old,context.new]){const filters={...context.filters,common_only:false};const r=await fetch('/api/admin/science',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'current',new:target,scope:context.scope,filters}),signal:controller.signal});const d=await r.json() as ScienceReport&{error?:string};if(!r.ok)throw Error(target.year+': '+d.error);if(controller.signal.aborted)return;columns.push({target:{...target,name:target.name+' · '+target.year},report:d});setProgress(columns.length);}
   if(!controller.signal.aborted)setMaps(columns);
  }catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Não foi possível consultar os mapas de cada ano.');}finally{if(active.current===controller&&!controller.signal.aborted)setBusy(false);}
 }
 function download(type:'csv'|'json'){const content=type==='csv'?historicalCsv(snapshot):JSON.stringify(snapshot,null,2);const url=URL.createObjectURL(new Blob([content],{type:type==='csv'?'text/csv;charset=utf-8':'application/json'}));const a=document.createElement('a');a.href=url;a.download=`IBFC-diagnostico-historico-${context.new.uf}-${context.scope}.${type}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <><section className="electoral-panel"><span className="electoral-eyebrow">COBERTURA HISTÓRICA</span><h2>Diagnóstico territorial · 2022 e 2026</h2><p>{context.old.name} (2022) → {context.new.name} (2026). As escolhas são feitas pelo analista; o painel não certifica que as candidaturas representam a mesma pessoa, partido ou composição.</p>
 <div className="multi-summary"><article><h3>Dados nos dois anos</h3><strong>{c.both_years} / {c.available_rows}</strong><p>{percentage(c.both_years_percent)} das linhas retornadas com dados em pelo menos um ano.</p></article><article><h3>Dados somente em 2022</h3><strong>{c.counts.old_only}</strong><p>Ausência em 2026 não comprova extinção ou zero voto.</p></article><article><h3>Dados somente em 2026</h3><strong>{c.counts.new_only}</strong><p>Ausência em 2022 não comprova criação do território.</p></article></div>
 {report.granularity==='zone'?<p className="electoral-notice">Fonte por zona: não há diagnóstico de chaves de seção ou mudança de local nesta base.</p>:<p>Totais do recorte: {number(c.old_sections)} seções em 2022, {number(c.new_sections)} em 2026, {number(c.common_sections)} chaves comuns e {number(c.moved_sections)} mudanças de local registradas. Chaves comuns ÷ menor conjunto de seções: {percentage(c.common_over_smaller_percent)}. Esses totais vêm do relatório; não são contagens de eleitores.</p>}
 <p>Chaves iguais não comprovam continuidade do eleitorado nem equivalência geográfica oficial. Mudanças são detectadas pelos registros importados. Em agregações por município ou local, a classificação descreve o conjunto de seções, não cada endereço.</p>
 {c.truncated&&<p role="alert">Diagnóstico limitado a {c.visible_rows} de {c.total_rows} linhas. As proporções e classificações abaixo descrevem apenas o conjunto retornado. Totais de seções acima vêm do recorte completo.</p>}
 <div className="science-filters"><label>Classificação histórica<select aria-label="Classificação histórica" value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="all">Todas</option>{Object.entries(HISTORICAL_STATUS_LABELS).map(([k,v])=><option key={k} value={k}>{v} ({c.counts[k as HistoricalStatus]})</option>)}</select></label><label>Buscar território histórico<input value={search} maxLength={120} onChange={e=>setSearch(e.target.value)}/></label></div>
 <ReportExport reportKey={JSON.stringify([context,report.analysis_id,report.generated_at])} filename={`IBFC-historico-${context.new.uf}`} buildDocument={details=>historicalPrintHtml(snapshot,report,HISTORICAL_STATUS_LABELS,{details,exportedAt:new Date().toLocaleString('pt-BR'),version:SCIENCE_VERSION+' · '+SCIENCE_BUILD})}/>
 <button onClick={()=>download('csv')}>Baixar diagnóstico CSV</button> <button onClick={()=>download('json')}>Baixar diagnóstico JSON</button><p>Os arquivos preservam todo o diagnóstico retornado, sem aplicar a busca ou a paginação da tela.</p>
 <div className="multi-table"><table><thead><tr><th>Território</th><th>Classificação</th><th>Votos 2022</th><th>Votos 2026</th><th>Diferença de votos</th><th>Variação relativa</th><th>Variação pp</th></tr></thead><tbody>{rows.slice(page*50,(page+1)*50).map(l=><tr key={l.row.key}><th>{l.row.name} · {l.row.uf}</th><td>{HISTORICAL_STATUS_LABELS[l.status]}</td><td>{number(l.row.old_votes)}</td><td>{number(l.row.new_votes)}</td><td>{number(l.delta_votes)}</td><td>{percentage(l.relative_change)}</td><td>{l.delta_points===null?'Não calculável':l.delta_points.toLocaleString('pt-BR',{maximumFractionDigits:2})+' pp'}</td></tr>)}</tbody></table></div>
 {!rows.length&&<p>Nenhuma linha nesta classificação ou busca.</p>}<button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Diagnóstico: anterior</button> <span>{rows.length} registros no filtro</span> <button disabled={(page+1)*50>=rows.length} onClick={()=>setPage(p=>p+1)}>Diagnóstico: próxima</button>
 <p>Variação relativa não é calculada quando a votação anterior é zero. Participação usa o denominador de cada ano; mudanças de cobertura, regras e número de votos por cargo devem ser consideradas. O painel não mede fidelidade ou transferência de votos individuais.</p>
 <h3>Mapas de cada ano</h3><p>Carregue consultas independentes para preservar votos, coordenadas, fontes e protocolos próprios de 2022 e 2026. Os mapas incluem todas as chaves do recorte de cada ano, mesmo se a análise histórica estiver restrita a chaves comuns.</p>
 <button disabled={busy} onClick={()=>void loadMaps()}>Carregar mapas históricos</button>{busy&&<div role="status"><progress value={progress} max={2}/> {progress} de 2 consultas concluídas <button onClick={()=>{active.current?.abort();setBusy(false);setMaps([]);}}>Cancelar mapas históricos</button></div>}{error&&<p role="alert">{error}</p>}
 <p className="electoral-caption">Protocolo histórico: {report.analysis_id}. Método: {snapshot.method_version}. Referências anteriores ao ano consultado podem ser usadas pela base existente; confira o ano cartográfico indicado em cada ponto.</p></section>
 {maps.length===2&&<ComparisonMaps columns={maps} historical/>}</>;
}
