'use client';
import {useCallback,useEffect,useState} from 'react';
import {Evidence} from './Evidence';
import {STATUS} from '@/lib/science/statistics';
import type {Investigation} from '@/lib/science/types';
const fields:Record<string,string>={hypothesis:'Hipótese',method:'Método de verificação',alternatives:'Explicações alternativas',sources:'Fontes e documentos (URL / referência)',conclusion:'Conclusão e limites',reviewer:'Responsável pela revisão',period:'Eleição e período analisado'};
const blank=()=>({protocol:'INV-2026-',title:'',status:'review',payload:Object.fromEntries(Object.keys(fields).map(k=>[k,'']))});
export function Investigations(){const [rows,setRows]=useState<Investigation[]>([]),[form,setForm]=useState<ReturnType<typeof blank>&{id?:string;revision?:number}>(blank),[error,setError]=useState(''),[busy,setBusy]=useState(false),[versions,setVersions]=useState<{created_at:string;snapshot:Investigation}[]>([]),[message,setMessage]=useState('');const refresh=useCallback(async()=>{try{const r=await fetch('/api/admin/science/investigations',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setRows(d.rows);}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar.');}},[]);useEffect(()=>{void refresh();},[refresh]);
 async function save(){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/admin/science/investigations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw Error(d.error);setMessage('Investigação salva. A revisão anterior permanece no histórico.');setForm(blank());setVersions([]);await refresh();}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar.');}finally{setBusy(false);}}
 async function edit(x:Investigation){setForm({...x,payload:{...blank().payload,...x.payload}});setVersions([]);try{const r=await fetch(`/api/admin/science/investigations?id=${x.id}`);const d=await r.json();if(!r.ok)throw Error(d.error);setVersions(d.rows);}catch(e){setError(e instanceof Error?e.message:'Histórico indisponível.');}}
 return <><header className="science-hero"><span className="electoral-eyebrow">HIPÓTESE · EVIDÊNCIA · REVISÃO</span><h1>Investigações documentadas</h1><p>Separe relatos, fatos confirmados e conclusões. Registre o método e as explicações alternativas.</p></header>{error&&<p role="alert" className="electoral-notice electoral-error">{error}</p>}{message&&<p role="status">{message}</p>}<div className="science-investigations"><section className="electoral-panel"><h2>Protocolos</h2><button onClick={()=>{setForm(blank());setVersions([]);}}>Nova investigação</button>{rows.map(x=><button className="science-protocol" key={x.id} onClick={()=>void edit(x)}><b>{x.protocol} · revisão {x.revision}</b><span>{x.title}</span><small>{STATUS[x.status]}</small></button>)}</section><section className="electoral-panel"><h2>{form.id?'Editar investigação':'Novo protocolo'}</h2><div className="science-filters"><label>Protocolo<input value={form.protocol} onChange={e=>setForm({...form,protocol:e.target.value})} maxLength={50}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{Object.entries(STATUS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div><label>Título<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} maxLength={250}/></label>{Object.entries(fields).map(([key,label])=><label key={key}>{label}<textarea rows={3} maxLength={10000} value={form.payload[key]??''} onChange={e=>setForm({...form,payload:{...form.payload,[key]:e.target.value}})}/></label>)}<button className="electoral-primary" disabled={busy} onClick={()=>void save()}>{busy?'Salvando…':'Salvar revisão'}</button>{form.id&&<Evidence key={form.id} investigation={form.id}/>}<p className="electoral-caption">Referências cadastradas não são arquivos verificados criptograficamente. Conclusões exigem revisão da evidência original.</p>{versions.length>0&&<details><summary>Histórico · {versions.length} revisões anteriores</summary>{versions.map((v,i)=><article key={i}><h3>Revisão {v.snapshot.revision} · {new Date(v.created_at).toLocaleString('pt-BR')}</h3><p>{STATUS[v.snapshot.status]} · {v.snapshot.title}</p><pre className="science-history">{JSON.stringify(v.snapshot.payload,null,2)}</pre></article>)}</details>}</section></div></>;
}
