'use client';
import {useEffect,useRef,useState} from 'react';
import {CATEGORIES,type LegislativeRun,type LegislativeSchedule} from '@/lib/legislative/types';
const labels:Record<string,string>={queued:'Na fila do worker',processing:'Em processamento',paused:'Pausada',failed:'Interrompida; pode retomar',done:'Worker encerrado'};
export function LegislativeAutomation({candidate,refresh,onUpdated}:{candidate:string;refresh:number;onUpdated:()=>void}){
 const [runs,setRuns]=useState<LegislativeRun[]>([]),[schedules,setSchedules]=useState<LegislativeSchedule[]>([]),[configured,setConfigured]=useState(false),[loading,setLoading]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[reload,setReload]=useState(0),[checked,setChecked]=useState('');const prior=useRef(new Map<string,string>());
 useEffect(()=>{if(!candidate){setRuns([]);setSchedules([]);return;}const abort=new AbortController();let fetching=false;async function load(){if(fetching)return;fetching=true;setLoading(true);try{const r=await fetch('/api/admin/science/automation?candidate_id='+candidate,{cache:'no-store',signal:abort.signal}),d=await r.json();if(!r.ok)throw Error(d.error);const completed=d.runs.some((run:LegislativeRun)=>prior.current.has(run.id)&&prior.current.get(run.id)!=='done'&&run.queue_status==='done');prior.current=new Map(d.runs.map((run:LegislativeRun)=>[run.id,run.queue_status??'']));setRuns(d.runs);if(completed)onUpdated();setSchedules(d.schedules);setConfigured(d.configured);setChecked(d.checked_at);setError('');}catch(e){if(!abort.signal.aborted)setError(e instanceof Error?e.message:'Falha ao consultar fila.');}finally{fetching=false;if(!abort.signal.aborted)setLoading(false);}}void load();const timer=setInterval(()=>void load(),8000);return()=>{abort.abort();clearInterval(timer);};},[candidate,refresh,reload]);
 useEffect(()=>{setMessage('');setError('');},[candidate]);
 async function control(action:string,id:string,extra:Record<string,unknown>={}){setBusy(id);setError('');setMessage('');try{const r=await fetch('/api/admin/science/automation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,id,...extra})}),d=await r.json();if(!r.ok)throw Error(d.error);setMessage(d.message??(action==='pause'?'Coleta pausada. O lote em consulta não será gravado; os anteriores permanecem salvos.':'Agenda atualizada. Desativar a agenda não interrompe uma coleta já iniciada.'));setReload(x=>x+1);onUpdated();}catch(e){setError(e instanceof Error?e.message:'Falha ao atualizar fila.');setReload(x=>x+1);}finally{setBusy('');}}
 return <section className="electoral-panel legislative-automation"><h2>Fila e atualização em segundo plano</h2><p>A coleta é executada pelo GitHub Actions e pode continuar com o portal fechado. Cada lote salvo é um checkpoint. A fila depende da disponibilidade do GitHub e das fontes oficiais. Ao atingir o limite de tempo do worker, o checkpoint aguarda a próxima execução agendada ou uma retomada pelo portal.</p>
 <details><summary>Configurar execução e agenda</summary><p>Instale a migração <b>20261027</b> e o workflow <b>.github/workflows/ibfc-legislative-sync.yml</b>. Os Secrets do GitHub são <b>SUPABASE_URL</b> e <b>SUPABASE_SERVICE_ROLE_KEY</b>, os mesmos do worker eleitoral.</p><p>Para iniciar pelo portal, a Vercel reutiliza <b>GITHUB_TSE_TOKEN</b>, <b>GITHUB_TSE_REPOSITORY</b> e <b>GITHUB_TSE_REF</b>. Alternativamente, configure os equivalentes <b>GITHUB_LEGISLATIVE_TOKEN</b>, <b>GITHUB_LEGISLATIVE_REPOSITORY</b> e <b>GITHUB_LEGISLATIVE_REF</b>.</p><p>Para as agendas, no GitHub → Settings → Secrets and variables → Actions → Variables, crie <b>IBFC_LEGISLATIVE_AUTO_ENABLED=true</b>. O workflow verifica as agendas diariamente às <b>03h43 de Brasília</b>, sujeito à fila do GitHub. Desative com <b>false</b>. A agenda habilitada abaixo é uma configuração do banco; ela depende desse workflow ativo.</p></details>
 {!candidate?<p>Selecione um candidato para consultar a fila e as agendas.</p>:<><p>Disparo pelo portal: {configured?'configurado na Vercel':'ainda não configurado na Vercel'}. {checked&&<>Última consulta: {new Date(checked).toLocaleString('pt-BR')}.</>}</p><div className="science-actions"><button disabled={loading||Boolean(busy)} onClick={()=>setReload(x=>x+1)}>Atualizar fila</button></div>{loading&&<p role="status">Consultando fila…</p>}{error&&<p role="alert" className="electoral-error">{error}</p>}{message&&<p role="status">{message}</p>}
 <h3>Coletas em segundo plano</h3>{runs.map(run=>{const processing=run.queue_status==='processing'&&Boolean(run.lease_until)&&Date.parse(run.lease_until!)>Date.now(),ended=['completed','partial'].includes(run.status);return <article key={run.id} className="science-evidence"><strong>{run.official_name} · {run.provider} · {CATEGORIES[run.category]}</strong><p>{run.start_on} a {run.end_on} · {labels[run.queue_status??'']??run.queue_status} · {run.page-1} lotes salvos · {run.saved} registros processados.</p>{run.heartbeat_at&&<p>Último sinal do worker: {new Date(run.heartbeat_at).toLocaleString('pt-BR')}.</p>}{run.queue_status==='processing'&&!processing&&<p>Sem concessão de processamento válida. A coleta pode ser retomada a partir do último lote salvo.</p>}{run.status==='partial'&&<p>Limite de 1.000 lotes alcançado. Reduza o intervalo para completar a cobertura.</p>}{run.error&&<p role="alert">{run.error}</p>}<div className="science-actions">{!ended&&!processing&&<button disabled={Boolean(busy)||!configured} onClick={()=>void control('enqueue',run.id)}>Retomar em segundo plano</button>}{!ended&&['queued','processing'].includes(run.queue_status??'')&&<button disabled={Boolean(busy)} onClick={()=>void control('pause',run.id)}>Pausar coleta</button>}</div></article>;})}{!runs.length&&!loading&&<p>Nenhuma coleta em segundo plano registrada para este candidato.</p>}
 <h3>Agendas cadastradas</h3>{schedules.map(s=><article key={s.id} className="science-evidence"><strong>{s.official_name} · {s.provider} · {CATEGORIES[s.category]}</strong><p>{s.interval_days===1?'Diária':'Semanal'} · janela dos últimos {s.lookback_days} dias · {s.enabled?'habilitada no banco':'desativada'}.</p>{s.enabled&&<p>Elegível a partir de {new Date(s.next_run_at).toLocaleString('pt-BR')}; execução na próxima verificação do workflow.</p>}{s.last_error&&<p role="alert">{s.last_error}</p>}<button disabled={Boolean(busy)} onClick={()=>void control('toggle_schedule',s.id,{enabled:!s.enabled})}>{s.enabled?'Desativar agenda':'Ativar agenda'}</button></article>)}{!schedules.length&&!loading&&<p>Nenhuma agenda cadastrada. Ao iniciar uma coleta em segundo plano, escolha atualização diária ou semanal para criar uma.</p>}</>}
 </section>;
}
