'use client';
import {useEffect,useRef,useState} from 'react';
import {TramitationArchive} from './TramitationArchive';
import type {Step} from '@/lib/legislative/tramitation';
type History={steps:Step[];title:string;checked_at:string;source:string;source_hash:string;raw:unknown;archive_id?:string;archive_created_at?:string};
export function ProjectTramitation({recordId}:{recordId:string}){
 const [history,setHistory]=useState<History|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[shown,setShown]=useState(50);const abort=useRef<AbortController|null>(null);
 useEffect(()=>()=>abort.current?.abort(),[]);
 async function load(){abort.current?.abort();const controller=new AbortController();abort.current=controller;setBusy(true);setError('');try{const r=await fetch('/api/admin/science/tramitation?'+new URLSearchParams({record_id:recordId}),{cache:'no-store',signal:controller.signal});const data=await r.json();if(!r.ok)throw Error(data.error);setHistory(data);setShown(50);}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Falha de consulta.');}finally{if(!controller.signal.aborted)setBusy(false);}}
 function download(){if(!history)return;const u=URL.createObjectURL(new Blob([JSON.stringify(history,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='ibfc-tramitacao-'+recordId+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
 return <details className="project-tramitation"><summary>Histórico de tramitação</summary><p>Consulte a Câmara ou abra uma versão arquivada. O histórico abrange a proposição coletada, inclusive movimentos fora do intervalo usado para localizar sua autoria.</p><div className="science-actions"><button disabled={busy} onClick={()=>void load()}>{busy?'Consultando…':history?'Atualizar histórico':'Consultar histórico oficial'}</button>{history&&<button onClick={download}>Baixar histórico completo (JSON)</button>}</div><TramitationArchive recordId={recordId} activeId={history?.archive_id} onOpen={data=>{abort.current?.abort();setBusy(false);setError('');setHistory(data);setShown(50);}}/>{error&&<p role="alert">{error}{history?' O histórico abaixo é da consulta anterior.':''}</p>}{history&&<>{history.archive_id&&<p>Você está visualizando uma versão arquivada, não uma consulta atual à fonte.</p>}<p>{history.steps.length} movimentos publicados · consulta em {new Date(history.checked_at).toLocaleString('pt-BR')}. <a href={history.source} target="_blank" rel="noopener noreferrer">Fonte oficial</a></p>{!history.steps.length&&<p>Nenhum movimento retornado nesta consulta. Isso não comprova inatividade.</p>}<ol className="tramitation-timeline">{history.steps.slice(0,shown).map((s,i)=><li key={s.sequence+':'+i}><strong>{s.date?.replace('T',' às ')??'Data não informada'} · {s.organ||'Órgão não informado'}</strong><p>{s.description||'Movimento sem descrição'}{s.situation&&<> · {s.situation}</>}</p>{s.regime&&<small>Regime: {s.regime}</small>}{s.dispatch&&<p>{s.dispatch}</p>}{s.document&&<a href={s.document} target="_blank" rel="noopener noreferrer">Documento oficial</a>}</li>)}</ol>{shown<history.steps.length&&<button onClick={()=>setShown(x=>x+50)}>Mostrar mais 50 movimentos</button>}<details><summary>Integridade da resposta</summary><span className="science-hash">SHA-256: {history.source_hash}</span></details><p>Ordem por data publicada e sequência. Movimentos de tramitação não comprovam presença nem autoria individual de cada ato.</p></>}</details>;
}
