"use client";
import {useEffect,useRef,useState} from 'react';
export function ReportExport({buildDocument,filename,reportKey}:{buildDocument:(details:boolean)=>string;filename:string;reportKey:string}){
 const [details,setDetails]=useState(false),[preview,setPreview]=useState(''),[error,setError]=useState('');const previewHeading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{setPreview('');setError('');setDetails(false);},[reportKey]);
 function document(){try{setError('');return buildDocument(details);}catch(e){setError(e instanceof Error?e.message:'Não foi possível montar o relatório.');return null;}}
 function download(){const html=document();if(!html)return;const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'})),a=window.document.createElement('a');a.href=url;a.download=filename.replace(/[^a-zA-Z0-9_-]/g,'-')+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function print(){const html=document();if(!html)return;const target=window.open('','_blank');if(!target){setError('O navegador bloqueou a janela de impressão. Permita pop-ups deste portal ou baixe o HTML, abra o arquivo e use Ctrl+P.');return;}try{target.opener=null;target.document.open();target.document.write(html);target.document.close();target.focus();target.setTimeout(()=>target.print(),150);}catch{target.close();setError('Não foi possível abrir a impressão. Baixe o HTML e use Ctrl+P no arquivo.');}}
 return <section className="report-export no-print" aria-label="Relatório consolidado"><h3>Relatório consolidado</h3><p>Escolha a versão resumida ou inclua todas as linhas retornadas. O PDF utiliza a opção “Salvar como PDF” do navegador. Os mapas PNG desta análise podem ser baixados separadamente.</p><label className="electoral-checkbox"><input type="checkbox" checked={details} onChange={e=>{setDetails(e.target.checked);setPreview('');}}/> Incluir detalhamento territorial completo (pode gerar muitas páginas)</label><div className="science-actions"><button onClick={()=>{const html=document();if(html){setPreview(html);setTimeout(()=>previewHeading.current?.focus(),0);}}}>Visualizar relatório</button><button onClick={print}>Imprimir / salvar PDF</button><button onClick={download}>Baixar relatório HTML</button></div>{error&&<p role="alert">{error}</p>}{preview&&<div><h4 tabIndex={-1} ref={previewHeading}>Prévia do relatório</h4><button onClick={()=>setPreview('')}>Fechar prévia</button><iframe title="Prévia do relatório consolidado" sandbox="" srcDoc={preview} className="report-export-preview"/><p>A impressão utiliza todo o documento, sem cortar na altura desta prévia.</p></div>}</section>;
}
