"use client";
import {useState} from 'react';
import {usableSnapshot,type ArchivedAnalysis} from '@/lib/science/report-archive';
import {archiveWorkbook} from '@/lib/science/report-workbook';
import {dossierHtml,type DossierMap} from '@/lib/science/report-dossier';
import {SCIENCE_VERSION} from '@/lib/science/version';
import {ReportExport} from './ReportExport';
export function ReportDossier({selected}:{selected:ArchivedAnalysis|null}){const [items,setItems]=useState<ArchivedAnalysis[]>([]),[maps,setMaps]=useState<DossierMap[]>([]),[protocol,setProtocol]=useState(''),[caption,setCaption]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);const valid=selected?.integrity_verified===true&&usableSnapshot(selected.result_snapshot);function add(){if(!selected||!valid)return;setError('');if(items.length>=10){setError('Limite de 10 análises.');return;}setItems(p=>p.some(a=>a.id===selected.id)?p:[...p,selected]);setProtocol(selected.id);}function excel(){try{const bytes=archiveWorkbook(items);const u=URL.createObjectURL(new Blob([bytes as BlobPart],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})),a=document.createElement('a');a.href=u;a.download='IBFC-dossie.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}catch(e){setError((e as Error).message);}}
async function attach(file:File|undefined){if(!file)return;setError('');if(!items.some(a=>a.id===protocol)||maps.length>=10||file.size>5*1024*1024){setError('Escolha um protocolo do dossiê e PNG de até 5 MB. Limite: 10 mapas.');return;}const target=protocol,label=caption.trim()||file.name;setLoading(true);try{const bytes=new Uint8Array(await file.arrayBuffer());if([137,80,78,71,13,10,26,10].some((b,i)=>bytes[i]!==b))throw Error('O arquivo precisa ser PNG.');const bitmap=await createImageBitmap(file);if(bitmap.width>10000||bitmap.height>10000||bitmap.width*bitmap.height>20000000){bitmap.close();throw Error('Mapa excede o limite de 20 milhões de pixels.');}bitmap.close();const dataUrl=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).replace(/^data:[^;]+;/,'data:image/png;'));reader.onerror=()=>reject(Error('Não foi possível ler o mapa.'));reader.readAsDataURL(file);});setMaps(p=>[...p,{id:crypto.randomUUID(),protocol:target,caption:label,dataUrl}]);setCaption('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
return <section className="electoral-panel" style={{minWidth:0,overflowWrap:'anywhere'}}><h2>Montar dossiê e planilha Excel</h2><p>Abra uma análise acima e adicione ao dossiê. Até 10 protocolos, preservados individualmente, sem somar recortes sobrepostos. A seleção e as imagens ficam nesta sessão; recarregar a página limpa o dossiê.</p><button disabled={!valid||items.some(a=>a.id===selected?.id)} onClick={add}>Adicionar análise aberta ao dossiê</button>{items.map((a,i)=><p key={a.id}><b>{i+1}. {a.parameters?.new?.name??'Análise'}</b> · {a.id} <button disabled={loading} onClick={()=>{setItems(p=>p.filter(x=>x.id!==a.id));setMaps(p=>p.filter(x=>x.protocol!==a.id));if(protocol===a.id)setProtocol('');}}>Remover análise</button></p>)}{items.length>0&&<><h3>Anexar mapa PNG</h3><p>Use o PNG exportado no mapa eleitoral. A imagem será incluída no HTML/PDF. A associação é declarada por você; a imagem não integra o hash original.</p><label style={{display:'block',minWidth:0,maxWidth:'100%'}}>Protocolo do mapa <select style={{width:'100%',maxWidth:'100%',minWidth:0}} value={protocol} disabled={loading} onChange={e=>setProtocol(e.target.value)}><option value="">Selecione</option>{items.map(a=><option key={a.id} value={a.id}>{a.parameters?.new?.name??'Análise'} · {a.id}</option>)}</select></label><label>Legenda <input maxLength={300} disabled={loading} value={caption} onChange={e=>setCaption(e.target.value)}/></label><label>Mapa PNG (até 5 MB) <input type="file" accept="image/png" disabled={loading||!protocol||maps.length>=10} onChange={e=>{const file=e.target.files?.[0];e.target.value='';void attach(file);}}/></label>{loading&&<p role="status">Validando imagem…</p>}{maps.map(m=><p key={m.id}>{m.caption} · {m.protocol} <button disabled={loading} onClick={()=>setMaps(p=>p.filter(x=>x.id!==m.id))}>Remover mapa</button></p>)}<button onClick={excel}>Baixar Excel XLSX do dossiê</button><ReportExport filename="IBFC-dossie-eleitoral" reportKey={items.map(x=>x.id).join('|')+maps.map(x=>x.id).join('|')} buildDocument={details=>dossierHtml(items,maps,{details,version:SCIENCE_VERSION,exportedAt:new Date().toISOString()})}/></>}{error&&<p role="alert" className="electoral-error">{error}</p>}</section>;}
