"use client";
import Link from 'next/link';
import {useState} from 'react';
const routes=[
 {title:'Reconciliar boletins com a análise',href:'mapa',label:'Abrir análise e reconciliação de boletins',steps:['Gere a análise da candidatura ou partido no recorte desejado e abra Reconciliação de boletins.','Confira o número de boletins carregados, as seções esperadas e os avisos de cobertura. Em comparações históricas ou entre cargos, somente a seleção B é conferida.','Filtre divergências, coberturas incompletas e chaves repetidas. A diferença usa BU menos análise, sem transformar ausência em zero.','Baixe o CSV/JSON para preservar o diagnóstico completo e confira uma amostra com a origem oficial fora do portal.'],note:'É uma conferência interna da mesma base. Cargas incompletas impedem reconciliar o total; coincidência não certifica integridade e divergência não comprova fraude.'},
 {title:'Consultar onde uma candidatura recebeu votos',href:'mapa',label:'Abrir mapa e análise territorial',steps:['Selecione UF, cargo, turno e candidatura ou partido. Para analisar apenas o ano atual, deixe a comparação anterior sem seleção.','Gere a análise. Confira a granularidade: dados por zona não identificam votação por escola, seção ou urna.','No mapa multicamadas, combine todas as zonas, zonas com votação e locais cadastrados. Use a busca para encontrar um território.','Consulte a tabela e a cobertura: coordenadas ausentes não removem os votos do relatório.'],note:'Círculos são referências de localização, não limites oficiais de zonas. Votos de uma zona não são distribuídos automaticamente entre escolas.'},
 {title:'Comparar candidaturas ou partidos',href:'comparacao',label:'Abrir comparação múltipla',steps:['Escolha o mesmo ano, UF, cargo, turno, tipo e recorte territorial.','Selecione de duas a dez candidaturas ou partidos e clique em Comparar seleções.','Confira os totais e os denominadores antes de comparar percentuais. Os mapas lado a lado usam uma escala comum.','No Relatório consolidado, escolha versão resumida ou detalhamento completo e visualize antes de imprimir.'],note:'A comparação considera apenas as seleções escolhidas. Os totais vêm do recorte consultado, mesmo quando a tabela retornada é limitada.'},
 {title:'Analisar mudanças entre 2022 e 2026',href:'mapa',label:'Abrir análise territorial histórica',steps:['Selecione as candidaturas de 2022 e 2026 no mesmo cargo, UF, turno e tipo.','Gere a análise e consulte o Diagnóstico territorial para verificar cobertura, chaves comuns e mudanças registradas.','Carregue os mapas históricos para consultar cada ano com coordenadas e protocolos próprios.','Exporte o diagnóstico CSV/JSON ou use o relatório para impressão. A busca da tela não restringe o detalhamento exportado.'],note:'Escolher duas candidaturas não certifica identidade ou continuidade do eleitorado. Ausência em um ano não comprova zero voto ou extinção do território.'},
 {title:'Exportar mapas e relatórios',href:'comparacao',label:'Abrir comparações e exportações',steps:['Ajuste o zoom, as camadas e a seleção antes de usar Baixar mapa PNG.','Se as ruas não carregarem ou o provedor bloquear a exportação, desmarque Incluir mapa de ruas.','Para PDF, clique em Imprimir / salvar PDF e selecione Salvar como PDF no navegador.','Se a janela for bloqueada, baixe o relatório HTML, abra o arquivo e use a opção Imprimir. CSV/JSON continuam disponíveis para processamento.'],note:'O PNG registra a vista atual. O relatório HTML/PDF não incorpora os mapas automaticamente. Protocolos e hashes identificam os relatórios originais.'},
 {title:'Conferir sincronização e fontes',href:'integracoes',label:'Abrir integrações e sincronização',steps:['Confira o estado da tarefa, o horário da última atualização e os registros processados.','Uma tarefa na fila ainda não está importando. Consulte a execução do worker quando não houver progresso.','Após a conclusão, gere uma análise e compare uma amostra com a fonte oficial correspondente.','Consulte fontes, protocolos e cobertura antes de interpretar ausência de votos ou coordenadas.'],note:'Não há percentual preciso quando o total de arquivos é desconhecido. Este guia não instala migrações nem configura credenciais.'}
];
const questions=[['Não aparecem votos da candidatura','O catálogo pode ter candidaturas sem resultados importados. Confira ano, cargo, turno e recorte, depois a tarefa de importação. Ausência não significa zero.'],['Por que alguns pontos não aparecem no mapa?','A tabela pode conter resultados sem coordenadas válidas. Consulte a cobertura. O sistema não inventa endereços ou posições de urnas.'],['Por que os percentuais não são comparáveis?','Fontes, granularidade ou denominadores podem ser diferentes. Consulte a indicação de compatibilidade; votos de cargos distintos podem ter bases distintas.'],['Como abrir o PDF?','O botão abre a impressão do navegador: escolha Salvar como PDF. Se bloqueado, use o HTML offline.'],['Os números identificam quem votou em quem?','Não. Resultados públicos agregados e participação voluntária são conjuntos separados. Crescimento de votação não identifica fidelidade individual.']];
export function ScienceGuide(){const [search,setSearch]=useState('');const normalized=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const matches=(s:string)=>normalized(s).includes(normalized(search.trim()));const guides=routes.filter(r=>matches([r.title,...r.steps,r.note].join(' '))),faq=questions.filter(q=>matches(q.join(' ')));return <><header className="science-hero"><span className="electoral-eyebrow">GUIA OPERACIONAL</span><h1>Como usar Ciência Eleitoral</h1><p>Roteiros para consultar resultados, verificar cobertura e produzir documentos a partir das análises disponíveis.</p></header><section className="electoral-panel"><label>Buscar no guia<input type="search" aria-label="Buscar no guia" maxLength={120} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Mapa, votos, PDF, sincronização…"/></label><p>{guides.length} roteiros e {faq.length} respostas encontrados.</p>{search&&<button onClick={()=>setSearch('')}>Limpar busca</button>}</section>{guides.map(r=><section className="electoral-panel" key={r.title}><h2>{r.title}</h2><ol>{r.steps.map(step=><li key={step}>{step}</li>)}</ol><p className="electoral-notice">{r.note}</p><Link href={'/admin/ciencia-eleitoral/'+r.href}>{r.label} →</Link></section>)}{faq.length>0&&<section className="electoral-panel"><h2>Dúvidas frequentes</h2>{faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>}{!guides.length&&!faq.length&&<section className="electoral-panel"><p>Nenhum resultado. Tente outro termo ou limpe a busca.</p></section>}</>;}
