'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import type {ScienceCatalogue,ScienceReport,ScienceRow,Target} from '@/lib/science/types';
import {STATES,SCOPES,OFFICES} from '@/lib/science/territory';
import {association,validateBaseline} from '@/lib/science/statistics';
import {csvCell,number,percentage} from '@/lib/electoral/analysis';
import {LeafletElectionMap} from '@/components/electoral/LeafletElectionMap';
import {candidateKey,type ElectionCandidate,type LocalComparison} from '@/lib/electoral/types';
const empty:ScienceCatalogue={candidates:[],parties:[],municipalities:[],zones:[],locations:[],coverage:[]};
export function ScienceExplorer({models=false,cross=false}:{models?:boolean;cross?:boolean}){
 const restore=useRef<{old:Target;new:Target}|null>(null);
 const [pendingDrill,setPendingDrill]=useState(false);
 const [uf,setUf]=useState('DF'),[scope,setScope]=useState<keyof typeof SCOPES>('state'),[office,setOffice]=useState(1),[turn,setTurn]=useState(1),[kind,setKind]=useState<'candidate'|'party'|'group'>('candidate');
 const [leftKind,setLeftKind]=useState<'candidate'|'party'|'group'>('candidate');
 const [year,setYear]=useState(2026),[leftOffice,setLeftOffice]=useState(1);
 const oldYear=cross?year:2022,newYear=cross?year:2026;
 const labelA=cross?`${OFFICES[leftOffice]} · ${year}`:'2022',labelB=cross?`${OFFICES[office]} · ${year}`:'2026';
 const [catalogue,setCatalogue]=useState(empty),[oldId,setOldId]=useState(''),[newId,setNewId]=useState(''),[oldGroup,setOldGroup]=useState<string[]>([]),[newGroup,setNewGroup]=useState<string[]>([]),[groupName,setGroupName]=useState('Grupo de partidos'),[groupSource,setGroupSource]=useState('');
 const [municipality,setMunicipality]=useState(''),[zone,setZone]=useState(''),[local,setLocal]=useState(''),[section,setSection]=useState('');
 const [report,setReport]=useState<ScienceReport|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[catalogueLoading,setCatalogueLoading]=useState(false),[sort,setSort]=useState('name'),[commonOnly,setCommonOnly]=useState(false),[swing,setSwing]=useState(0),[selected,setSelected]=useState('');
 const load=useCallback(async(signal?:AbortSignal)=>{setCatalogueLoading(true);setError('');try{const r=await fetch(`/api/admin/science?uf=${uf}`,{cache:'no-store',signal});const d=await r.json();if(!r.ok)throw Error(d.error);setCatalogue(d);if(restore.current){const saved=restore.current;for(const side of ['old','new'] as const){const t=saved[side];const values=t.kind==='candidate'?d.candidates:d.parties;if(t.kind==='group'){const allowed=values.filter((x:ElectionCandidate)=>x.year===t.year&&x.office===t.office&&x.turn===t.turn).map((x:ElectionCandidate)=>x.number);(side==='old'?setOldGroup:setNewGroup)((t.numbers??[]).filter(n=>allowed.includes(n)));continue;}const match=values.find((x:ElectionCandidate)=>x.number===t.number&&x.year===t.year&&x.office===t.office&&x.turn===t.turn);if(match)(side==='old'?setOldId:setNewId)(candidateKey(match));}restore.current=null;}}catch(e){if(signal?.aborted)return;setError(e instanceof Error?e.message:'Falha ao carregar catálogo.');setCatalogue(empty);}finally{if(!signal?.aborted)setCatalogueLoading(false);}},[uf]);
 useEffect(()=>{const c=new AbortController();setCatalogue(empty);setReport(null);setOldId('');setNewId('');setOldGroup([]);setNewGroup([]);void load(c.signal);return()=>c.abort();},[load]);
 useEffect(()=>{setReport(null);setOldId('');setNewId('');setOldGroup([]);setNewGroup([]);},[office,leftOffice,year,turn,kind,leftKind]);
 const list=kind==='candidate'?catalogue.candidates:catalogue.parties;
 const options=(year:number,code=office,source=list)=>source.filter(x=>x.year===year&&x.office===code&&x.turn===turn);
 const oldOptions=options(oldYear,cross?leftOffice:office,cross?(leftKind==='candidate'?catalogue.candidates:catalogue.parties):list),newOptions=options(newYear);
 const target=(side:'old'|'new'):Target|undefined=>{
  const rows=side==='old'?oldOptions:newOptions,id=side==='old'?oldId:newId,numbers=side==='old'?oldGroup:newGroup;
  const selectionKind=side==='old'&&cross?leftKind:kind;
  if(selectionKind==='group'){const base=rows.find(x=>numbers.includes(x.number));return base?{...base,kind:'group',numbers,name:groupName,source_url:groupSource}:undefined;}
  const c=rows.find(x=>candidateKey(x)===id);return c?{...c,kind:selectionKind}:undefined;
 };
 async function analyze(){setLoading(true);setError('');setReport(null);try{const old=target('old'),newer=target('new');if(!old||!newer)throw Error('Escolha a candidatura/partido de cada ano ou os partidos do grupo.');if((cross?leftKind:kind)==='group'&&oldGroup.some(n=>oldOptions.find(x=>x.number===n)?.election!==old.election)||kind==='group'&&newGroup.some(n=>newOptions.find(x=>x.number===n)?.election!==newer.election))throw Error('Os partidos devem pertencer à mesma eleição em cada ano.');const filters:Record<string,number|boolean>={common_only:commonOnly};if(municipality)filters.municipality=Number(municipality);if(zone)filters.zone=Number(zone);if(local)filters.local=Number(local);if(section)filters.section=Number(section);const r=await fetch('/api/admin/science',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:cross?'cross':'historical',old,new:newer,scope,filters})});const d=await r.json();if(!r.ok)throw Error(d.error);setReport(d);}catch(e){setError(e instanceof Error?e.message:'Falha na análise.');}finally{setLoading(false);}}
 const points=(r:ScienceRow)=>r.old_valid&&r.new_valid&&r.old_votes!==null&&r.new_votes!==null?r.new_votes/r.new_valid*100-r.old_votes/r.old_valid*100:null;
 const rows=useMemo(()=>[...(report?.rows??[])].sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):(points(b)??-Infinity)-(points(a)??-Infinity)),[report,sort]);
 const places=useMemo<LocalComparison[]>(()=>rows.map(r=>({...r,address:r.address??'',sections:[r],old_label:labelA,new_label:labelB})),[rows,labelA,labelB]);
 const choose=useCallback((key:string)=>setSelected(key),[]);
 const stats=report?association(report.rows):null,validation=report&&!report.truncated?validateBaseline(report.rows):null;
 const totals=report?.totals;
 const share=(votes:number|null|undefined,valid:number|null|undefined)=>votes!=null&&valid?100*votes/valid:null;
 const oldShare=share(totals?.old_votes,totals?.old_valid),newShare=share(totals?.new_votes,totals?.new_valid);
 function exportCsv(){if(!report)return;const lines=[['Território','UF','Município','Zona','Local','Seção',`Votos ${labelA}`,`Votos ${labelB}`,`Válidos ${labelA}`,`Válidos ${labelB}`,'Variação pp','Seções comuns','Seções mudadas'],...rows.map(r=>[r.name,r.uf,r.municipality,r.zone,r.local,r.section,r.old_votes,r.new_votes,r.old_valid,r.new_valid,points(r),r.common_sections,r.moved_sections])].map(row=>row.map(csvCell).join(';'));
  lines.push('',...[["Gerado em",report.generated_at],['Protocolo',report.analysis_id??''],['SHA-256 do resultado',report.result_sha256??''],['Escopo',scope],['Somente seções comuns',String(commonOnly)],['Grupo manual',kind==='group'?groupName:''],['Fonte do grupo',groupSource],['Cobertura 2026',report.coverage.join(',')],['Linhas exportadas / disponíveis',`${rows.length}/${report.total_rows}`],['Comparação','Resultados públicos agregados; não identifica votos individuais.'],...report.sources.map(x=>['Fonte '+x.year,x.filename,x.source_url,x.finished_at])].map(row=>row.map(csvCell).join(';')));
  const url=URL.createObjectURL(new Blob(['\uFEFF'+lines.join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`IBFC-${scope}-${uf}-${oldYear}-${newYear}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
 }
 function drill(r:ScienceRow){setPendingDrill(true);setReport(null);setSection('');if(scope==='country'){const old=target('old'),newer=target('new');if(old&&newer)restore.current={old,new:newer};setUf(r.uf);setScope('state');setMunicipality('');setZone('');setLocal('');}else if(scope==='state'){setMunicipality(String(r.municipality));setScope('municipality');setZone('');setLocal('');}else if(scope==='municipality'){setZone(String(r.zone));setLocal('');setScope('zone');}else if(scope==='zone'){setMunicipality(String(r.municipality));setZone(String(r.zone));setLocal(String(r.local));setScope('location');}else{setSection(String(r.section));setScope('section');}setSelected('');}
 function selectScope(value:keyof typeof SCOPES){setPendingDrill(false);restore.current=null;setScope(value);setReport(null);setMunicipality('');setZone('');setLocal('');setSection('');if(value==='country'){setUf('BR');setOffice(1);}else if(uf==='BR')setUf('DF');}
 useEffect(()=>{if(pendingDrill&&!catalogueLoading&&!loading&&target('old')&&target('new')){setPendingDrill(false);void analyze();}},[pendingDrill,catalogueLoading,loading,scope,municipality,zone,local,section,oldId,newId]);
 function back(value:keyof typeof SCOPES){setPendingDrill(false);setScope(value);setReport(null);if(value==='state'){setMunicipality('');setZone('');setLocal('');setSection('');}else if(value==='municipality'){setZone('');setLocal('');setSection('');}else if(value==='zone'){setLocal('');setSection('');}else if(value==='location'){setSection('');}}
 function optionSelect(label:string,year:number,values:ElectionCandidate[],value:string,setValue:(s:string)=>void){return <label>{label}<select aria-label={label} value={value} disabled={catalogueLoading} onChange={e=>{setValue(e.target.value);setReport(null);}}><option value="">Selecione {year}</option>{values.map(x=><option key={candidateKey(x)} value={candidateKey(x)}>{x.number} · {x.name} · eleição {x.election}</option>)}</select></label>;}
 return <><header className="science-hero"><span className="electoral-eyebrow">{cross?'COMPARAÇÃO ENTRE CARGOS':models?'LABORATÓRIO ESTATÍSTICO':'EXPLORADOR TERRITORIAL'}</span><h1>{cross?'Comparação entre cargos':models?'Estatística e cenários':'Mapa eleitoral'}</h1><p>{cross?'Compare cargos no mesmo ano, UF e turno, com denominadores próprios.':'Compare 2022 e 2026 com denominadores, fontes e cobertura.'} {models?'Escolha um recorte para avaliar a associação e a validação exploratória.':'Aprofunde a análise do país à seção.'}</p></header>
 <nav className="science-breadcrumb no-print" aria-label="Recorte territorial"><span>{uf==='BR'?'Brasil':STATES[uf]}</span>{uf!=='BR'&&<button onClick={()=>back('state')}>UF</button>}{municipality&&<button onClick={()=>back('municipality')}>{catalogue.municipalities.find(x=>String(x.municipality)===municipality)?.name??municipality}</button>}{zone&&<button onClick={()=>back('zone')}>Zona {zone}</button>}{local&&<button onClick={()=>back('location')}>Local {local}</button>}{section&&<span>Seção {section}</span>}</nav>
 <section className="electoral-panel no-print"><div className="science-filters">
 <label>Escopo<select aria-label="Escopo" value={scope} onChange={e=>selectScope(e.target.value as keyof typeof SCOPES)}>{Object.entries(SCOPES).filter(([key])=>!cross||key!=='country').map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label>
 <label>UF<select aria-label="UF" value={uf} disabled={scope==='country'} onChange={e=>{setUf(e.target.value);setMunicipality('');setZone('');setLocal('');setSection('');}}>{scope==='country'&&<option value="BR">Brasil · presidente</option>}{Object.entries(STATES).map(([key,label])=><option key={key} value={key}>{key} · {label}</option>)}</select></label>
 <label>{cross?"Cargo B":"Cargo"}<select aria-label="Cargo" value={office} disabled={uf==='BR'} onChange={e=>setOffice(Number(e.target.value))}>{Object.entries(OFFICES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
 {cross&&<><label>Ano<select aria-label="Ano" value={year} onChange={e=>setYear(Number(e.target.value))}><option>2026</option><option>2022</option></select></label><label>Cargo A<select aria-label="Cargo A" value={leftOffice} onChange={e=>setLeftOffice(Number(e.target.value))}>{Object.entries(OFFICES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></>}
 <label>Turno<select aria-label="Turno" value={turn} onChange={e=>setTurn(Number(e.target.value))}><option value={1}>1º turno</option><option value={2}>2º turno</option></select></label>
 {cross&&<label>Analisar no cargo A<select aria-label="Analisar no cargo A" value={leftKind} onChange={e=>setLeftKind(e.target.value as typeof leftKind)}><option value="candidate">Candidatura</option><option value="party">Partido</option><option value="group">Coligação / grupo manual</option></select></label>}
 <label>{cross?'Analisar no cargo B':'Analisar'}<select aria-label="Analisar" value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="candidate">Candidatura</option><option value="party">Partido · nominal + legenda</option><option value="group">Coligação / grupo manual de partidos</option></select></label>
 {scope!=='country'&&scope!=='state'&&<label>Município<select aria-label="Município" value={municipality} onChange={e=>{setMunicipality(e.target.value);setZone('');setLocal('');setSection('');setReport(null);}}><option value="">Selecione</option>{catalogue.municipalities.map(x=><option key={x.municipality} value={x.municipality}>{x.name}</option>)}</select></label>}
 {['zone','location','section'].includes(scope)&&<label>Zona<select aria-label="Zona" value={zone} onChange={e=>{setZone(e.target.value);setLocal('');setSection('');setReport(null);}}><option value="">Selecione</option>{catalogue.zones.filter(x=>String(x.municipality)===municipality).map(x=><option key={x.zone} value={x.zone}>{x.zone}</option>)}</select></label>}
 {['location','section'].includes(scope)&&<label>Local<select aria-label="Local" value={local} onChange={e=>{setLocal(e.target.value);setSection('');setReport(null);}}><option value="">Selecione</option>{catalogue.locations.filter(x=>String(x.municipality)===municipality&&String(x.zone)===zone).map(x=><option key={x.local} value={x.local}>{x.name}</option>)}</select></label>}
 {scope==='section'&&<label>Seção<input type="number" min={1} value={section} onChange={e=>{setSection(e.target.value);setReport(null);}}/></label>}
 {['old','new'].map(side=>{const isOld=side==='old',selectionKind=isOld&&cross?leftKind:kind,values=isOld?oldOptions:newOptions,current=isOld?oldGroup:newGroup;
 return <div key={side}>{selectionKind==='group'?<fieldset><legend>Partidos {isOld?labelA:labelB}</legend>{values.map(x=><label className="electoral-checkbox" key={candidateKey(x)}><input type="checkbox" checked={current.includes(x.number)} onChange={e=>{(isOld?setOldGroup:setNewGroup)(s=>e.target.checked?[...s,x.number]:s.filter(n=>n!==x.number));setReport(null);}}/>{x.number} · {x.name}</label>)}</fieldset>:optionSelect(cross?(isOld?'Seleção A':'Seleção B'):(isOld?'Comparação 2022':'Seleção 2026'),isOld?oldYear:newYear,values,isOld?oldId:newId,isOld?setOldId:setNewId)}</div>;})}
 {(kind==='group'||(cross&&leftKind==='group'))&&<><label>Nome da coligação / grupo<input value={groupName} onChange={e=>{setGroupName(e.target.value);setReport(null);}} maxLength={150}/></label><label>Fonte da composição (opcional)<input value={groupSource} onChange={e=>{setGroupSource(e.target.value);setReport(null);}} placeholder="URL / documento oficial" maxLength={1000}/></label></>}

 </div><label className="electoral-checkbox"><input type="checkbox" checked={commonOnly} onChange={e=>{setCommonOnly(e.target.checked);setReport(null);}}/>Comparar somente chaves de seção presentes {cross?"nos dois cargos":"nos dois anos"}</label><div className="science-actions"><button className="electoral-primary" disabled={loading||catalogueLoading} onClick={()=>void analyze()}>{loading?'Calculando…':'Gerar análise'}</button><button disabled={catalogueLoading} onClick={()=>void load()}>Atualizar catálogo</button></div>
 <p className="electoral-caption">{catalogueLoading?'Carregando catálogo…':`${oldOptions.length} opções em ${labelA} · ${newOptions.length} em ${labelB}. Sem opções? Sincronize as UFs e confira ano, cargo e turno.`} {(kind==='group'||(cross&&leftKind==='group'))&&'Composição definida pelo analista; não certifica uma coligação ou federação oficial.'}</p>
 </section>{error&&<p className="electoral-notice electoral-error" role="alert">{error}</p>}
 {report&&<><section className="science-kpis"><article><small>{labelA} · votos</small><strong>{number(totals?.old_votes??null)}</strong><span>{percentage(oldShare)} dos votos válidos</span></article><article><small>{labelB} · votos</small><strong>{number(totals?.new_votes??null)}</strong><span>{percentage(newShare)} dos votos válidos</span></article><article><small>{cross?"Diferença entre cargos":"Variação da participação"}</small><strong>{oldShare!==null&&newShare!==null?`${(newShare-oldShare).toFixed(2)} pp`:'Sem comparação'}</strong><span>{totals?.common_sections??0} seções com chave comum</span></article></section>
 <section className="electoral-panel"><h2>Cobertura e método</h2><p>{scope==='country'?'UFs importadas':'UF consultada'} no recorte B: {report.coverage.join(', ')||'nenhuma'}. {number(totals?.old_sections??0)} seções em {labelA} / {number(totals?.new_sections??0)} em 2026. {number(totals?.moved_sections??0)} mudaram de local na chave comparada.</p><p>Participação = votos selecionados ÷ votos válidos do cargo. Em eleições com dois votos para senador, votos válidos não equivalem a número de eleitores. A chave da seção não comprova continuidade do eleitorado. {cross&&"A diferença entre cargos não mede transferência ou fidelidade. Em 2026 são até dois votos para senador; em 2022, um. Os percentuais usam votos válidos de cada cargo."}</p>{report.truncated&&<p className="electoral-notice">Tabela limitada a 5.000 de {report.total_rows} territórios. Totais cobrem todo o filtro; mapa e exportação cobrem somente as linhas exibidas. Aprofunde o recorte.</p>}<p className="electoral-caption">Protocolo de análise: {report.analysis_id}. SHA-256 do resultado: <span style={{overflowWrap:'anywhere'}}>{report.result_sha256}</span>.</p><p className="electoral-caption">Gerado em {new Date(report.generated_at).toLocaleString('pt-BR')}. Resultados agregados não identificam quem votou em quem.</p></section>
 {!models&&<><p className="electoral-caption">Pontos de UF/município são médias das coordenadas disponíveis das seções; não representam limites geográficos oficiais. Seções sem coordenadas permanecem na tabela.</p><LeafletElectionMap places={places} onSelect={choose}/></>}
 {models&&<section className="electoral-panel"><h2>Associação e validação exploratória</h2><p>Correlação das participações territoriais: {stats?.r==null?'não calculável':stats.r.toFixed(3)} · {stats?.n} pares. Correlação não identifica transferência de voto nem causalidade.</p>{validation?<><p>Regressão linear · 5 grupos alternados de territórios, com treino e teste separados. {validation.n} territórios.</p><div className="science-kpis"><article><small>Erro médio absoluto</small><strong>{validation.mae.toFixed(2)} pp</strong></article><article><small>RMSE do modelo</small><strong>{validation.rmse.toFixed(2)} pp</strong></article><article><small>RMSE da média de treino</small><strong>{validation.baselineRmse.toFixed(2)} pp</strong></article></div><p>Melhoria relativa de erro quadrático: {validation.skill==null?'não calculável':percentage(validation.skill*100)}. Valor negativo significa pior desempenho que a média.</p></>:<p>São necessários pelo menos 15 territórios com dados nos dois anos, denominadores positivos e relatório sem truncamento.</p>}<p className="electoral-notice">Este teste estima associação espacial entre dois resultados conhecidos. Não valida previsão de eleição futura. Dependência entre territórios pode tornar o erro otimista; validação temporal e geográfica independente será necessária.</p><h3>Cenário hipotético</h3><label>Alteração uniforme da participação: {swing} pp<input type="range" min={-10} max={10} step={0.5} value={swing} onChange={e=>setSwing(Number(e.target.value))}/></label><p>Aplicando a hipótese ao total válido de 2026: {newShare==null?'sem dados':number(Math.round(Math.max(0,Math.min(100,newShare+swing))/100*(totals?.new_valid??0)))} votos selecionados. Mantém o denominador fixo; não é previsão nem projeção de pessoas.</p></section>}
 <section className="electoral-panel"><div className="science-actions no-print"><label>Ordenar<select value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Território</option><option value="points">Maior crescimento em pp</option></select></label><button onClick={exportCsv}>Baixar CSV</button><button onClick={()=>window.print()}>Imprimir / salvar PDF</button></div><div className="science-table"><table><thead><tr><th>Território</th><th>{labelA}</th><th>{labelB}</th><th>Variação pp</th><th>Seções</th><th className="no-print">Explorar</th></tr></thead><tbody>{rows.map(r=><tr key={r.key} className={selected===r.key?'selected':''}><td>{r.name}<small>{r.uf}{scope!=='country'?` · município ${r.municipality}`:''}{scope!=='country'&&scope!=='state'?` · zona ${r.zone}`:''}</small></td><td>{number(r.old_votes)}</td><td>{number(r.new_votes)}</td><td>{points(r)==null?'Sem comparação':points(r)!.toFixed(2)}</td><td>{r.section_count}</td><td className="no-print"><button disabled={scope==='section'||loading} onClick={()=>drill(r)}>{scope==='section'?'Último nível':'Aprofundar →'}</button></td></tr>)}</tbody></table></div>{!rows.length&&<p>Nenhum resultado disponível neste recorte.</p>}</section><section className="electoral-panel"><h2>Fontes da análise</h2>{report.sources.map((x,i)=><p key={i}><a href={x.source_url} target="_blank" rel="noopener noreferrer">{x.year} · {x.filename}</a><br/><small>Importado em {new Date(x.finished_at).toLocaleString('pt-BR')}</small></p>)}</section></>}
 </>;
}
