'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {STATES,OFFICES} from '@/lib/science/territory';
import {candidateKey} from '@/lib/electoral/types';
import type {ScienceCatalogue,ScienceReport,Target} from '@/lib/science/types';
import type {TemporalResult} from '@/lib/science/temporal-models';
import {TemporalResults} from './TemporalResults';
type Report=ScienceReport&{temporal:TemporalResult};
const blank:ScienceCatalogue={candidates:[],parties:[],municipalities:[],zones:[],locations:[],coverage:[]};
export function TemporalModels(){
 const [uf,setUf]=useState('DF'),[office,setOffice]=useState(1),[turn,setTurn]=useState(1),[kind,setKind]=useState<'candidate'|'party'>('candidate'),[years,setYears]=useState([2014,2018,2022]),[scope,setScope]=useState('state'),[municipality,setMunicipality]=useState(''),[ids,setIds]=useState<Record<number,string>>({}),[confirmed,setConfirmed]=useState(false);
 const [catalogue,setCatalogue]=useState(blank),[report,setReport]=useState<Report|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[catalogueLoading,setCatalogueLoading]=useState(false),[reload,setReload]=useState(0);
 useEffect(()=>{const c=new AbortController();setCatalogue(blank);setCatalogueLoading(true);setError('');fetch('/api/admin/science?uf='+uf,{cache:'no-store',signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setCatalogue(d);}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setCatalogueLoading(false);});return()=>c.abort();},[uf,reload]);
 useEffect(()=>{setIds({});setConfirmed(false);setReport(null);},[uf,office,turn,kind,years,reload]);
 useEffect(()=>{setConfirmed(false);setReport(null);},[scope,municipality]);
 useEffect(()=>{setMunicipality('');},[uf]);
 const list=kind==='candidate'?catalogue.candidates:catalogue.parties;
 const options=(year:number)=>list.filter(c=>c.year===year&&c.office===office&&c.turn===turn);
 async function analyze(){setLoading(true);setError('');setReport(null);try{const targets=years.map(year=>{const t=options(year).find(c=>candidateKey(c)===ids[year]);if(!t)throw Error('Escolha uma seleção em cada ano.');return {...t,kind} as Target;});const r=await fetch('/api/admin/science/temporal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({targets,scope,filters:municipality?{municipality:Number(municipality)}:{},correspondence_confirmed:confirmed})});const d=await r.json();if(!r.ok)throw Error(d.error);setReport(d);}catch(e){setError(e instanceof Error?e.message:'Falha na análise.');}finally{setLoading(false);}}
 function download(){if(!report)return;const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='IBFC-serie-temporal-'+report.analysis_id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <><header className="science-hero"><span className="electoral-eyebrow">HISTÓRICO · TESTE CRONOLÓGICO · PROTOCOLO</span><h1>Séries históricas e validação temporal</h1><p>Compare persistência e tendência linear usando apenas resultados públicos agregados de eleições anteriores ao ano de teste.</p></header><section className="electoral-panel no-print"><h2>Montar série</h2><p>Importe os votos de cada ano em <Link href="/admin/ciencia-eleitoral/integracoes">Integrações e sincronização</Link>. O painel requer três ou quatro eleições consecutivas e resultados por seção publicados. Uma candidatura sem votos importados permanece indisponível.</p><div className="science-filters">
 <label>UF<select disabled={loading} value={uf} onChange={e=>setUf(e.target.value)}>{Object.entries(STATES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 <label>Cargo<select aria-label="Cargo" disabled={loading} value={office} onChange={e=>setOffice(Number(e.target.value))}>{Object.entries(OFFICES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 <label>Turno<select disabled={loading} value={turn} onChange={e=>setTurn(Number(e.target.value))}><option value={1}>Primeiro turno</option><option value={2}>Segundo turno</option></select></label>
 <label>Tipo de série<select disabled={loading} value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="candidate">Candidatura</option><option value="party">Partido</option></select></label>
 <label>Janela histórica<select disabled={loading} value={years.join(',')} onChange={e=>setYears(e.target.value.split(',').map(Number))}><option value="2014,2018,2022">2014 → 2018 → 2022</option><option value="2018,2022,2026">2018 → 2022 → 2026</option><option value="2014,2018,2022,2026">2014 → 2018 → 2022 → 2026</option></select></label>
 <label>Unidade de análise<select disabled={loading} value={scope} onChange={e=>setScope(e.target.value)}><option value="state">Municípios da UF</option><option value="municipality">Zonas de um município</option></select></label>
 <label>Município{scope==='state'?' (opcional)':''}<select disabled={loading||catalogueLoading} value={municipality} onChange={e=>setMunicipality(e.target.value)}><option value="">{scope==='state'?'Todos os municípios':'Selecione'}</option>{catalogue.municipalities.map(m=><option key={m.uf+':'+m.municipality} value={m.municipality}>{m.name}</option>)}</select></label>
 </div><div className="science-filters">{years.map(year=><label key={year}>{kind==='candidate'?'Candidatura':'Partido'} · {year}<select aria-label={`${kind==='candidate'?'Candidatura':'Partido'} · ${year}`} disabled={loading||catalogueLoading} value={ids[year]??''} onChange={e=>{setIds({...ids,[year]:e.target.value});setConfirmed(false);setReport(null);}}><option value="">{catalogueLoading?'Carregando catálogo…':'Selecione'}</option>{options(year).map(c=><option key={candidateKey(c)} value={candidateKey(c)} disabled={c.results_available===false||c.result_granularity==='zone'}>{c.number} · {c.name} · eleição {c.election}{c.results_available===false?' · sem votos':c.result_granularity==='zone'?' · somente zona':''}</option>)}</select>{!catalogueLoading&&!options(year).length&&<small>Nenhum resultado deste recorte foi importado para {year}.</small>}</label>)}</div>
 <label className="electoral-checkbox"><input type="checkbox" disabled={loading} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Revisei a correspondência das seleções entre os anos, inclusive mudanças de número, partido e candidatura. Os códigos territoriais não garantem limites geográficos idênticos.</label>
 <div className="science-actions"><button className="electoral-primary" disabled={loading||catalogueLoading||!confirmed||years.some(y=>!ids[y])||(scope==='municipality'&&!municipality)} onClick={()=>void analyze()}>{loading?'Calculando e registrando…':'Gerar validação temporal'}</button><button disabled={loading||catalogueLoading} onClick={()=>setReload(reload+1)}>Atualizar catálogo</button></div></section>
 {error&&<p role="alert" className="electoral-error">{error}</p>}{report&&<><section className="electoral-panel"><h2>Protocolo da série</h2><p>{report.analysis_id} · {new Date(report.generated_at).toLocaleString('pt-BR')}</p><p className="science-hash">SHA-256: {report.result_sha256}</p><div className="science-actions no-print"><button onClick={download}>Baixar protocolo JSON</button><button onClick={()=>window.print()}>Imprimir / salvar PDF</button></div></section><TemporalResults result={report.temporal}/><section className="electoral-panel"><h2>Origem dos dados</h2>{report.sources.map((s,i)=><p key={i}><a href={s.source_url}>{s.year} · {s.filename}</a> · {s.finished_at?new Date(s.finished_at).toLocaleString('pt-BR'):'data indisponível'}</p>)}</section></>}
 </>;
}
