'use client';
import {useEffect,useRef,useState} from 'react';
type File={name:string;type:string;status:string;hash:string;received_at:string;url:string};
export function UrnaDocuments({uf,election,municipality,zone}:{uf:string;election:number|undefined;municipality:string;zone:string}){
 const [sections,setSections]=useState<{ns:string;nsp?:string;nsa?:string[]}[]>([]),[section,setSection]=useState(''),[files,setFiles]=useState<File[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false),[status,setStatus]=useState('');
 const epoch=useRef(0);
 const ready=uf!=='BR'&&!!election&&!!municipality&&!!zone;
 useEffect(()=>{epoch.current++;setLoading(false);setSections([]);setSection('');setFiles([]);setError('');setStatus('');},[uf,election,municipality,zone]);
 async function load(sn?:string){const version=epoch.current;setLoading(true);setError('');setFiles([]);try{const query=new URLSearchParams({uf,election:String(election),municipality,zone});if(sn)query.set('section',sn);const r=await fetch('/api/admin/science/urnas?'+query,{cache:'no-store'});const d=await r.json();if(version!==epoch.current)return;if(!r.ok)throw Error(d.error);setSections(d.sections);setFiles(d.files??[]);setStatus(d.status);}catch(e){if(version!==epoch.current)return;setError(e instanceof Error?e.message:'Falha na consulta.');}finally{if(version===epoch.current)setLoading(false);}}
 return <section className="electoral-panel"><h2>Arquivos de urna · TSE 2026</h2><p>Selecione candidatura, município e zona nos filtros. Consulte o inventário oficial e escolha uma seção para acessar Boletim de Urna, RDV e log disponíveis.</p><div className="science-actions"><button disabled={!ready||loading} onClick={()=>void load()}>{loading?'Consultando TSE…':'Consultar seções da zona'}</button>{!!sections.length&&<label>Seção eleitoral<select aria-label="Seção eleitoral" value={section} onChange={e=>{setSection(e.target.value);setFiles([]);setStatus('');}}><option value="">Selecione</option>{sections.map(s=><option key={s.ns} value={s.ns}>{s.ns}{s.nsp?' · principal '+s.nsp:''}{s.nsa?.length?' · agregadas '+s.nsa.join(', '):''}</option>)}</select></label>}<button disabled={!ready||!section||loading} onClick={()=>void load(section)}>Consultar BU, RDV e log</button></div>{error&&<p role="alert">{error}</p>}{status&&<p>Situação informada pelo TSE: {status}</p>}{files.map(f=><p key={f.url} style={{overflowWrap:'anywhere'}}><a href={f.url} target="_blank" rel="noopener noreferrer">{f.type} · {f.name}</a><br/><small>{f.status} · recebido em {f.received_at} · hash {f.hash}</small></p>)}<p className="electoral-caption">Arquivos abrem diretamente no servidor oficial. BUs podem exigir leitor específico; esta consulta não decodifica nem soma automaticamente votos do BU. Os totais desta análise vêm do JSON por zona, do CSV por seção ou do CSV oficial dos Boletins de Urna; a fonte utilizada aparece no relatório. Versões retransmitidas são exibidas com seus status, sem escolher arbitrariamente um hash.</p></section>;
}
