'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import type {Target} from '@/lib/science/types';
import type {LocalComparison} from '@/lib/electoral/types';
import {filterZoneLayer,type ZoneMapData,zoneMarkerColor} from '@/lib/science/map-layers';
import {LeafletElectionMap} from '@/components/electoral/LeafletElectionMap';
import {number} from '@/lib/electoral/analysis';
export function ZoneLayers({uf,year,turn,office,target,municipality,zone}:{uf:string;year:number;turn:number;office:number;target?:Target;municipality:string;zone:string}){
 const [mode,setMode]=useState<'all'|'votes'>('all'),[data,setData]=useState<ZoneMapData|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[selected,setSelected]=useState('');
 const request=JSON.stringify({uf,year,turn,office,target,filters:{...(municipality?{municipality:Number(municipality)}:{}),...(zone?{zone:Number(zone)}:{})}});
 useEffect(()=>{const abort=new AbortController();setLoading(true);setError('');setData(null);setSelected('');fetch('/api/admin/science/zones',{method:'POST',headers:{'Content-Type':'application/json'},body:request,signal:abort.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);}).catch(e=>{if(!abort.signal.aborted)setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[request]);
 useEffect(()=>{if(!target)setMode('all');},[Boolean(target)]);
 const visible=useMemo(()=>filterZoneLayer(data?.rows??[],mode),[data,mode]);
 const places=useMemo<LocalComparison[]>(()=>visible.map(r=>({key:r.key,uf:r.uf,municipality:r.municipality,municipality_name:r.municipality_name,zone:r.zone,local:null,name:`Zona ${r.zone} · ${r.municipality_name}/${r.uf}`,address:'',latitude:r.latitude,longitude:r.longitude,coordinate_year:r.coordinate_year_max,section_count:r.sections_count??undefined,granularity:'zone',marker_color:zoneMarkerColor(r,mode),marker_label:mode==='votes'?number(r.votes):String(r.zone),urnas_count:r.urnas_count,new_label:String(year),sections:[{uf:r.uf,municipality:r.municipality,municipality_name:r.municipality_name,zone:r.zone,section:0,old_votes:null,new_votes:r.votes,old_valid:null,new_valid:r.valid,old_local:null,new_local:null,old_name:null,new_name:null,latitude:r.latitude,longitude:r.longitude,address:null,coordinate_year:r.coordinate_year_max}]})),[visible,mode,year]);
 const pick=useCallback((key:string)=>setSelected(key),[]),point=visible.find(r=>r.key===selected);
 const missingCoordinates=visible.filter(r=>r.latitude===null||r.longitude===null).length;
 return <section className="electoral-panel"><h2>Mapa de zonas eleitorais</h2><div className="science-actions no-print"><label>Camada eleitoral<select aria-label="Camada eleitoral" value={mode} onChange={e=>{setMode(e.target.value as 'all'|'votes');setSelected('');}}><option value="all">Todas as zonas</option><option value="votes" disabled={!target}>Zonas com votação</option></select></label><span className="science-zone-legend"><i style={{background:mode==='all'?'#2165b5':'#c63438'}}/>{mode==='all'?'Azul · todas as zonas da cobertura':'Vermelho · votos positivos; número no círculo = votos'}</span></div>
 {!target&&<p>Selecione uma candidatura ou partido nos filtros para visualizar as zonas com votação.</p>}{data?.selection_pending&&<p className="electoral-notice">Candidatura cadastrada, mas os votos deste recorte ainda não foram importados. Não significa zero voto.</p>}{error&&<p role="alert" className="electoral-notice">{error}</p>}{loading&&<p role="status">Consultando zonas e votação…</p>}
 {data&&<><p className="electoral-caption">{visible.length} zonas exibidas de {data.total_rows} na cobertura. {missingCoordinates} sem coordenadas permanecem na tabela. {data.notice}</p>{data.truncated&&<p className="electoral-notice">Limite de 5.000 zonas. Restrinja a UF ou município; o mapa não representa toda a base neste recorte.</p>}
 <div className="science-map-layout"><div className="science-map-canvas"><LeafletElectionMap places={places} onSelect={pick}/></div><aside className="science-map-detail" aria-live="polite"><h3>{point?`Zona ${point.zone}`:'Selecione uma zona'}</h3>{point?<><p>{point.municipality_name}/{point.uf}</p><div className="science-detail-votes"><small>{data.selection_name??'Sem candidato selecionado'} · {year}</small><strong>{number(point.votes)} votos</strong><span>{point.vote_status==='missing'?'Resultado indisponível':point.vote_status==='zero'?'Zero confirmado no recorte':'Votação positiva'}</span></div><dl><dt>Seções na base do cargo</dt><dd>{number(point.sections_count)}</dd><dt>Urnas físicas identificadas nos BUs</dt><dd>{number(point.urnas_count)}</dd><dt>Locais cadastrados</dt><dd>{number(point.locations_count)}</dd><dt>Ano das referências cartográficas</dt><dd>{point.coordinate_year_min??'Sem dados'}{point.coordinate_year_max!==point.coordinate_year_min?` a ${point.coordinate_year_max}`:''}</dd></dl><p className="electoral-caption">Seções e urnas físicas têm contagens diferentes. Este ponto é uma referência média dos locais, não um limite oficial.</p></>:<p>Clique em um círculo ou na tabela para consultar seus votos e contagens.</p>}</aside></div>
 <div className="science-table"><table><thead><tr><th>Zona</th><th>Município / UF</th><th>Seções</th><th>Urnas identificadas</th><th>Votos selecionados</th><th>Situação</th></tr></thead><tbody>{visible.map(r=><tr key={r.key} className={r.key===selected?'selected':''}><td><button className="science-territory-select" onClick={()=>pick(r.key)}>Zona {r.zone}</button></td><td>{r.municipality_name}/{r.uf}</td><td>{number(r.sections_count)}</td><td>{number(r.urnas_count)}</td><td>{number(r.votes)}</td><td>{r.vote_status==='missing'?'Sem resultado':r.vote_status==='zero'?'Zero confirmado':'Com votação'}{r.latitude===null||r.longitude===null?' · sem coordenadas':''}</td></tr>)}</tbody></table></div>{mode==='votes'&&!visible.length&&<p>Nenhuma zona com voto positivo disponível para a seleção. Confira a cobertura e a sincronização.</p>}</>}
 </section>;
}
