import type {ComparisonColumn,ComparisonLine,ComparisonCell} from './multi-comparison';
import type {ScienceReport} from './types';
import type {historicalSnapshot,HistoricalStatus} from './historical-coverage';
export type PrintOptions={details:boolean;exportedAt:string;version:string};
const esc=(value:unknown)=>String(value??'Não informado').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const n=(value:number|null|undefined)=>value==null||!Number.isFinite(value)?'Sem dados':value.toLocaleString('pt-BR',{maximumFractionDigits:2});
const pct=(value:number|null|undefined)=>value==null||!Number.isFinite(value)?'Não calculável':n(value)+'%';
const p=(value:unknown)=>`<p>${esc(value)}</p>`;
const table=(headers:string[],rows:string[][])=>`<table><thead><tr>${headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(row=>'<tr>'+row.map((cell,i)=>`<${i===0?'th scope="row"':'td'}>${cell}</${i===0?'th':'td'}>`).join('')+'</tr>').join(''):`<tr><td colspan="${headers.length}">Nenhuma linha territorial retornada.</td></tr>`}</tbody></table>`;
const labels:Record<string,string>={uf:'UF',year:'Ano',office:'Cargo',turn:'Turno',kind:'Tipo de seleção',scope:'Escopo',filters:'Filtros',municipality:'Código do município',zone:'Zona',local:'Local',section:'Seção',common_only:'Somente chaves comuns',old:'Seleção anterior',new:'Seleção posterior',name:'Nome',number:'Número',election:'Eleição',candidate_id:'Identificador da candidatura',party:'Partido',source_url:'Fonte',results_available:'Resultados disponíveis',office_name:'Nome do cargo',numbers:'Números'};
const officeName:Record<number,string>={1:'Presidente',3:'Governador',5:'Senador',6:'Deputado federal',7:'Deputado estadual',8:'Deputado distrital'};
function params(value:unknown){const rows:string[][]=[];function walk(item:unknown,path:string[]){if(item&&typeof item==='object'&&!Array.isArray(item)){const entries=Object.entries(item);if(!entries.length)rows.push([esc(path.join(' / ')||'Recorte'),esc('Sem filtros adicionais')]);for(const [key,v] of entries)walk(v,[...path,labels[key]??key]);}else rows.push([esc(path.join(' / ')||'Recorte'),esc(typeof item==='boolean'?(item?'Sim':'Não'):Array.isArray(item)?item.join(', '):item)]);}walk(value,[]);return table(['Parâmetro','Valor'],rows);}

const sources=(report:ScienceReport)=>`<section class="sources"><h3>Fontes e rastreabilidade</h3>${p('Protocolo: '+(report.analysis_id??'não arquivado'))}${p('SHA-256 do relatório original: '+(report.result_sha256??'não informado'))}${p('Dados gerados em: '+report.generated_at)}${p('Granularidade: '+(report.granularity??'não informada')+' · denominador: '+(report.denominator_basis??'votos válidos'))}${p(`Linhas retornadas: ${report.rows.length} de ${report.total_rows}. ${report.truncated?'Carga limitada.':'Sem truncamento informado.'}`)}${report.notice?p(report.notice):''}${report.coverage.map(p).join('')}${report.sources.length?report.sources.map(s=>p(`${s.year} · ${s.filename} · ${s.source_url} · importado em ${s.finished_at}`)).join(''):p('Nenhuma fonte registrada no relatório recebido.')}</section>`;
function documentHtml(title:string,body:string,options:PrintOptions){return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>${esc(title)} · IBFC</title><style>
*{box-sizing:border-box}body{margin:0;color:#172338;background:#edf1f5;font:15px/1.5 Arial,sans-serif}main{max-width:1200px;margin:24px auto;padding:40px;background:#fff}header{border-bottom:3px solid #173c64;padding-bottom:18px}header small{letter-spacing:2px;color:#173c64}h1{font-size:30px;line-height:1.2}h2{font-size:21px;color:#173c64;margin-top:30px}h3{font-size:17px}p,pre,td,th{overflow-wrap:anywhere}pre{white-space:pre-wrap;font-size:12px;background:#f3f6f8;padding:12px}.notice{padding:12px;border-left:4px solid #af7928;background:#fff7e8}table{width:100%;border-collapse:collapse;table-layout:fixed;margin:16px 0;font-size:12px}th,td{border:1px solid #cdd6e0;padding:8px;vertical-align:top;text-align:left}thead{background:#173c64;color:white}tbody th{font-weight:normal}tbody tr:nth-child(even){background:#f5f7fa}.sources{font-size:12px;border-top:1px solid #cdd6e0;margin-top:22px;padding-top:8px}footer{border-top:2px solid #173c64;padding-top:12px;margin-top:28px;font-size:12px}.instructions{max-width:1200px;margin:20px auto;padding:12px;color:#173c64}@media(max-width:640px){main{margin:0;padding:16px}table{font-size:10px}th,td{padding:4px}}@page{size:A4 landscape;margin:14mm}@media print{body{background:white;font-size:11px}main{max-width:none;margin:0;padding:0}.instructions{display:none}h1{font-size:23px}h2{font-size:17px;break-after:avoid}h3{break-after:avoid}table{font-size:10px}thead{display:table-header-group}tr{break-inside:avoid}section{break-inside:auto}pre{font-size:10px}footer{font-size:9px}th,td{padding:5px}*{print-color-adjust:exact;-webkit-print-color-adjust:exact}}
</style></head><body><p class="instructions">Para salvar em PDF: Ctrl+P (ou menu Imprimir) → destino “Salvar como PDF”. Este documento não usa conexão de rede.</p><main><header><small>IBFC · CIÊNCIA ELEITORAL</small><h1>${esc(title)}</h1>${p('Exportado em: '+options.exportedAt+' · versão '+options.version)}</header>${body}<footer>Resultados eleitorais públicos agregados. Ausência de dados não significa zero voto. Esta análise não identifica o voto de pessoas, fidelidade individual ou transferência de eleitores. Os protocolos e hashes referem-se aos relatórios originais, não a este HTML ou PDF.</footer></main></body></html>`;}
export function comparisonPrintHtml(columns:ComparisonColumn[],lines:ComparisonLine[],totals:ComparisonCell[],parameters:unknown,options:PrintOptions){
 if(columns.length<2||columns.length>10||totals.length!==columns.length||lines.some(l=>l.cells.length!==columns.length))throw Error('Comparação incompleta para gerar o relatório.');
 let body='<h2>Recorte consultado</h2>'+params(parameters)+'<p class="notice">Consultas sequenciais, com horários próprios; não são uma transação única. Os totais abaixo vêm dos relatórios, não da soma das linhas retornadas. A comparação considera apenas as seleções escolhidas, sem representar classificação geral da eleição.</p>';
 body+=table(['Seleção','Ano / cargo / turno','Votos no recorte','Denominador','Participação'],columns.map((c,i)=>[esc(c.target.name),esc(`${c.target.year} · ${officeName[c.target.office]??('cargo '+c.target.office)} · ${c.target.turn}º turno`),esc(n(totals[i].votes)),esc(n(totals[i].valid)),esc(pct(totals[i].share))]));
 if(columns.some(c=>c.report.truncated))body+=p('ATENÇÃO: há carga limitada. O detalhamento inclui somente os registros retornados.');
 body+=p(`Detalhamento disponível: ${lines.length} territórios. ${options.details?'Incluído integralmente, sem paginação da tela.':'Não incluído nesta versão resumida. Consulte CSV/JSON ou gere com detalhamento.'}`);
 if(options.details){for(let start=0;start<columns.length;start+=3){const chunk=columns.slice(start,start+3);body+='<h2>Detalhamento territorial · seleções '+(start+1)+' a '+(start+chunk.length)+'</h2>'+table(['Território / UF / município / zona',...chunk.map(c=>c.target.name),'Denominadores'],lines.map(l=>[esc(`${l.territory.name} · ${l.territory.uf} · município ${l.territory.municipality} · zona ${l.territory.zone}`),...l.cells.slice(start,start+3).map(cell=>esc(n(cell.votes)+' votos')+'<br>'+esc(pct(cell.share)+' · base '+n(cell.valid))),esc(l.comparable?'Compatíveis em todas as seleções':'Não comparáveis / sem dados')]));}}
 body+='<h2>Fontes por seleção</h2>'+columns.map(c=>'<h3>'+esc(c.target.name)+'</h3>'+sources(c.report)).join('');return documentHtml('Comparação eleitoral consolidada',body,options);
}
export function historicalPrintHtml(snapshot:ReturnType<typeof historicalSnapshot>,report:ScienceReport,labels:Record<HistoricalStatus,string>,options:PrintOptions){
 const c=snapshot.coverage;let body='<h2>Recorte histórico</h2>'+params(snapshot.parameters)+p('Método: '+snapshot.method_version)+'<p class="notice">'+esc(snapshot.notice)+'</p>';
 body+=table(['Indicador','Valor'],[['Dados nos dois anos',esc(n(c.both_years)+' de '+n(c.available_rows)+' com dados em pelo menos um ano')],['Cobertura nos dois anos',esc(pct(c.both_years_percent))],['Dados somente no ano anterior',esc(n(c.counts.old_only))],['Dados somente no ano posterior',esc(n(c.counts.new_only))],['Votos do recorte anterior',esc(n(report.totals.old_votes))],['Votos do recorte posterior',esc(n(report.totals.new_votes))]]);
 body+=p(`Linhas do diagnóstico: ${c.visible_rows} de ${c.total_rows}. ${c.truncated?'Carga limitada: proporções descrevem somente linhas retornadas.':'Sem truncamento informado.'}`)+p('Chaves iguais não certificam continuidade territorial ou identidade de eleitores. Diferenças refletem apenas os registros e denominadores disponíveis. Variação relativa com base anterior zero não é calculável.');
 body+=p(options.details?'Detalhamento completo retornado; a busca e classificação da tela não são aplicadas.':'Detalhamento não incluído nesta versão resumida.');
 if(options.details)body+='<h2>Diagnóstico por território</h2>'+table(['Território / UF / zona','Classificação','Votos anteriores','Votos posteriores','Diferença','Variação relativa','Variação pp'],c.lines.map(l=>[esc(`${l.row.name} · ${l.row.uf} · zona ${l.row.zone}`),esc(labels[l.status]),esc(n(l.row.old_votes)),esc(n(l.row.new_votes)),esc(l.delta_votes===null?'Não calculável':n(l.delta_votes)),esc(pct(l.relative_change)),esc(l.delta_points===null?'Não calculável':n(l.delta_points)+' pp')]));
 body+=sources(report);return documentHtml('Diagnóstico eleitoral histórico',body,options);
}

export function archivedPrintHtml(archive:import('./report-archive').ArchivedAnalysis,options:PrintOptions){const report=archive.result_snapshot;if(!report||archive.integrity_verified!==true)throw Error('Integridade não confirmada.');const r={...report,analysis_id:archive.id,result_sha256:archive.result_sha256};let body=p('Arquivado em: '+archive.created_at+' · método original: '+archive.method_version)+p('Hash do resultado confere. Esta conferência não certifica a exatidão da fonte nem os parâmetros.')+'<h2>Parâmetros originais</h2>'+params(archive.parameters??{})+'<h2>Totais originais</h2>'+params(r.totals)+p('Os totais são os guardados na análise; não foram recalculados pela soma das linhas.');if(options.details)body+=table(['Território','Votos A','Votos B','Válidos A','Válidos B'],r.rows.map(x=>[esc(x.name),esc(n(x.old_votes)),esc(n(x.new_votes)),esc(n(x.old_valid)),esc(n(x.new_valid))]));return documentHtml('Relatório eleitoral arquivado',body+sources(r),options);}
