import type {TemporalResult} from './temporal-models';
import type {ScienceReport} from './types';
export type ArchivedAnalysis={id:string;created_at:string;method_version:string;parameters?:{mode?:string;scope?:string;old?:{name?:string;year?:number;uf?:string};new?:{name?:string;year?:number;uf?:string}};result_sha256:string;result_snapshot?:ScienceReport&{temporal?:TemporalResult};integrity_verified?:boolean};
export const PAGE_SIZE=50;
export const validId=(id:string)=>/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(id);
export function archiveQuery(p:URLSearchParams){const id=p.get('id'),raw=p.get('offset')??'0';if(id!==null&&!validId(id))throw Error('Protocolo inválido.');if(!/^\d+$/.test(raw)||Number(raw)>10000)throw Error('Página inválida.');return {id,offset:Number(raw)};}
export function usableSnapshot(v:unknown):v is ScienceReport {if(!v||typeof v!=='object')return false;const r=v as ScienceReport;return Array.isArray(r.rows)&&r.rows.every(x=>x&&typeof x.key==='string'&&typeof x.name==='string'&&['old_votes','new_votes','old_valid','new_valid'].every(k=>x[k as keyof typeof x]===null||typeof x[k as keyof typeof x]==='number'))&&Array.isArray(r.sources)&&r.sources.every(x=>x&&typeof x.filename==='string'&&typeof x.source_url==='string')&&Array.isArray(r.coverage)&&r.coverage.every(x=>typeof x==='string')&&typeof r.generated_at==='string'&&typeof r.total_rows==='number'&&typeof r.truncated==='boolean'&&!!r.totals&&['old_votes','new_votes','old_valid','new_valid','old_sections','new_sections','common_sections','moved_sections'].every(k=>r.totals[k as keyof typeof r.totals]===null||typeof r.totals[k as keyof typeof r.totals]==='number');}
export function sourceHref(raw:string){try{const u=new URL(raw);return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password?u.href:null;}catch{return null;}}
const cell=(v:unknown)=>{let s=String(v??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};
export function archivedCsv(a:ArchivedAnalysis){if(!usableSnapshot(a.result_snapshot))throw Error('Resultado incompatível.');const r=a.result_snapshot;return '\ufeff'+[['Protocolo',a.id],['Método original',a.method_version],['SHA-256',a.result_sha256],['Integridade',a.integrity_verified===true?'confere':'não confirmada'],['Parâmetros',JSON.stringify(a.parameters??{})],['Totais originais',JSON.stringify(r.totals)],['Carga limitada',r.truncated],['Território','UF','Zona','Seção','Votos A','Votos B','Válidos A','Válidos B'],...r.rows.map(x=>[x.name,x.uf,x.zone,x.section,x.old_votes,x.new_votes,x.old_valid,x.new_valid]),...r.sources.map(s=>['Fonte',s.year,s.filename,s.source_url])].map(row=>row.map(cell).join(';')).join('\r\n');}

export function usableTemporal(v:unknown):v is TemporalResult {if(!v||typeof v!=='object')return false;const r=v as TemporalResult;const num=(x:unknown)=>typeof x==='number'&&Number.isFinite(x);return ['common_territories','union_territories','excluded_territories','projection_year'].every(k=>num(r[k as keyof TemporalResult]))&&typeof r.notice==='string'&&Array.isArray(r.folds)&&r.folds.every(f=>f&&num(f.year)&&Array.isArray(f.train_years)&&f.train_years.every(num)&&f.persistence&&f.linear&&[f.persistence.mae,f.persistence.rmse,f.linear.mae,f.linear.rmse].every(num))&&Array.isArray(r.projections)&&r.projections.every(p=>p&&typeof p.key==='string'&&typeof p.name==='string'&&[p.last_share,p.persistence,p.linear].every(num));}
