import {usableSnapshot,type ArchivedAnalysis} from './report-archive';
export type WorkbookSheet={name:string;rows:(string|number|null|undefined|boolean)[][]};
const xml=(v:unknown)=>String(v??'').replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));
const column=(n:number):string=>n<26?String.fromCharCode(65+n):column(Math.floor(n/26)-1)+String.fromCharCode(65+n%26);
function crc(bytes:Uint8Array){let c=0xffffffff;for(const b of bytes){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
/** ZIP stored entries: no extra client dependency, all fields little-endian. */
function zip(entries:[string,string][]):Uint8Array{const chunks:Uint8Array[]=[],central:Uint8Array[]=[];let offset=0;const enc=new TextEncoder();for(const [name,text] of entries){const n=enc.encode(name),data=enc.encode(text),sum=crc(data);const h=new Uint8Array(30+n.length),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint32(14,sum,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,n.length,true);h.set(n,30);chunks.push(h,data);const c=new Uint8Array(46+n.length),d=new DataView(c.buffer);d.setUint32(0,0x02014b50,true);d.setUint16(4,20,true);d.setUint16(6,20,true);d.setUint32(16,sum,true);d.setUint32(20,data.length,true);d.setUint32(24,data.length,true);d.setUint16(28,n.length,true);d.setUint32(42,offset,true);c.set(n,46);central.push(c);offset+=h.length+data.length;}const size=central.reduce((s,c)=>s+c.length,0),end=new Uint8Array(22),e=new DataView(end.buffer);e.setUint32(0,0x06054b50,true);e.setUint16(8,entries.length,true);e.setUint16(10,entries.length,true);e.setUint32(12,size,true);e.setUint32(16,offset,true);const out=new Uint8Array(offset+size+22);let p=0;for(const c of [...chunks,...central,end]){out.set(c,p);p+=c.length;}return out;}
export function workbookBytes(sheets:WorkbookSheet[]){if(!sheets.length||sheets.length>30)throw Error('Quantidade de abas inválida.');const names=new Set<string>();for(const s of sheets){if(!s.name||s.name.length>31||/[\[\]:*?\/\\]/.test(s.name)||names.has(s.name.toLowerCase()))throw Error('Nome de aba inválido ou repetido.');names.add(s.name.toLowerCase());if(s.rows.length>1048576||s.rows.some(r=>r.length>16384||r.some(c=>typeof c==='string'&&c.length>32767)))throw Error('Dados excedem os limites do Excel.');}
const entries:[string,string][]=[['[Content_Types].xml',`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>${sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`],['_rels/.rels','<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'],['xl/workbook.xml',`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map((s,i)=>`<sheet name="${xml(s.name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`],['xl/_rels/workbook.xml.rels',`<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}</Relationships>`]];
sheets.forEach((s,i)=>entries.push([`xl/worksheets/sheet${i+1}.xml`,`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>${Array.from({length:Math.max(1,...s.rows.map(r=>r.length))},(_,c)=>`<col min="${c+1}" max="${c+1}" width="${c===0?38:24}" customWidth="1"/>`).join('')}</cols><sheetData>${s.rows.map((row,r)=>`<row r="${r+1}">${row.map((c,k)=>{const ref=column(k)+(r+1);return c==null?'':typeof c==='number'&&Number.isFinite(c)?`<c r="${ref}"><v>${c}</v></c>`:`<c r="${ref}" t="inlineStr"><is><t xml:space="preserve">${xml(c)}</t></is></c>`;}).join('')}</row>`).join('')}</sheetData></worksheet>`]));return zip(entries);}
export function archiveSheets(archives:ArchivedAnalysis[]):WorkbookSheet[]{if(!archives.length||archives.length>10)throw Error('Escolha de 1 a 10 análises.');const index:WorkbookSheet={name:'Protocolos',rows:[['Protocolo','Método','Arquivado em','Hash','Integridade','Parâmetros','Linhas recebidas','Total de linhas','Carga limitada']]};const result=[index];archives.forEach((a,i)=>{const r=a.result_snapshot;if(!usableSnapshot(r))throw Error('Snapshot incompatível: '+a.id);index.rows.push([a.id,a.method_version,a.created_at,a.result_sha256,a.integrity_verified===true?'confere':'não confirmada',JSON.stringify(a.parameters??{}),r.rows.length,r.total_rows,r.truncated]);result.push({name:'Analise '+(i+1),rows:[['Totais originais (sem somar análises)'],['Votos A','Votos B','Válidos A','Válidos B'],[r.totals.old_votes,r.totals.new_votes,r.totals.old_valid,r.totals.new_valid],['Território','UF','Município','Zona','Local','Seção','Votos A','Votos B','Válidos A','Válidos B'],...r.rows.map(x=>[x.name,x.uf,x.municipality,x.zone,x.local,x.section,x.old_votes,x.new_votes,x.old_valid,x.new_valid]),['Fontes','Ano','Arquivo','URL','Importado em'],...r.sources.map(x=>['Fonte',x.year,x.filename,x.source_url,x.finished_at])]});});return result;}
export const archiveWorkbook=(archives:ArchivedAnalysis[])=>workbookBytes(archiveSheets(archives));
