import type {LocalComparison} from '@/lib/electoral/types';
import type {ZoneMapData} from './map-layers';
export type LayerSettings={zones:boolean;votes:boolean;locations:boolean};
export const DEFAULT_LAYERS:LayerSettings={zones:true,votes:false,locations:false};
export type TerritorialPoint=LocalComparison&{layer_kind:'zone'|'location';marker_color:string;marker_label?:string;marker_caption:string;marker_radius?:number;urnas_count?:number|null;votes:number|null;valid:number|null;vote_status:'positive'|'zero'|'missing'};
export function readLayerSettings(value:unknown):LayerSettings{if(!value||typeof value!=='object')return {...DEFAULT_LAYERS};const b=value as Record<string,unknown>;return {zones:typeof b.zones==='boolean'?b.zones:true,votes:typeof b.votes==='boolean'?b.votes:false,locations:typeof b.locations==='boolean'?b.locations:false};}
export function hasCoordinates(p:{latitude:number|null;longitude:number|null}){return p.latitude!==null&&p.longitude!==null&&Number.isFinite(p.latitude)&&Number.isFinite(p.longitude)&&Math.abs(p.latitude)<=90&&Math.abs(p.longitude)<=180;}
export function buildTerritorialPoints(data:ZoneMapData|null,locations:LocalComparison[],settings:LayerSettings,year:number):TerritorialPoint[]{
 const rows=data?.rows??[],max=Math.max(1,...rows.map(r=>r.votes??0));
 const zones=rows.filter(r=>settings.zones||settings.votes&&r.votes!==null&&r.votes>0).map(r=>{const highlighted=settings.votes&&r.votes!==null&&r.votes>0;return {key:'zone:'+r.key,uf:r.uf,municipality:r.municipality,municipality_name:r.municipality_name,zone:r.zone,local:null,name:`Zona ${r.zone} · ${r.municipality_name}/${r.uf}`,address:'',latitude:r.latitude,longitude:r.longitude,coordinate_year:r.coordinate_year_max,section_count:r.sections_count??undefined,granularity:'zone' as const,layer_kind:'zone' as const,marker_color:highlighted?'#c63438':'#2165b5',marker_label:highlighted?r.votes!.toLocaleString('pt-BR'):String(r.zone),marker_caption:'Referência média dos locais, sem delimitação oficial de área.',marker_radius:highlighted?Math.min(34,22+12*Math.sqrt(r.votes!/max)):22,urnas_count:r.urnas_count,votes:r.votes,valid:r.valid,vote_status:r.vote_status,new_label:String(year),sections:[{uf:r.uf,municipality:r.municipality,municipality_name:r.municipality_name,zone:r.zone,section:0,old_votes:null,new_votes:r.votes,old_valid:null,new_valid:r.valid,old_local:null,new_local:null,old_name:null,new_name:null,latitude:r.latitude,longitude:r.longitude,address:null,coordinate_year:r.coordinate_year_max}]};});
 return [...zones,...(settings.locations?locations.map(p=>({...p,key:'location:'+p.key,sections:[],layer_kind:'location' as const,marker_color:'#8058ad',marker_caption:'Local cadastrado. Votos por escola/seção devem ser consultados no recorte detalhado, quando disponíveis.',marker_radius:8,votes:null,valid:null,vote_status:'missing' as const})):[])];
}
export function searchTerritorialPoints(rows:TerritorialPoint[],query:string){const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const words=normalize(query.trim().slice(0,120)).split(/\s+/).filter(Boolean);return rows.filter(p=>words.every(word=>normalize(`${p.name} ${p.address} ${p.municipality_name} ${p.uf} zona ${p.zone} ${p.local??''}`).includes(word)));}
export type LayerSnapshot={schema_version:1;generated_at:string;data_generated_at:string|null;query:unknown;layers:LayerSettings;search:string;zones_total:number;locations_total:number;zones_truncated:boolean;locations_truncated:boolean;rows:TerritorialPoint[]};
const cell=(v:unknown)=>{let s=String(v??'');if(/^[\s]*[=+\-@]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};
export function territorialCsv(s:LayerSnapshot){const header=['Gerado em','Dados de zonas em','Recorte JSON','Camadas JSON','Busca','Limite de zonas atingido','Limite de locais atingido','Tipo','Identificador','Nome','UF','Município','Zona','Local','Latitude','Longitude','Ano cartográfico','Votos','Situação de votos'];return '\ufeff'+[header,...s.rows.map(p=>[s.generated_at,s.data_generated_at,JSON.stringify(s.query),JSON.stringify(s.layers),s.search,s.zones_truncated,s.locations_truncated,p.layer_kind,p.key,p.name,p.uf,p.municipality,p.zone,p.local,p.latitude,p.longitude,p.coordinate_year,p.votes,p.vote_status])].map(row=>row.map(cell).join(';')).join('\r\n')+'\r\n';}
