import {NextRequest,NextResponse} from 'next/server';
import {electoralStaff} from '@/lib/electoral/auth';
export const dynamic='force-dynamic';
const reply=(data:unknown,status=200)=>NextResponse.json(data,{status,headers:{'Cache-Control':'private, no-store'}});
const uuid=(v:unknown)=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v);
const link=(v:unknown)=>{try{const u=new URL(String(v));return u.protocol==='https:'&&!u.username&&!u.password&&u.hostname.length>0&&String(v).length<=2000;}catch{return false;}};
export async function GET(request:NextRequest){const {db,allowed}=await electoralStaff();if(!allowed)return reply({error:'Acesso administrativo necessário.'},403);const q=request.nextUrl.searchParams,id=q.get('id'),candidate=q.get('candidate_id'),status=q.get('status'),offset=Number(q.get('offset')??0);if(id&&!uuid(id)||candidate&&!uuid(candidate)||!Number.isSafeInteger(offset)||offset<0||offset>100000||status&&!['registered','in_progress','fulfilled','unfulfilled','cancelled'].includes(status))return reply({error:'Filtro inválido.'},400);
if(id){const {data,error}=await db.from('ibfc_commitment_history').select('*').eq('commitment_id',id).order('occurred_at',{ascending:false}).order('id',{ascending:false}).range(offset,offset+19);return error?reply({error:'Histórico indisponível.'},503):reply({rows:data,offset,page_size:20});}
let query=db.from('ibfc_public_commitments').select('*, candidates(name,state_uf)',{count:'exact'}).order('updated_at',{ascending:false}).order('id',{ascending:false});if(candidate)query=query.eq('candidate_id',candidate);if(status)query=query.eq('status',status);const {data,error,count}=await query.range(offset,offset+19);return error?reply({error:'Execute a migração 20261031 e atualize a página.'},503):reply({rows:data,total:count,offset,page_size:20});}
export async function POST(request:NextRequest){const {db,allowed}=await electoralStaff();if(!allowed)return reply({error:'Acesso administrativo necessário.'},403);if(request.headers.get('origin')!==request.nextUrl.origin)return reply({error:'Origem inválida.'},403);let b;try{const raw=await request.text();if(raw.length>15000)return reply({error:'Pedido muito grande.'},413);b=JSON.parse(raw);}catch{return reply({error:'Pedido inválido.'},400);}if(!uuid(b?.request_id)||!uuid(b.candidate_id)||b.id&&!uuid(b.id)||b.id&&(!Number.isSafeInteger(b.version)||b.version<1)||typeof b.title!=='string'||b.title.trim().length<3||b.title.length>180||typeof b.description!=='string'||b.description.length>5000||!link(b.source_url)||typeof b.review_note!=='string'||b.review_note.trim().length<10||b.review_note.length>2000||!['registered','in_progress','fulfilled','unfulfilled','cancelled'].includes(b.status)||b.evidence_url&&!link(b.evidence_url)||['fulfilled','unfulfilled','cancelled'].includes(b.status)&&!b.evidence_url||b.deadline&&(!/^\d{4}-\d{2}-\d{2}$/.test(b.deadline)||!Number.isFinite(Date.parse(b.deadline))||new Date(b.deadline).toISOString().slice(0,10)!==b.deadline))return reply({error:'Confira os campos. Toda avaliação precisa de justificativa; conclusões exigem uma evidência HTTPS.'},400);
const {data,error}=await db.rpc('ibfc_commitment_save',{p_request:b.request_id,p_id:b.id||null,p_version:b.version||null,p_candidate:b.candidate_id,p_title:b.title,p_description:b.description,p_source:b.source_url,p_deadline:b.deadline||null,p_status:b.status,p_evidence:b.evidence_url||null,p_note:b.review_note});return error?reply({error:'Não foi possível salvar. Atualize para verificar alterações concorrentes e confira a migração.'},409):reply(data);}
