import {NextRequest,NextResponse} from 'next/server';
import {electoralStaff} from '@/lib/electoral/auth';
import {UFS} from '@/lib/science/territory';
import {validLocation} from '@/lib/community/map';
export const dynamic='force-dynamic';
const reply=(body:unknown,status=200)=>NextResponse.json(body,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(r:NextRequest){const {db,allowed}=await electoralStaff();if(!allowed)return reply({error:'Acesso administrativo necessário.'},403);const uf=r.nextUrl.searchParams.get('uf')??'';if(uf&&!UFS.includes(uf))return reply({error:'UF inválida.'},400);const {data,error}=await db.rpc('ibfc_community_map',{p_uf:uf||null});if(error)return reply({error:'Instale a migração 20261021_ibfc_community_map.sql após 20261019 e 20261020.'},503);return reply(data);}
export async function POST(r:NextRequest){const {db,user,allowed}=await electoralStaff();if(!allowed)return reply({error:'Acesso administrativo necessário.'},403);if(r.headers.get('origin')!==r.nextUrl.origin)return reply({error:'Origem inválida.'},403);let b;try{b=await r.json();}catch{return reply({error:'Pedido inválido.'},400);}if(!b||typeof b!=='object'||!(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(b.id??''))||!validLocation(b.latitude,b.longitude,b.note,b.confirmed))return reply({error:'Informe coordenadas válidas, referência e confirmação do ponto público.'},400);
 const cleared=b.latitude==null||b.latitude==='';const {data,error}=await db.from('ibfc_community_organizations').update({latitude:cleared?null:b.latitude,longitude:cleared?null:b.longitude,location_note:cleared?'':b.note.trim(),location_verified_at:cleared?null:new Date().toISOString(),location_verified_by:cleared?null:user!.id}).eq('id',b.id).select('id');if(error)return reply({error:'Não foi possível salvar. Confira a migração e permissões.'},400);if(!data?.length)return reply({error:'Organização não encontrada.'},404);return reply({ok:true});}
